[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$PolicyPath)
$ErrorActionPreference='Stop'
$unit=Split-Path -Parent $PSScriptRoot
$repo=(Resolve-Path (Join-Path $unit '..\..')).Path
$policy=Get-Content -LiteralPath $PolicyPath -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Add-Error($message){$errors.Add([string]$message)}
function Eq($name,$actual,$expected){if($actual-ne$expected){Add-Error "$name expected=$expected actual=$actual"}}
function Seq($name,$actual,$expected){$a=if($null-eq$actual){@()}else{@($actual)};$e=if($null-eq$expected){@()}else{@($expected)};if(($a|ConvertTo-Json -Compress -Depth 20)-ne($e|ConvertTo-Json -Compress -Depth 20)){Add-Error "$name sequence mismatch"}}
function Exact-Keys($name,$object,$expected){$actual=@($object.PSObject.Properties.Name|Sort-Object);$wanted=@($expected|Sort-Object);Seq "$name keys" $actual $wanted}
function Load($path){Get-Content -LiteralPath $path -Raw -Encoding UTF8|ConvertFrom-Json}
function Find-ExactSessionMessage($sourcePath,$expected){
 if($null-eq$global:Logh7AuthorityMessageCache){$global:Logh7AuthorityMessageCache=@{}}
 $cacheKey=([IO.Path]::GetFullPath($sourcePath)+'|'+[string]$expected.messageId+'|'+[string]$expected.rawLineSha256+'|'+[string]$expected.lineNumberOneBased)
 if($global:Logh7AuthorityMessageCache.ContainsKey($cacheKey)){return $global:Logh7AuthorityMessageCache[$cacheKey]}
 $utf8=[Text.UTF8Encoding]::new($false);$stream=$null;$reader=$null;$lineNumber=0;$matches=@()
 try{
  $stream=[IO.FileStream]::new($sourcePath,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::ReadWrite)
  $reader=[IO.StreamReader]::new($stream,$utf8,$true)
  while(($line=$reader.ReadLine())-ne$null){
   $lineNumber++;if(-not$line.Contains([string]$expected.messageId)){continue}
   try{$item=$line|ConvertFrom-Json}catch{continue}
   if($item.type-ne'response_item'-or$item.payload.type-ne'message'-or$item.payload.id-ne$expected.messageId){continue}
   $matches+=,[ordered]@{lineNumber=$lineNumber;item=$item;rawLineSha256=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($utf8.GetBytes($line)))}
  }
 }finally{if($null-ne$reader){$reader.Dispose()}elseif($null-ne$stream){$stream.Dispose()}}
 if($matches.Count-ne1){Add-Error "message $($expected.messageId) exact response-item count expected=1 actual=$($matches.Count)";return $null}
 $global:Logh7AuthorityMessageCache[$cacheKey]=$matches[0]
 return $matches[0]
}
$expectedHashes=[ordered]@{
 currentAuthorityRecord='72668E9B5F7EFDAD00C9E8100927889ABE8D751510B0ECCC7B4915C7C4297D93'
 authorityMessageChronology='899D0FA447146EE7580406D561887AA749ABDD8CD4543641FB01991702213757'
 historicalAuthorityRecord='284FE30A5239C50660B2153658931BBAF776BD84AAB7CF6E74E9992CB5ED3C37'
 historicalLaunchPermit='B0D9E4AF0EFF6300611A304A0DC6A2D40036CB72252ACA38F32E1DE7FCF05A36'
 historicalPermitConsumption='6DEB344D029C4315865AE44495F0B8A73AF6E5A4BA55D9649154FDC1B2C5B570'
 stageGateContract='1A7A9AF14EEC47D1C51AD34A3DF3294C2846A8E6526954B4743A26355D79FCFF'
 stageGateEvaluator='7F977C6756842FCE934EC617F54905553F7EDA949E4083521A342E620CB1AAD4'
 stageGateFinalVerification='057FEBB59166C2EB87D731ABB699F061B352A697B9F98F2D767C7675191CB893'
 prelaunchV8Contract='1B235C8448467A5CBDD75F2247FA182A743CAA6151F96051A301567E4177E54E'
 prelaunchV8Verifier='3D32EA6095B4E4654606ABFE76019EA0E280AEC49E9ADEE71E9F95EE1393002D'
 prelaunchV8FinalVerification='3D08AACA7624B938F375381AD7878A106E0A225CA88C30F772B2288BACF714CA'
}
$loaded=@{}
function Bound($name){$entry=$policy.boundArtifacts.$name;if($null-eq$entry){Add-Error "missing artifact $name";return};Exact-Keys "artifact $name" $entry @('path','sha256');Eq "$name declared hash" ([string]$entry.sha256).ToUpperInvariant() $expectedHashes[$name];$path=Join-Path $repo ([string]$entry.path);if(-not(Test-Path -LiteralPath $path)){Add-Error "missing file $name";return};Eq "$name actual hash" (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash $expectedHashes[$name];if([IO.Path]::GetExtension($path)-eq'.json'){$loaded[$name]=Load $path}}
try{
 Exact-Keys 'root' $policy @('schemaVersion','contract','state','currentAuthority','historicalAuthority','priorPermit','transaction','ruling','stagePolicy','permitPolicy','boundArtifacts','operations','review','permitIssued')
 Exact-Keys 'currentAuthority' $policy.currentAuthority @('authorityId','source','scope','maxLiveRuns','liveRunsConsumed','liveRunsRemaining','reauthorizedAfterPriorConsumption','reauthorizationMessageId','reauthorizationTimestampUtc','activationBudget','noPerStepApproval','isPermit','doesNotBypassPrelaunchGates','broadApprovalInstrumentationExtension','broadApprovalOverridesActivationOrForbiddenCaps','allowedBreakpointSets')
 Exact-Keys 'historicalAuthority' $policy.historicalAuthority @('authorityId','launchPermitId','oracleRunId','liveRunsGranted','liveRunsConsumed','liveRunsRemaining')
 Exact-Keys 'priorPermit' $policy.priorPermit @('id','state','reusable','gameActivationsObserved','attemptConsumptionControlsReuse')
 Exact-Keys 'transaction' $policy.transaction @('provenance','physicalActivationCount','automaticInputBudget','retryBudget','sameRunRequired','stages')
 Exact-Keys 'ruling' $policy.ruling @('policyMismatchResolved','retiredBlocker','resolution','replacementFullTransactionBlocker','doesNotExpandAuthority')
 Exact-Keys 'stagePolicy' $policy.stagePolicy @('currentStage','authorizedPrefixLength','allocation','allocationSum','currentStageBudgetCompatible','scopedTerminalState','fullTransactionAuthoritySufficient','fullTransactionLaunchEligible','additionalPhysicalActivationsRequired','futureStageAuthorityStatus','automaticPermitChaining','stagePermitReusable','stopAfterAuthorizedStage','prepositionedDestinationOrConfirmStateBound','successSequence','claimsAllowed','claimsForbidden')
 Exact-Keys 'allocation' $policy.stagePolicy.allocation @('WARP','DESTINATION','CONFIRM')
 Exact-Keys 'permitPolicy' $policy.permitPolicy @('newPermitRequired','currentPermitIssued','newPermitIdMustDifferFromPrior','freshOracleRunIdRequired','allScopedPrelaunchGatesAndIndependentReviewRequired')
 Exact-Keys 'boundArtifacts' $policy.boundArtifacts @($expectedHashes.Keys)
 Exact-Keys 'operations' $policy.operations @('liveOperations','guestOperations','debuggerAttach','breakpointsInstalled','processMemoryReads','processMemoryWrites','physicalInputs','captures','automaticInputs','retries','vmLifecycleChanges','serverProtocolDbChanges')
 Exact-Keys 'review' $policy.review @('status','reviewer','artifactPath','artifactSha256')
 foreach($name in $expectedHashes.Keys){Bound $name}

 Eq 'schema' $policy.schemaVersion 1;Eq 'contract' $policy.contract 'ORIGINAL_CLIENT_ACTIVATION_BUDGET_STAGE_POLICY';Eq 'state' $policy.state 'OFFLINE_POLICY_RESOLVED_STAGE_LOCAL_ONE_ACTIVATION_ONLY'
 $currentId='CURRENT_THREAD_ORACLE_ONE_RUN_ONE_ACTIVATION_V1';$oldAuthority='E-AUTH-001';$oldPermit='permit-live-v3-20260827-d89449bc2c3c4b70a9854833b2214012-once';$oldRun='oracle-run-v3-20260827-d89449bc2c3c4b70a9854833b2214012'
 Eq 'authority id' $policy.currentAuthority.authorityId $currentId;Eq 'authority source' $policy.currentAuthority.source 'USER_MESSAGES_CURRENT_THREAD_HASH_BOUND';Eq 'authority scope' $policy.currentAuthority.scope 'ONE_LIVE_ORACLE_ONE_PHYSICAL_ACTIVATION_READ_ONLY_CAPTURE';Eq 'authority runs' $policy.currentAuthority.maxLiveRuns 1;Eq 'current runs consumed' $policy.currentAuthority.liveRunsConsumed 0;Eq 'current runs remaining' $policy.currentAuthority.liveRunsRemaining 1;Eq 'reauthorized after consumption' $policy.currentAuthority.reauthorizedAfterPriorConsumption $true;Eq 'reauthorization message' $policy.currentAuthority.reauthorizationMessageId 'msg_01a04341-060c-7501-8694-90a25198f52e';Eq 'reauthorization time' ([DateTimeOffset]$policy.currentAuthority.reauthorizationTimestampUtc).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ') '2026-08-27T12:45:29.996Z';Eq 'authority budget' $policy.currentAuthority.activationBudget 1;Eq 'no per-step approval' $policy.currentAuthority.noPerStepApproval $true;Eq 'authority is not permit' $policy.currentAuthority.isPermit $false;Eq 'authority gates' $policy.currentAuthority.doesNotBypassPrelaunchGates $true;Eq 'instrumentation extension' $policy.currentAuthority.broadApprovalInstrumentationExtension $true;Eq 'broad cap override' $policy.currentAuthority.broadApprovalOverridesActivationOrForbiddenCaps $false;Seq 'breakpoint sets' $policy.currentAuthority.allowedBreakpointSets @('BP01-BP14','MVB01-MVB09')
 Eq 'historical authority id' $policy.historicalAuthority.authorityId $oldAuthority;Eq 'historical permit id' $policy.historicalAuthority.launchPermitId $oldPermit;Eq 'historical run' $policy.historicalAuthority.oracleRunId $oldRun;Eq 'historical runs granted' $policy.historicalAuthority.liveRunsGranted 1;Eq 'historical runs consumed' $policy.historicalAuthority.liveRunsConsumed 1;Eq 'historical runs remaining' $policy.historicalAuthority.liveRunsRemaining 0;if($policy.currentAuthority.authorityId-eq$policy.historicalAuthority.authorityId){Add-Error 'current authority collides with historical authority'}
 Eq 'prior permit id' $policy.priorPermit.id $oldPermit;Eq 'prior permit state' $policy.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'prior reusable' $policy.priorPermit.reusable $false;Eq 'prior game activations' $policy.priorPermit.gameActivationsObserved 0;Eq 'attempt controls reuse' $policy.priorPermit.attemptConsumptionControlsReuse $true

 Eq 'transaction provenance' $policy.transaction.provenance 'OFFLINE_TECHNICAL_REQUIREMENT_NOT_USER_AUTHORITY';Eq 'transaction activations' $policy.transaction.physicalActivationCount 3;Eq 'automatic input budget' $policy.transaction.automaticInputBudget 0;Eq 'retry budget' $policy.transaction.retryBudget 0;Eq 'same run' $policy.transaction.sameRunRequired $true;Eq 'stage count' @($policy.transaction.stages).Count 3
 $stageNames=@('WARP','DESTINATION','CONFIRM');$predecessors=@(@(),@('WARP=1'),@('WARP=1','DESTINATION=1'));$createdAfter=@($null,'WARP','DESTINATION')
 for($i=0;$i-lt[Math]::Min(3,@($policy.transaction.stages).Count);$i++){$stage=$policy.transaction.stages[$i];Exact-Keys "stage[$i]" $stage @('name','ordinal','physicalActivations','requiredPredecessors','createdAfterStage');Eq "stage[$i] name" $stage.name $stageNames[$i];Eq "stage[$i] ordinal" $stage.ordinal ($i+1);Eq "stage[$i] activations" $stage.physicalActivations 1;Seq "stage[$i] predecessors" $stage.requiredPredecessors $predecessors[$i];Eq "stage[$i] created after" $stage.createdAfterStage $createdAfter[$i]}
 Eq 'policy mismatch resolved' $policy.ruling.policyMismatchResolved $true;Eq 'retired blocker' $policy.ruling.retiredBlocker 'ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH';Eq 'resolution' $policy.ruling.resolution 'SCOPE_SPLIT_NO_AUTHORITY_EXPANSION';Eq 'replacement blocker' $policy.ruling.replacementFullTransactionBlocker 'FULL_MOVEMENT_TRANSACTION_AUTHORITY_INSUFFICIENT_TWO_ADDITIONAL_PHYSICAL_ACTIVATIONS_REQUIRED';Eq 'no authority expansion' $policy.ruling.doesNotExpandAuthority $true
 Eq 'current stage' $policy.stagePolicy.currentStage 'WARP';Eq 'prefix length' $policy.stagePolicy.authorizedPrefixLength 1;Eq 'WARP allocation' $policy.stagePolicy.allocation.WARP 1;Eq 'DESTINATION allocation' $policy.stagePolicy.allocation.DESTINATION 0;Eq 'CONFIRM allocation' $policy.stagePolicy.allocation.CONFIRM 0;Eq 'allocation sum' $policy.stagePolicy.allocationSum 1;Eq 'budget compatible' $policy.stagePolicy.currentStageBudgetCompatible $true;Eq 'terminal' $policy.stagePolicy.scopedTerminalState 'WARP_STAGE_ENTERED_THEN_STOP_AND_HANDOFF';Eq 'full authority' $policy.stagePolicy.fullTransactionAuthoritySufficient $false;Eq 'full launch' $policy.stagePolicy.fullTransactionLaunchEligible $false;Eq 'additional activations' $policy.stagePolicy.additionalPhysicalActivationsRequired 2;Eq 'future authority' $policy.stagePolicy.futureStageAuthorityStatus 'MISSING';Eq 'automatic chaining' $policy.stagePolicy.automaticPermitChaining $false;Eq 'stage permit reusable' $policy.stagePolicy.stagePermitReusable $false;Eq 'stop after stage' $policy.stagePolicy.stopAfterAuthorizedStage $true;Eq 'prepositioned state' $policy.stagePolicy.prepositionedDestinationOrConfirmStateBound $false
 Seq 'success sequence' $policy.stagePolicy.successSequence @('WARP_INPUT','DESTINATION_STAGE_CREATED','OWNED_HWND_CAPTURE','STOP_AND_HANDOFF');Seq 'claims allowed' $policy.stagePolicy.claimsAllowed @('WARP_INPUT_CONSUMED','DESTINATION_STAGE_CREATED','WARP_STAGE_OWNER_BOUND','OWNED_HWND_POST_WARP');Seq 'claims forbidden' $policy.stagePolicy.claimsForbidden @('DESTINATION_INPUT','CONFIRM_INPUT','MVB01_ACCEPTED_HIT','OUTBOUND_0X0B01','INBOUND_0X0B07','QUEUE_COMPLETION','FULL_MOVEMENT','AUTHORITY_PROVEN','PERSISTENCE_PROVEN','PLAYER_VISIBLE_MOVEMENT')
 Eq 'new permit required' $policy.permitPolicy.newPermitRequired $true;Eq 'current permit' $policy.permitPolicy.currentPermitIssued $false;Eq 'new id differs' $policy.permitPolicy.newPermitIdMustDifferFromPrior $true;Eq 'fresh run required' $policy.permitPolicy.freshOracleRunIdRequired $true;Eq 'scoped gates' $policy.permitPolicy.allScopedPrelaunchGatesAndIndependentReviewRequired $true

 if($loaded.ContainsKey('currentAuthorityRecord')){$a=$loaded.currentAuthorityRecord;Exact-Keys 'authority record root' $a @('schemaVersion','authorityId','sourceType','sourceChronology','rawGrantExcerpts','adjudication','allowed','forbidden','permitIssued','liveOperations');Exact-Keys 'authority record chronology binding' $a.sourceChronology @('path','sha256','postConsumptionReauthorizationMessageId','postConsumptionReauthorizationTimestampUtc');Eq 'record id' $a.authorityId $currentId;Eq 'record source type' $a.sourceType 'USER_MESSAGES_CURRENT_THREAD_HASH_BOUND';Eq 'record chronology path' $a.sourceChronology.path $policy.boundArtifacts.authorityMessageChronology.path;Eq 'record chronology hash' $a.sourceChronology.sha256 $expectedHashes.authorityMessageChronology;Eq 'record reauthorization message' $a.sourceChronology.postConsumptionReauthorizationMessageId $policy.currentAuthority.reauthorizationMessageId;Eq 'record reauthorization time' $a.sourceChronology.postConsumptionReauthorizationTimestampUtc $policy.currentAuthority.reauthorizationTimestampUtc;Eq 'record runs' $a.adjudication.maxLiveRuns 1;Eq 'record runs consumed' $a.adjudication.liveRunsConsumed 0;Eq 'record runs remaining' $a.adjudication.liveRunsRemaining 1;Eq 'record reauthorization order' $a.adjudication.reauthorizedAfterPriorConsumption $true;Eq 'record activations' $a.adjudication.maxPhysicalActivations 1;Eq 'record not permit' $a.adjudication.isPermit $false;Eq 'record broad override' $a.adjudication.broadLaterApprovalOverridesExplicitCaps $false;Eq 'record instrumentation extension' $a.adjudication.broadLaterApprovalExtendsReadOnlyInstrumentation $true;Eq 'record cap retention' $a.adjudication.broadLaterApprovalDoesNotOverrideExplicitActivationOrForbiddenCaps $true;Seq 'record breakpoint sets' $a.adjudication.allowedBreakpointSets @('BP01-BP14','MVB01-MVB09');if(@($a.forbidden)-notcontains'second physical activation'){Add-Error 'record second activation prohibition missing'};Eq 'record permit' $a.permitIssued $false;Eq 'record live' $a.liveOperations 0}
 if($loaded.ContainsKey('authorityMessageChronology')){
  $c=$loaded.authorityMessageChronology;Eq 'chronology record' $c.record 'CURRENT_THREAD_AUTHORITY_MESSAGE_CHRONOLOGY';Eq 'chronology thread' $c.sourceSession.threadId '01a03bde-ebcb-7ee2-8a71-a07b0fcee407';Eq 'chronology mutable source' $c.sourceSession.mutableAppendOnlySource $true;Eq 'chronology whole hash' $c.sourceSession.wholeFileHashRequired $false;Eq 'chronology binding method' $c.sourceSession.bindingMethod 'EXACT_RESPONSE_ITEM_MESSAGE_ID_AND_RAW_JSONL_LINE_SHA256';Eq 'chronology initial id' $c.initialGrant.messageId 'msg_01a040f6-6fda-78a2-a493-deba1fe79bc3';Eq 'chronology broad id' $c.postConsumptionBroadApproval.messageId 'msg_01a04341-060c-7501-8694-90a25198f52e';Eq 'chronology permit hash' $c.historicalPermitConsumption.sha256 $expectedHashes.historicalPermitConsumption;Eq 'chronology permit state' $c.historicalPermitConsumption.permitState 'CONSUMED_NO_RETRY'
  $initial=Find-ExactSessionMessage $c.sourceSession.path $c.initialGrant;$broad=Find-ExactSessionMessage $c.sourceSession.path $c.postConsumptionBroadApproval
  foreach($pair in @(@('initial',$initial,$c.initialGrant),@('broad',$broad,$c.postConsumptionBroadApproval))){if($null-eq$pair[1]){continue};$name=$pair[0];$found=$pair[1];$expected=$pair[2];Eq "$name line number" $found.lineNumber $expected.lineNumberOneBased;Eq "$name ordinal" ($found.lineNumber-1) $expected.sequenceOrdinalZeroBased;Eq "$name raw hash" $found.rawLineSha256 $expected.rawLineSha256;Eq "$name timestamp" $found.item.timestamp $expected.timestampUtc;Eq "$name turn" $found.item.payload.internal_chat_message_metadata_passthrough.turn_id $expected.turnId;Eq "$name create time" $found.item.payload.internal_chat_message_metadata_passthrough.create_time $expected.createTime;Eq "$name role" $found.item.payload.role 'user';Eq "$name text" $found.item.payload.content[0].text $expected.text}
  $initialTime=[DateTimeOffset]::Parse($c.initialGrant.timestampUtc);$consumedTime=[DateTimeOffset]::Parse($c.historicalPermitConsumption.observedAtUtc);$broadTime=[DateTimeOffset]::Parse($c.postConsumptionBroadApproval.timestampUtc);Eq 'initial before consumption actual' ($initialTime-lt$consumedTime) $true;Eq 'consumption before broad actual' ($consumedTime-lt$broadTime) $true;Eq 'initial ordinal before broad actual' ($c.initialGrant.sequenceOrdinalZeroBased-lt$c.postConsumptionBroadApproval.sequenceOrdinalZeroBased) $true;Eq 'ordering initial' $c.ordering.initialGrantBeforePermitConsumption $true;Eq 'ordering consumption' $c.ordering.permitConsumptionBeforeBroadApproval $true;Eq 'ordering ordinal' $c.ordering.initialGrantOrdinalBeforeBroadApproval $true;Eq 'ordering status' $c.ordering.status 'PASS';Eq 'historical consumed' $c.adjudication.historicalGrantLiveRunsConsumed 1;Eq 'historical remaining' $c.adjudication.historicalGrantLiveRunsRemaining 0;Eq 'fresh reauthorized' $c.adjudication.postConsumptionApprovalReauthorizesFreshLiveRun $true;Eq 'current granted' $c.adjudication.currentGrantLiveRunsGranted 1;Eq 'current consumed' $c.adjudication.currentGrantLiveRunsConsumed 0;Eq 'current remaining' $c.adjudication.currentGrantLiveRunsRemaining 1;Eq 'retained activation' $c.adjudication.retainedPhysicalActivationCap 1;Eq 'retained automatic budget' $c.adjudication.retainedAutomaticInputBudget 0;Eq 'retained retry budget' $c.adjudication.retainedRetryBudget 0;Eq 'retained forbidden' $c.adjudication.retainedForbiddenOperations $true;Eq 'chronology MVB extension' $c.adjudication.extendsCompatibleReadOnlyInstrumentationToMvb01Mvb09 $true;Eq 'chronology no permit' $c.adjudication.doesNotIssuePermit $true;foreach($property in $c.operations.PSObject.Properties){Eq "chronology operation $($property.Name)" $property.Value 0}
 }
 if($loaded.ContainsKey('historicalLaunchPermit')){$p=$loaded.historicalLaunchPermit;Eq 'historical launch id' $p.permitId $oldPermit;Eq 'historical launch run' $p.oracleRunId $oldRun;Eq 'historical launch state' $p.state 'ISSUED_NOT_CONSUMED'}
 if($loaded.ContainsKey('historicalPermitConsumption')){$c=$loaded.historicalPermitConsumption;Eq 'consumption permit' $c.permitId $oldPermit;Eq 'consumption run' $c.oracleRunId $oldRun;Eq 'consumption state' $c.permitState 'CONSUMED_NO_RETRY';Eq 'consumption retry' $c.retryAllowed $false;Eq 'consumption activations' $c.postFailureState.gameActivations 0}
 if($loaded.ContainsKey('stageGateContract')){$s=$loaded.stageGateContract;Eq 'stage gate contract' $s.contract 'ORIGINAL_CLIENT_FIRST_PLAY_THREE_STAGE_GATE';Eq 'stage gate technical maximum' $s.maximumPhysicalActivations 3;Seq 'stage gate names' @($s.stages|ForEach-Object{$_.name}) $stageNames;Eq 'stage gate source count' @($s.stages).Count 3;for($i=0;$i-lt[Math]::Min(3,@($s.stages).Count);$i++){Eq "stage gate source max[$i]" $s.stages[$i].maxConsumption 1;Seq "stage gate source predecessors[$i]" $s.stages[$i].requiredPredecessors $predecessors[$i]};Eq 'stage gate automatic' $s.automaticInputBudget 0;Eq 'stage gate retry' $s.retryBudget 0;Eq 'stage gate live' $s.liveOperations 0}
 if($loaded.ContainsKey('stageGateFinalVerification')){$f=$loaded.stageGateFinalVerification;Eq 'stage gate verification' $f.result 'PASS';Eq 'stage gate claim' $f.claim 'OFFLINE_FIRST_PLAY_THREE_STAGE_GATE_PASS';Eq 'stage gate permit' $f.permitIssued $false;Eq 'stage gate verification live' $f.liveOperations 0}
 if($loaded.ContainsKey('prelaunchV8Contract')){$v=$loaded.prelaunchV8Contract;Eq 'v8 authority budget' $v.currentAuthority.activationBudget 1;Eq 'v8 prior state' $v.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'v8 prior reuse' $v.priorPermit.reusable $false;Eq 'v8 mismatch' $v.firstMissingBoundary 'ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH';Eq 'v8 ready' $v.launchEligible $false;Eq 'v8 permit' $v.permitIssued $false}
 if($loaded.ContainsKey('prelaunchV8FinalVerification')){$v=$loaded.prelaunchV8FinalVerification;Eq 'v8 verification' $v.result 'PASS';Eq 'v8 runtime receipt' $v.runtimeReceiptStatus 'MISSING';Eq 'v8 verification permit' $v.permitIssued $false}
 foreach($property in $policy.operations.PSObject.Properties){Eq "operation $($property.Name)" $property.Value 0};Eq 'review' $policy.review.status 'NOT_REVIEWED';Eq 'permit issued' $policy.permitIssued $false
}catch{Add-Error "verification exception: $($_.Exception.Message)"}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors);liveOperations=0;permitIssued=$false}|ConvertTo-Json -Depth 20;return}
[ordered]@{result='PASS';state=$policy.state;retiredMismatch=1;currentAuthorityBudget=[int]$policy.currentAuthority.activationBudget;currentLiveRunsRemaining=[int]$policy.currentAuthority.liveRunsRemaining;transactionPhysicalActivations=[int]$policy.transaction.physicalActivationCount;currentStage=$policy.stagePolicy.currentStage;currentStageBudgetCompatible=$policy.stagePolicy.currentStageBudgetCompatible;fullTransactionAuthoritySufficient=$policy.stagePolicy.fullTransactionAuthoritySufficient;additionalPhysicalActivationsRequired=[int]$policy.stagePolicy.additionalPhysicalActivationsRequired;automaticPermitChaining=$policy.stagePolicy.automaticPermitChaining;stagePermitReusable=$policy.stagePolicy.stagePermitReusable;stopAfterAuthorizedStage=$policy.stagePolicy.stopAfterAuthorizedStage;liveOperations=0;permitIssued=$false}|ConvertTo-Json -Depth 10
