[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ContractPath)
$ErrorActionPreference='Stop'
$unit=Split-Path -Parent $PSScriptRoot
$repo=(Resolve-Path (Join-Path $unit '..\..')).Path
$contract=Get-Content -LiteralPath $ContractPath -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Add-Error($message){$errors.Add([string]$message)}
function Eq($name,$actual,$expected){if($actual-ne$expected){Add-Error "$name expected=$expected actual=$actual"}}
function Seq($name,$actual,$expected){$a=if($null-eq$actual){@()}else{@($actual)};$e=if($null-eq$expected){@()}else{@($expected)};if(($a|ConvertTo-Json -Compress -Depth 30)-ne($e|ConvertTo-Json -Compress -Depth 30)){Add-Error "$name sequence mismatch"}}
function Exact-Keys($name,$object,$expected){Seq "$name keys" @($object.PSObject.Properties.Name|Sort-Object) @($expected|Sort-Object)}
function Load($path){Get-Content -LiteralPath $path -Raw -Encoding UTF8|ConvertFrom-Json}
$hashes=[ordered]@{
 activationPolicy='23203A865F85C27E6D7E282A01455183F9C2D67651A770F6AAEBB133431D53D2'
 activationPolicyVerifier='FCDE7E4104D6260239B92E24AA74BF9036EC4A5FF159E7536AE43A1A44E20298'
 activationPolicyTests='274CC307B6D44FF38B9139923C1DDF36F89883EEB0B66AD31AD5FAAC39E36D4C'
 stageMvbTimingAdjudication='15D5B1D077E475AE460ECFC523E3AE1C4E81BE65840E86BEDC5427E6B91C2270'
 warpStageOwnerLedger='AE058E57927DEF598DA598537D0D4DF469733FC6A1CBDAB8DD28C73D6A809B51'
 destinationConfirmLedger='59C1988F7743CCE774345D25E8BF50AD3728BC2A01D0944890E937C45DD844D3'
 movementBreakpointLedger='9BC141E9C2F9AA7A0EF6BADF9B63CED2822F3E5D7AF820382F38803523ED3B99'
 hardwareRearmPlan='54192253616B5CE26F81A87276BD861B15069677E8F3EEDD6C3FA903D8DE665D'
 prelaunchV8Contract='1B235C8448467A5CBDD75F2247FA182A743CAA6151F96051A301567E4177E54E'
 prelaunchV8Verifier='3D32EA6095B4E4654606ABFE76019EA0E280AEC49E9ADEE71E9F95EE1393002D'
 prelaunchV8Tests='18BB21C7CA86D6D946E7F1BFBDF318D667779515277E95733A5D2F5DE56E312D'
 prelaunchV8FinalVerification='3D08AACA7624B938F375381AD7878A106E0A225CA88C30F772B2288BACF714CA'
 prelaunchV8ArtifactLedger='093108A8F8E50716A132AC1DE740E53DAC03AB26FEECBC2FE78059D8908D234E'
 stageGateContract='1A7A9AF14EEC47D1C51AD34A3DF3294C2846A8E6526954B4743A26355D79FCFF'
 stageGateEvaluator='7F977C6756842FCE934EC617F54905553F7EDA949E4083521A342E620CB1AAD4'
 stageGateTests='6BB385EC66F77922D7376DD59E333C13AB5301EDBFB634B46611A88FF8242064'
 stageGateFinalVerification='057FEBB59166C2EB87D731ABB699F061B352A697B9F98F2D767C7675191CB893'
}
$loaded=@{}
function Bound($name){$entry=$contract.boundArtifacts.$name;if($null-eq$entry){Add-Error "missing artifact $name";return};Exact-Keys "artifact $name" $entry @('path','sha256');Eq "$name declared" ([string]$entry.sha256).ToUpperInvariant() $hashes[$name];$path=Join-Path $repo ([string]$entry.path);if(-not(Test-Path -LiteralPath $path)){Add-Error "missing file $name";return};Eq "$name actual" (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash $hashes[$name];if([IO.Path]::GetExtension($path)-eq'.json'){$loaded[$name]=Load $path}}
$scoped=@('FRESH_RUN_IDENTITY_MISSING','FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING','MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_MANAGER65_SNAPSHOT_MISSING','MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_MOVEMENT_BREAKPOINT_INSTALLATION_AND_INITIAL_DR_SNAPSHOT_MISSING','FOREGROUND_PROBE_NOT_RUN','INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING')
$post=@('WARP_INPUT_CONSUMED_EXACTLY_ONCE','FRESH_WARP_STAGE_OWNER_AND_SELECTGRID_SNAPSHOT_MISSING','FRESH_DESTINATION_PROJECTION_SNAPSHOT_AND_HIT_REGION_MISSING','OWNED_HWND_POST_WARP_CAPTURE_MISSING','MVB01_ACCEPTED_HIT_COUNT_MUST_REMAIN_ZERO','INITIAL_DR_ACTIVE_SET_MUST_REMAIN_UNCHANGED','STOP_AND_HANDOFF_NO_FURTHER_INPUT')
$authorityBoundary='FULL_MOVEMENT_TRANSACTION_AUTHORITY_INSUFFICIENT_TWO_ADDITIONAL_PHYSICAL_ACTIVATIONS_REQUIRED'
$deferred=@($authorityBoundary,'FRESH_TEXTDIALOG_SNAPSHOT_AND_CONFIRM_HIT_REGION_MISSING','MOVEMENT_RECEIPT_MVB01_MVB09_COMPLETION_MISSING','OUTBOUND_INBOUND_QUEUE_COMPLETION_AND_MOVEMENT_PIXELS_MISSING')
$routing=@'
[
 {"source":"ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH","lane":"RESOLVED_POLICY_AND_DEFERRED_AUTHORITY","targets":["FULL_MOVEMENT_TRANSACTION_AUTHORITY_INSUFFICIENT_TWO_ADDITIONAL_PHYSICAL_ACTIVATIONS_REQUIRED"]},
 {"source":"FRESH_RUN_IDENTITY_MISSING","lane":"SCOPED_PRELAUNCH","targets":["FRESH_RUN_IDENTITY_MISSING"]},
 {"source":"FRESH_MOVEMENT_BREAKPOINT_INSTALL_AND_PER_THREAD_TEMPORAL_RECEIPT_MISSING","lane":"SPLIT_PRELAUNCH_AND_DEFERRED","targets":["FRESH_MOVEMENT_BREAKPOINT_INSTALLATION_AND_INITIAL_DR_SNAPSHOT_MISSING","MOVEMENT_RECEIPT_MVB01_MVB09_COMPLETION_MISSING"]},
 {"source":"FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING","lane":"SCOPED_PRELAUNCH","targets":["FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING"]},
 {"source":"MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING","lane":"SCOPED_PRELAUNCH","targets":["MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING"]},
 {"source":"FRESH_MANAGER65_SNAPSHOT_MISSING","lane":"SCOPED_PRELAUNCH","targets":["FRESH_MANAGER65_SNAPSHOT_MISSING"]},
 {"source":"MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING","lane":"SCOPED_PRELAUNCH","targets":["MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING"]},
 {"source":"FRESH_WARP_STAGE_OWNER_SNAPSHOT_MISSING","lane":"POST_WARP","targets":["FRESH_WARP_STAGE_OWNER_AND_SELECTGRID_SNAPSHOT_MISSING"]},
 {"source":"FRESH_DESTINATION_PROJECTION_SNAPSHOT_MISSING","lane":"POST_WARP","targets":["FRESH_DESTINATION_PROJECTION_SNAPSHOT_AND_HIT_REGION_MISSING"]},
 {"source":"FRESH_TEXTDIALOG_SNAPSHOT_MISSING","lane":"DEFERRED_AFTER_DESTINATION","targets":["FRESH_TEXTDIALOG_SNAPSHOT_AND_CONFIRM_HIT_REGION_MISSING"]},
 {"source":"FOREGROUND_PROBE_NOT_RUN","lane":"SCOPED_PRELAUNCH","targets":["FOREGROUND_PROBE_NOT_RUN"]},
 {"source":"INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING","lane":"SCOPED_PRELAUNCH","targets":["INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING"]}
]
'@|ConvertFrom-Json
try{
 Exact-Keys 'root' $contract @('schemaVersion','contract','state','currentStage','oracleRunId','launchEligible','permitEligible','permitIssued','currentAuthority','priorPermit','resolvedPolicyBlockers','scopedPrelaunchBlockers','postActivationRequiredEvidence','deferredFullTransactionBoundaries','postActivationAssertions','v8BlockerRouting','firstMissingBoundary','firstTechnicalBoundary','firstAuthorityBoundary','boundArtifacts','operationCounters')
 Exact-Keys 'current authority' $contract.currentAuthority @('authorityId','liveOracleRunBudget','physicalActivationBudget','allowedStages','authorizedPrefixLength','scopedTerminalState','fullTransactionAuthorized','automaticInputBudget','retryBudget','permitChaining','doesNotBypassPrelaunchGates')
 Exact-Keys 'prior permit' $contract.priorPermit @('id','state','reusable')
 Exact-Keys 'post assertions' $contract.postActivationAssertions @('destinationStageCreatedExpected','expectedMvb01AcceptedHits','expectedReceiptPhaseOrdinal','expectedActiveAnchorShortIds','continueToDestinationInput','stopAndHandoff')
 Exact-Keys 'bound artifacts' $contract.boundArtifacts @($hashes.Keys)
 Exact-Keys 'operations' $contract.operationCounters @('liveOperations','guestOperations','debuggerAttach','debuggerCommands','processMemoryReads','processMemoryWrites','physicalInputs','captures','automaticInputs','retries','permitIssuance')
 foreach($name in $hashes.Keys){Bound $name}
 Eq 'schema' $contract.schemaVersion 9;Eq 'contract' $contract.contract 'ORIGINAL_CLIENT_FIRST_SERVER_BACKED_PLAY_PRELAUNCH_V9_STAGE_LOCAL_POLICY';Eq 'state' $contract.state 'OFFLINE_PRELAUNCH_V9_WARP_STAGE_ONLY_POLICY_RESOLVED_FRESH_RUNTIME_MISSING_READY_FALSE';Eq 'stage' $contract.currentStage 'WARP';Eq 'run id' $contract.oracleRunId $null;Eq 'launch' $contract.launchEligible $false;Eq 'permit eligible' $contract.permitEligible $false;Eq 'permit' $contract.permitIssued $false
 Eq 'authority id' $contract.currentAuthority.authorityId 'CURRENT_THREAD_ORACLE_ONE_RUN_ONE_ACTIVATION_V1';Eq 'run budget' $contract.currentAuthority.liveOracleRunBudget 1;Eq 'activation budget' $contract.currentAuthority.physicalActivationBudget 1;Seq 'allowed stages' $contract.currentAuthority.allowedStages @('WARP');Eq 'prefix' $contract.currentAuthority.authorizedPrefixLength 1;Eq 'terminal' $contract.currentAuthority.scopedTerminalState 'WARP_STAGE_ENTERED_THEN_STOP_AND_HANDOFF';Eq 'full transaction' $contract.currentAuthority.fullTransactionAuthorized $false;Eq 'automatic budget' $contract.currentAuthority.automaticInputBudget 0;Eq 'retry budget' $contract.currentAuthority.retryBudget 0;Eq 'permit chaining' $contract.currentAuthority.permitChaining $false;Eq 'gate bypass' $contract.currentAuthority.doesNotBypassPrelaunchGates $true
 Eq 'prior id' $contract.priorPermit.id 'permit-live-v3-20260827-d89449bc2c3c4b70a9854833b2214012-once';Eq 'prior state' $contract.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'prior reusable' $contract.priorPermit.reusable $false
 Seq 'resolved policy' $contract.resolvedPolicyBlockers @('ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH');Seq 'scoped blockers' $contract.scopedPrelaunchBlockers $scoped;Seq 'post evidence' $contract.postActivationRequiredEvidence $post;Seq 'deferred' $contract.deferredFullTransactionBoundaries $deferred
 Eq 'destination created' $contract.postActivationAssertions.destinationStageCreatedExpected $true;Eq 'MVB01 post-WARP' $contract.postActivationAssertions.expectedMvb01AcceptedHits 0;Eq 'receipt phase post-WARP' $contract.postActivationAssertions.expectedReceiptPhaseOrdinal 0;Seq 'active DR set post-WARP' $contract.postActivationAssertions.expectedActiveAnchorShortIds @('MVB01','MVB06','MVB08','MVB09');Eq 'no destination continuation' $contract.postActivationAssertions.continueToDestinationInput $false;Eq 'stop handoff' $contract.postActivationAssertions.stopAndHandoff $true
 Eq 'routing count' @($contract.v8BlockerRouting).Count 12;for($i=0;$i-lt[Math]::Min(12,@($contract.v8BlockerRouting).Count);$i++){Exact-Keys "routing[$i]" $contract.v8BlockerRouting[$i] @('source','lane','targets');Eq "routing[$i] source" $contract.v8BlockerRouting[$i].source $routing[$i].source;Eq "routing[$i] lane" $contract.v8BlockerRouting[$i].lane $routing[$i].lane;Seq "routing[$i] targets" $contract.v8BlockerRouting[$i].targets $routing[$i].targets}
 Eq 'first missing' $contract.firstMissingBoundary 'FRESH_RUN_IDENTITY_MISSING';Eq 'first technical' $contract.firstTechnicalBoundary 'FRESH_RUN_IDENTITY_MISSING';Eq 'first authority' $contract.firstAuthorityBoundary $authorityBoundary
 if($loaded.ContainsKey('activationPolicy')){$p=$loaded.activationPolicy;Eq 'policy result state' $p.state 'OFFLINE_POLICY_RESOLVED_STAGE_LOCAL_ONE_ACTIVATION_ONLY';Eq 'policy current stage' $p.stagePolicy.currentStage 'WARP';Eq 'policy budget' $p.currentAuthority.activationBudget 1;Eq 'policy runs consumed' $p.currentAuthority.liveRunsConsumed 0;Eq 'policy runs remaining' $p.currentAuthority.liveRunsRemaining 1;Eq 'policy post-consumption reauthorization' $p.currentAuthority.reauthorizedAfterPriorConsumption $true;Eq 'policy full authority' $p.stagePolicy.fullTransactionAuthoritySufficient $false;Eq 'policy additional' $p.stagePolicy.additionalPhysicalActivationsRequired 2;Eq 'policy permit' $p.permitIssued $false}
 if($loaded.ContainsKey('prelaunchV8Contract')){$v=$loaded.prelaunchV8Contract;Seq 'v8 routing source conservation' @($contract.v8BlockerRouting|ForEach-Object{$_.source}) @($v.blockers);Eq 'v8 ready' $v.launchEligible $false;Eq 'v8 permit' $v.permitIssued $false}
 if($loaded.ContainsKey('prelaunchV8FinalVerification')){$v=$loaded.prelaunchV8FinalVerification;Eq 'v8 final' $v.result 'PASS';Eq 'v8 policy blocker' $v.firstPolicyBoundary 'ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH';Eq 'v8 final permit' $v.permitIssued $false}
 if($loaded.ContainsKey('stageGateContract')){$s=$loaded.stageGateContract;$stagePredecessors=@(@(),@('WARP=1'),@('WARP=1','DESTINATION=1'));Eq 'stage count proof' $s.maximumPhysicalActivations 3;Eq 'stage source count' @($s.stages).Count 3;Seq 'stage order proof' @($s.stages|ForEach-Object{$_.name}) @('WARP','DESTINATION','CONFIRM');for($i=0;$i-lt[Math]::Min(3,@($s.stages).Count);$i++){Eq "stage source max[$i]" $s.stages[$i].maxConsumption 1;Seq "stage source predecessor[$i]" $s.stages[$i].requiredPredecessors $stagePredecessors[$i]};Eq 'stage auto' $s.automaticInputBudget 0;Eq 'stage retry' $s.retryBudget 0}
 if($loaded.ContainsKey('stageGateFinalVerification')){$s=$loaded.stageGateFinalVerification;Eq 'stage final' $s.result 'PASS';Eq 'stage claim' $s.claim 'OFFLINE_FIRST_PLAY_THREE_STAGE_GATE_PASS';Eq 'stage permit' $s.permitIssued $false}
 if($loaded.ContainsKey('stageMvbTimingAdjudication')){
  $t=$loaded.stageMvbTimingAdjudication;Eq 'timing record' $t.record 'WARP_DESTINATION_CONFIRM_STAGE_MVB_TIMING_ADJUDICATION';Eq 'timing provenance' $t.provenance 'ORIGINAL_OBSERVED_STATIC_AND_OFFLINE_CONTRACT';Eq 'timing status' $t.status 'STATIC_EXPECTED_NOT_RUNTIME_OBSERVED';Exact-Keys 'timing bound sources' $t.boundSources @('stageGateContract','warpStageOwnerLedger','destinationConfirmLedger','movementBreakpointLedger','hardwareRearmPlan');foreach($name in @('stageGateContract','warpStageOwnerLedger','destinationConfirmLedger','movementBreakpointLedger','hardwareRearmPlan')){Eq "timing source path $name" $t.boundSources.$name.path $contract.boundArtifacts.$name.path;Eq "timing source hash $name" $t.boundSources.$name.sha256 $hashes[$name]}
  Seq 'timing stages' $t.stageFacts.orderedStages @('WARP','DESTINATION','CONFIRM');Eq 'timing WARP max' $t.stageFacts.maxConsumptionByStage.WARP 1;Eq 'timing DESTINATION max' $t.stageFacts.maxConsumptionByStage.DESTINATION 1;Eq 'timing CONFIRM max' $t.stageFacts.maxConsumptionByStage.CONFIRM 1;Seq 'timing WARP predecessors' $t.stageFacts.requiredPredecessorsByStage.WARP @();Seq 'timing DESTINATION predecessors' $t.stageFacts.requiredPredecessorsByStage.DESTINATION @('WARP=1');Seq 'timing CONFIRM predecessors' $t.stageFacts.requiredPredecessorsByStage.CONFIRM @('WARP=1','DESTINATION=1');Eq 'timing max activations' $t.stageFacts.maximumPhysicalActivations 3;Eq 'timing factory' $t.stageFacts.warpFactory 'FUN_00581C80';Eq 'timing creates selectgrid' $t.stageFacts.warpCreatesFlowObject 'SelectGrid';Eq 'timing send child index' $t.stageFacts.sendWarpChildIndex 3;Eq 'timing send child vtable' $t.stageFacts.sendWarpChildVtable 'moduleBase+0x276AEC';Eq 'timing confirm object' $t.stageFacts.confirmFlowObject 'TextDialog';Eq 'timing MVB01 id' $t.mvbFacts.mvb01AnchorId 'MVB01_HANDLER_CALLBACK';Eq 'timing MVB01 role' $t.mvbFacts.mvb01Role 'WARP_SEND_CALLBACK_ENTRY';Eq 'timing child3 requirement' $t.mvbFacts.mvb01CaptureRequiresActiveFlowChild3Equality $true;Seq 'timing initial set' $t.mvbFacts.initialActiveAnchorShortIds @('MVB01','MVB06','MVB08','MVB09');Eq 'timing first transition' $t.mvbFacts.firstRearmTransitionRequiresAcceptedMvb01 $true;Eq 'timing post scope' $t.postWarpExpectation.scope 'AFTER_WARP_ACTIVATION_BEFORE_DESTINATION_ACTIVATION';Eq 'timing destination created' $t.postWarpExpectation.destinationStageCreated $true;Eq 'timing post hits' $t.postWarpExpectation.expectedMvb01AcceptedHits 0;Eq 'timing post phase' $t.postWarpExpectation.expectedReceiptPhaseOrdinal 0;Seq 'timing post set' $t.postWarpExpectation.expectedActiveAnchorShortIds @('MVB01','MVB06','MVB08','MVB09');Eq 'timing no destination input' $t.postWarpExpectation.continueToDestinationInput $false;Eq 'timing stop' $t.postWarpExpectation.stopAndHandoff $true;Eq 'timing evidence class' $t.postWarpExpectation.evidenceClass 'INFERRED_FROM_HASH_BOUND_STATIC_FLOW_AND_REARM_CONTRACT';Eq 'timing runtime' $t.postWarpExpectation.runtimeObserved $false;Seq 'timing allowed claims' $t.claimCeiling.allowed @('STATIC_STAGE_ORDER','STATIC_MVB01_SEND_BOUNDARY','EXPECTED_POST_WARP_ZERO_MVB01');Seq 'timing forbidden claims' $t.claimCeiling.forbidden @('RUNTIME_OBSERVED','MVB01_ACCEPTED_HIT','OUTBOUND_0X0B01','FULL_MOVEMENT','PLAYER_VISIBLE_MOVEMENT');foreach($property in $t.operations.PSObject.Properties){Eq "timing operation $($property.Name)" $property.Value 0}
 }
 if($loaded.ContainsKey('warpStageOwnerLedger')){$w=$loaded.warpStageOwnerLedger;Eq 'warp factory source' $w.facts.warpFactory 'FUN_00581C80';Eq 'warp child count' $w.facts.childVector.requiredCount 6;Eq 'warp SelectGrid child' $w.facts.orderedChildVtables[0] 'moduleBase+0x270228';Eq 'warp send child' $w.facts.orderedChildVtables[3] 'moduleBase+0x276AEC';Eq 'warp live snapshot' $w.status.liveSnapshot 'UNSEEN'}
 if($loaded.ContainsKey('destinationConfirmLedger')){$d=$loaded.destinationConfirmLedger;Eq 'destination factory source' $d.destination.flowFactory 'FUN_00581C80';Eq 'destination object source' $d.destination.flowObject 'SelectGrid';Eq 'confirm object source' $d.confirm.flowObject 'TextDialog';Eq 'destination runtime source' $d.status.runtimeObserved 'UNSEEN'}
 if($loaded.ContainsKey('movementBreakpointLedger')){$m=$loaded.movementBreakpointLedger;$a=@($m.anchors|Where-Object{$_.id-eq'MVB01_HANDLER_CALLBACK'});Eq 'MVB01 source count' $a.Count 1;if($a.Count-eq1){Eq 'MVB01 source role' $a[0].role 'WARP_SEND_CALLBACK_ENTRY';if(@($a[0].capture)-notcontains'fresh active-flow child[3] equality'){Add-Error 'MVB01 child[3] capture proof missing'}};Eq 'movement runtime source' $m.status.runtimeObserved 'UNSEEN'}
 if($loaded.ContainsKey('hardwareRearmPlan')){$h=$loaded.hardwareRearmPlan;Seq 'rearm initial source' $h.initial.active @('MVB01','MVB06','MVB08','MVB09');Eq 'rearm first transition hit' $h.transitions[0].hit 'MVB01';Seq 'rearm first before' $h.transitions[0].activeBefore @('MVB01','MVB06','MVB08','MVB09');Eq 'rearm runtime source' $h.debuggerSemantics.runtimeNoMissProof 'MISSING';Eq 'rearm live eligible' $h.dryRun.liveInstallEligible $false}
 foreach($property in $contract.operationCounters.PSObject.Properties){Eq "operation $($property.Name)" $property.Value 0}
}catch{Add-Error "verification exception: $($_.Exception.Message)"}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors);liveOperations=0;gameInputs=0;permitIssued=$false}|ConvertTo-Json -Depth 20;return}
[ordered]@{result='PASS';state=$contract.state;currentStage=$contract.currentStage;scopedBlockerCount=@($contract.scopedPrelaunchBlockers).Count;postActivationEvidenceCount=@($contract.postActivationRequiredEvidence).Count;deferredBoundaryCount=@($contract.deferredFullTransactionBoundaries).Count;firstMissingBoundary=$contract.firstMissingBoundary;firstAuthorityBoundary=$contract.firstAuthorityBoundary;expectedPostWarpMvb01AcceptedHits=$contract.postActivationAssertions.expectedMvb01AcceptedHits;stageMvbTimingStatus=$loaded.stageMvbTimingAdjudication.status;launchEligible=$false;permitEligible=$false;liveOperations=0;gameInputs=0;permitIssued=$false}|ConvertTo-Json -Depth 10
