;; LOGH7 owned background client copy only. Author: 최병호
;; https://github.com/elishacloud/dxwrapper/releases/tag/v1.8.8600.25
[General]
RealDllPath=AUTO
WrapperMode=AUTO
DisableLogging=0
[Compatibility]
D3d8to9=1
D3d9to9Ex=1
EnableD3d9Wrapper=1
[Direct3D9]
EnableWindowMode=1
FullscreenWindowMode=0
EnableCursorClip=0
