$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot;$collector=Join-Path $root 'src/collect-manager65-action2b-hardened.ps1';$resolver=Join-Path $root 'src/resolve-manager65-action2b-hardened.ps1';$fixture=Join-Path $PSScriptRoot 'fixture-memory.json';$identity=Join-Path $PSScriptRoot 'fixture-identity.json'
if(-not(Test-Path $collector)){throw 'RED: hardened collector missing'};if(-not(Test-Path $resolver)){throw 'RED: hardened resolver missing'}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('manager65-hardening-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null;$script:n=0;$script:cases=0
function Eq($name,$actual,$expected){$script:n++;if($actual-ne$expected){throw "$name expected=$expected actual=$actual"}}
function Variant($name,[scriptblock]$change){$f=Get-Content $fixture -Raw|ConvertFrom-Json;$f.second=$f.first|ConvertTo-Json -Depth 12|ConvertFrom-Json;&$change $f;$p=Join-Path $temp "$name.json";$f|ConvertTo-Json -Depth 15|Set-Content $p;$p}
function Run($memory,$name){$script:cases++;$p=Join-Path $temp "$name-capture.json";&$collector -FixtureMemoryPath $memory -FixtureIdentityPath $identity -OutputPath $p;Get-Content $p -Raw|ConvertFrom-Json}
function IdentityVariant($name,[scriptblock]$change){$i=Get-Content $identity -Raw|ConvertFrom-Json;&$change $i;$ip=Join-Path $temp "$name-identity.json";$i|ConvertTo-Json|Set-Content $ip;$script:cases++;$p=Join-Path $temp "$name-capture.json";&$collector -FixtureMemoryPath $fixture -FixtureIdentityPath $ip -OutputPath $p;Get-Content $p -Raw|ConvertFrom-Json}
function Resolve($capture,$name){$p=Join-Path $temp "$name-resolution.json";&$resolver -CapturePath $capture -OutputPath $p;Get-Content $p -Raw|ConvertFrom-Json}
try{
 $r=Run $fixture ready;Eq 'eligible' $r.stateEligible $true;Eq 'provenance' $r.provenance 'SYNTHETIC_FIXTURE';Eq 'module' $r.process.moduleBase '0x00400000';Eq 'root' $r.root.pointer '0x00C9E638';Eq 'strategy mode' $r.root.strategyMode 2;Eq 'controller' $r.manager65.controllerPointer '0x00C9E768';Eq 'manager' $r.manager65.managerPointer '0x07000000';Eq 'manager id' $r.manager65.managerId 101;Eq 'registry' $r.manager65.registrySlotMatches $true;Eq 'page' $r.manager65.page 2;Eq 'card' $r.manager65.cardId 7;Eq 'count' $r.manager65.actionCount 3;Eq 'record count match' $r.manager65.recordActionCountMatches $true;Eq 'pending reset' $r.manager65.selectedIndex -1;Eq 'warp count' @($r.manager65.actions|Where-Object{$_.commandId-eq43}).Count 1;$warp=@($r.manager65.actions|Where-Object{$_.commandId-eq43})[0];Eq 'warp pointer' $warp.widgetPointer '0x07100F18';Eq 'warp eligible' $warp.eligible $true;Eq 'warp left' $warp.logicalRect.left 700;Eq 'warp top' $warp.logicalRect.top 630;Eq 'warp right' $warp.logicalRect.right 820;Eq 'warp bottom' $warp.logicalRect.bottom 654;Eq 'scale x' $r.coordinateFrame.scaleX 1.25;Eq 'logical width' $r.coordinateFrame.logicalWidth 1000;Eq 'snapshot stable' $r.snapshotStable $true;Eq 'surface stable' $r.windowSurfaceStable $true;Eq 'read count' $r.operations.memoryReadCount 142;Eq 'writes' $r.operations.writes 0;Eq 'inputs' $r.operations.gameInputs 0;Eq 'runtime unseen' $r.originalRuntimeObserved $false
 $capture=Join-Path $temp ready-capture.json;$resolved=Resolve $capture ready;Eq 'offline resolved' $resolved.status 'OFFLINE_RESOLVED';Eq 'region count' @($resolved.action0x2B.regions).Count 1;Eq 'client left' $resolved.action0x2B.regions[0].clientRect.left 560;Eq 'client top' $resolved.action0x2B.regions[0].clientRect.top 420;Eq 'client right' $resolved.action0x2B.regions[0].clientRect.right 656;Eq 'client bottom' $resolved.action0x2B.regions[0].clientRect.bottom 436;Eq 'safe x' $resolved.action0x2B.regions[0].safePoint.x 607;Eq 'safe y' $resolved.action0x2B.regions[0].safePoint.y 427;Eq 'no automatic point' $resolved.automaticActivationPoint $null
 $p=Variant duplicate {param($f)foreach($s in @($f.first,$f.second)){$s.u16.'0x083418E6'=43}};$r=Run $p duplicate;Eq 'duplicate warp blocked' (@($r.blockers)-contains'ACTION_0X2B_NOT_UNIQUE') $true
 $p=Variant nowarp {param($f)foreach($s in @($f.first,$f.second)){$s.u16.'0x083418E4'=16}};$r=Run $p nowarp;Eq 'missing warp blocked' (@($r.blockers)-contains'ACTION_0X2B_NOT_FOUND') $true
 $p=Variant torn {param($f)$f.second.u16.'0x083418E4'=44};$r=Run $p torn;Eq 'torn blocked' (@($r.blockers)-contains'TORN_SNAPSHOT') $true
 $r=IdentityVariant hash {param($i)$i.sha256='0'*64};Eq 'identity hash blocked' (@($r.blockers)-contains'EXECUTABLE_HASH_MISMATCH') $true
 $r=IdentityVariant module {param($i)$i.moduleBase='0x00500000'};Eq 'module blocked' (@($r.blockers)-contains'MODULE_BASE_NOT_0X00400000') $true
 $r=IdentityVariant owner {param($i)$i.hwndOwnerPid=4243};Eq 'owner blocked' (@($r.blockers)-contains'OWNED_HWND_PID_MISMATCH') $true
 $r=IdentityVariant owner2 {param($i)$i.secondHwndOwnerPid=4243};Eq 'second owner blocked' (@($r.blockers)-contains'OWNED_HWND_PID_MISMATCH') $true
 $r=IdentityVariant surface {param($i)$i.secondClientWidth=799};Eq 'surface tear blocked' (@($r.blockers)-contains'OWNED_HWND_SURFACE_TORN') $true
 $r=IdentityVariant dimensions {param($i)$i.clientWidth=0};Eq 'dimensions blocked' (@($r.blockers)-contains'NONPOSITIVE_CLIENT_SURFACE') $true
 $p=Variant registry {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x06000198'=117440768}};$r=Run $p registry;Eq 'registry blocked' (@($r.blockers)-contains'MANAGER65_REGISTRY_SLOT_MISMATCH') $true
 $p=Variant registryhostnull {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x02215E2C'=0}};$r=Run $p registryhostnull;Eq 'registry host null blocked' (@($r.blockers)-contains'MANAGER65_REGISTRY_HOST_NULL') $true
 $p=Variant registrynull {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x0100000C'=0}};$r=Run $p registrynull;Eq 'registry null blocked' (@($r.blockers)-contains'MANAGER65_REGISTRY_NULL') $true
 $p=Variant managerid {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x07000000'=102}};$r=Run $p managerid;Eq 'manager id blocked' (@($r.blockers)-contains'MANAGER65_ID_MISMATCH') $true
 $p=Variant manageractive {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07000004'=0}};$r=Run $p manageractive;Eq 'manager active blocked' (@($r.blockers)-contains'MANAGER65_CONTEXT_INACTIVE') $true
 $p=Variant managerinput {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07000005'=0}};$r=Run $p managerinput;Eq 'manager input blocked' (@($r.blockers)-contains'MANAGER65_CONTEXT_INACTIVE') $true
 $p=Variant page {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9EAB4'=6}};$r=Run $p page;Eq 'page blocked' (@($r.blockers)-contains'MANAGER65_PAGE_OUT_OF_RANGE_1_TO_5') $true
 $p=Variant count {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9EAB8'=25}};$r=Run $p count;Eq 'count blocked' (@($r.blockers)-contains'MANAGER65_ACTION_COUNT_OUT_OF_RANGE') $true
 $p=Variant recordcount {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x083418E0'=2}};$r=Run $p recordcount;Eq 'record count blocked' (@($r.blockers)-contains'MANAGER65_RECORD_ACTION_COUNT_MISMATCH') $true
 $p=Variant selected {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9EABC'=1}};$r=Run $p selected;Eq 'pending selection blocked' (@($r.blockers)-contains'MANAGER65_SELECTED_INDEX_NOT_RESET') $true
 $p=Variant card {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9EAC0'=-1}};$r=Run $p card;Eq 'card blocked' (@($r.blockers)-contains'MANAGER65_BOUND_CARD_ID_INVALID') $true
 $p=Variant ownernull {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x007CCFFC'=0}};$r=Run $p ownernull;Eq 'current owner null blocked' (@($r.blockers)-contains'CURRENT_CHARACTER_OWNER_NULL') $true
 $p=Variant initialized {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07100F20'=0}};$r=Run $p initialized;Eq 'initialized blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant localgate {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07100F22'=1;$s.u8.'0x07100F2C'=0}};$r=Run $p localgate;Eq 'local gate blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant localtransform {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07100F22'=1;$s.u8.'0x07100F2C'=1;$s.i32.'0x07100F24'=10;$s.i32.'0x07100F28'=5}};$r=Run $p localtransform;$warp=@($r.manager65.actions|Where-Object{$_.commandId-eq43})[0];Eq 'local transform eligible' $r.stateEligible $true;Eq 'local transform x' $warp.logicalRect.left 710;Eq 'local transform y' $warp.logicalRect.top 635
 $p=Variant hit {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07100F2D'=0}};$r=Run $p hit;Eq 'hit gate blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant active {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07100F30'=0}};$r=Run $p active;Eq 'active gate blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant render {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x07100F33'=0}};$r=Run $p render;Eq 'render gate blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant width {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x07100F44'=0}};$r=Run $p width;Eq 'width blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant height {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x07100F48'=-1}};$r=Run $p height;Eq 'height blocked' (@($r.blockers)-contains'ACTION_0X2B_WIDGET_NOT_ELIGIBLE') $true
 $p=Variant bounds {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x0700000C'=1200}};$r=Run $p bounds;Eq 'logical bounds blocked' (@($r.blockers)-contains'ACTION_0X2B_RECT_OUTSIDE_LOGICAL_SURFACE') $true
 $p=Variant strategy {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9E72C'=1}};$r=Run $p strategy;Eq 'strategy mode blocked' (@($r.blockers)-contains'STRATEGY_ROOT_STATE_MISMATCH') $true
 $p=Variant handler {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9E63C'=0}};$r=Run $p handler;Eq 'handler state blocked' (@($r.blockers)-contains'STRATEGY_ROOT_STATE_MISMATCH') $true
 $p=Variant engine {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x0402A604'=801}};$r=Run $p engine;Eq 'engine rect blocked' (@($r.blockers)-contains'ENGINE_RECT_HWND_MISMATCH') $true
 $p=Variant scale {param($f)foreach($s in @($f.first,$f.second)){$s.f32.'0x00772E2C'=1.0}};$r=Run $p scale;Eq 'scale mismatch blocked' (@($r.blockers)-contains'SCALE_LOGICAL_SURFACE_MISMATCH') $true
 $p=Variant zeroscale {param($f)foreach($s in @($f.first,$f.second)){$s.f32.'0x00772E2C'=0}};$r=Run $p zeroscale;Eq 'invalid scale blocked' (@($r.blockers)-contains'INVALID_SCALE') $true
 $p=Variant nanscale {param($f)foreach($s in @($f.first,$f.second)){$s.f32.'0x00772E2C'='NaN'}};$r=Run $p nanscale;Eq 'NaN scale blocked' (@($r.blockers)-contains'INVALID_SCALE') $true
 $p=Variant parent {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x07000008'=2;$s.u32|Add-Member -NotePropertyName '0x0500000C' -NotePropertyValue 117444608;$s.u32|Add-Member -NotePropertyName '0x07001000' -NotePropertyValue 2;$s.u8|Add-Member -NotePropertyName '0x07001004' -NotePropertyValue 1;$s.i32|Add-Member -NotePropertyName '0x07001008' -NotePropertyValue -1;$s.i32|Add-Member -NotePropertyName '0x0700100C' -NotePropertyValue 10;$s.i32|Add-Member -NotePropertyName '0x07001010' -NotePropertyValue 20;$s.u32|Add-Member -NotePropertyName '0x07001030' -NotePropertyValue 83886080}};$r=Run $p parent;$warp=@($r.manager65.actions|Where-Object{$_.commandId-eq43})[0];Eq 'parent origin x' $warp.logicalRect.left 710;Eq 'parent origin y' $warp.logicalRect.top 650;Eq 'parent read count' $r.operations.memoryReadCount 156
 $p=Variant cycle {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x07000008'=101}};$threw=$false;try{$null=Run $p cycle}catch{$threw=$_.Exception.Message-like'*INVALID_PARENT_CHAIN*'};Eq 'context cycle rejected' $threw $true
 $rejected=$false;$script:cases++;try{&$collector -TargetProcessId 2147483647 -ExpectedStartTimeUtc '2000-01-01Z' -ExpectedExecutableSha256 ('0'*64) -ExpectedWindowHandle 0x1 -OutputPath (Join-Path $temp invalid.json)}catch{$rejected=$_.Exception.Message-like'*canonical*'};Eq 'noncanonical rejected before process lookup' $rejected $true
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.provenance='LIVE_READONLY';$p=Join-Path $temp live.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$script:cases++;$v=Resolve $p live;Eq 'live self claim unbound' $v.status 'UNBOUND';Eq 'live no region' @($v.action0x2B.regions).Count 0;Eq 'live no automatic point' $v.automaticActivationPoint $null
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.provenance='UNKNOWN_PROVENANCE';$p=Join-Path $temp unknown.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$script:cases++;$v=Resolve $p unknown;Eq 'unknown provenance unbound' $v.status 'UNBOUND';Eq 'unknown provenance reason' $v.reason 'UNSUPPORTED_CAPTURE_PROVENANCE';Eq 'unknown provenance no region' @($v.action0x2B.regions).Count 0
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.PSObject.Properties.Remove('provenance');$p=Join-Path $temp missingprovenance.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$script:cases++;$v=Resolve $p missingprovenance;Eq 'missing provenance unbound' $v.status 'UNBOUND';Eq 'missing provenance reason' $v.reason 'UNSUPPORTED_CAPTURE_PROVENANCE';Eq 'missing provenance no region' @($v.action0x2B.regions).Count 0
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.stateEligible=$false;$j.blockers=@('TEST');$p=Join-Path $temp ineligible.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$script:cases++;$v=Resolve $p ineligible;Eq 'ineligible unbound' $v.status 'UNBOUND'
 [ordered]@{result='PASS';cases=$script:cases;assertions=$script:n}|ConvertTo-Json
}finally{if(Test-Path $temp){$resolvedPath=(Resolve-Path $temp).Path;$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if(-not$resolvedPath.StartsWith($base,[StringComparison]::OrdinalIgnoreCase)){throw 'unsafe cleanup'};Remove-Item $resolvedPath -Recurse -Force}}
