[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ContractPath)
$ErrorActionPreference='Stop';$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$contract=Get-Content $ContractPath -Raw -Encoding UTF8|ConvertFrom-Json;$errors=[Collections.Generic.List[string]]::new()
function Eq($name,$actual,$expected){if($actual-ne$expected){$errors.Add("$name expected=$expected actual=$actual")}}
function Seq($name,$actual,$expected){if((@($actual)|ConvertTo-Json -Compress)-ne(@($expected)|ConvertTo-Json -Compress)){$errors.Add("$name sequence mismatch")}}
function Load($path){Get-Content $path -Raw -Encoding UTF8|ConvertFrom-Json}
$hashes=[ordered]@{warpOwnerStaticLedger='AE058E57927DEF598DA598537D0D4DF469733FC6A1CBDAB8DD28C73D6A809B51';priorV4Contract='97C5A06A9BE678F4AEF7B0121806CDF1EDEE50D0C8947B06BE3F8E27CB996614';priorV4Verification='085093C899E1B1DCA60BF4187E71D1C3A4992F6D8C6060D061F9CC89C74BF321';priorV4ArtifactLedger='DD92B2E869A0DE55B8D4795B308B513F5205F2F3A2A88B207F03574A4FD99294'};$loaded=@{}
foreach($name in $hashes.Keys){$e=$contract.boundArtifacts.$name;if($null-eq$e){$errors.Add("missing artifact $name");continue};Eq "$name declared" ([string]$e.sha256).ToUpperInvariant() $hashes[$name];$p=Join-Path $repo ([string]$e.path);if(-not(Test-Path $p)){$errors.Add("missing file $name");continue};Eq "$name actual" (Get-FileHash $p -Algorithm SHA256).Hash $hashes[$name];$loaded[$name]=Load $p}
Eq 'schema' $contract.schemaVersion 5;Eq 'contract' $contract.contract 'ORIGINAL_CLIENT_FIRST_SERVER_BACKED_PLAY_PRELAUNCH_V5_WARP_OWNER_INTEGRATED';Eq 'state' $contract.state 'OFFLINE_PRELAUNCH_WARP_OWNER_INTEGRATED_READY_FALSE';Eq 'run id' $contract.oracleRunId $null;Eq 'launch' $contract.launchEligible $false;Eq 'permit eligible' $contract.permitEligible $false;Eq 'permit' $contract.permitIssued $false;Eq 'authority source' $contract.currentAuthority.source 'USER_APPROVED_CURRENT_THREAD';Eq 'authority scope' $contract.currentAuthority.scope 'ONE_LIVE_ORACLE_ONE_PHYSICAL_ACTIVATION_READ_ONLY_CAPTURE';Eq 'budget' $contract.currentAuthority.activationBudget 1;Eq 'gate bypass' $contract.currentAuthority.doesNotBypassPrelaunchGates $true;Eq 'prior permit id' $contract.priorPermit.id 'permit-live-v3-20260827-d89449bc2c3c4b70a9854833b2214012-once';Eq 'prior permit state' $contract.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'prior permit reusable' $contract.priorPermit.reusable $false
$resolved=@('WARP_STAGE_OWNER_POINTER_UNBOUND');$introduced=@('FRESH_WARP_STAGE_OWNER_SNAPSHOT_MISSING');Seq 'resolved' $contract.integrationDelta.resolvedStaticBlockers $resolved;Seq 'introduced' $contract.integrationDelta.introducedRuntimeBlockers $introduced;Eq 'prior count' $contract.integrationDelta.priorBlockerCount 12;Eq 'current count' $contract.integrationDelta.currentBlockerCount 12
$expected=@('ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH','MOVEMENT_SPECIFIC_BREAKPOINT_RECEIPT_SCHEMA_MISSING','FRESH_RUN_IDENTITY_MISSING','FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING','MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_MANAGER65_SNAPSHOT_MISSING','MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_WARP_STAGE_OWNER_SNAPSHOT_MISSING','FRESH_DESTINATION_PROJECTION_SNAPSHOT_MISSING','FRESH_TEXTDIALOG_SNAPSHOT_MISSING','FOREGROUND_PROBE_NOT_RUN','INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING');Seq 'blockers' $contract.blockers $expected;Eq 'first missing' $contract.firstMissingBoundary $expected[0];Eq 'first technical' $contract.firstTechnicalBoundary $expected[1]
$w=$contract.staticPreparation.warpStageOwner;Eq 'owner status' $w.status 'STATIC_WARP_STAGE_MANAGER_OWNER_PASS_LIVE_SNAPSHOT_MISSING';Eq 'owner runtime' $w.runtimeObserved 'UNSEEN';Eq 'active pointer' $w.activeFlowPointerField 'moduleBase+0x89E2F8';Eq 'command' $w.ownerCommand 'activeFlow+0x28=0x2B';Eq 'card' $w.ownerCardBinding 'activeFlow+0x20==strategyRoot+0x488';Eq 'child' $w.textDialogChild 'child[2] vtable=moduleBase+0x275780';Eq 'manager' $w.textDialogManager 'moduleBase+0x8A292C';Eq 'cache' $w.managerCacheEquality 'U32(textDialog+0x58)==moduleBase+0x8A292C';Eq 'fixture reuse' $w.fixtureCoordinateReusable $false;Eq 'independent live' $w.independentLiveBinding 'UNBOUND'
$composition=@('fresh G7MTClient PID/startTime/hash/moduleBase/HWND/owner/client surface','fresh listener and heartbeat','fresh x32dbg PID/startTime/HWND/owner and exact foreground','fresh manager65-bound manager67 authority-card/action-0x2B/page-selected widget/gates/rect snapshot','independently bound manager67 authority-card hit region','fresh hardened manager65 action-0x2B snapshot','independently bound manager65 action-0x2B hit region','fresh WARP stage-owner snapshot binding active flow child[2] to the scoped TextDialog manager','fresh destination projection snapshot and independently resolved hit region','fresh TextDialog snapshot and independently resolved confirm region','movement-specific breakpoint/receipt schema installed without writes','one physical activation sequence followed by outbound/inbound/pixel receipts');Seq 'composition' $contract.requiredSameRunComposition $composition
$counterNames=@('guestOperations','debuggerAttach','breakpointsInstalled','processMemoryReads','physicalInputs','captures','memoryWrites');Seq 'counters' @($contract.operationCounters.PSObject.Properties.Name) $counterNames;foreach($n in $counterNames){Eq "counter $n" $contract.operationCounters.$n 0}
$forbidden=@('reuse prior permit/run/PID/HWND/pointer/coordinate','automatic click or retry','input before all same-run gates and independent review pass','process-memory write or binary/resource patch','VM lifecycle or server/protocol/database change','fixture or self-claimed live evidence promotion');Seq 'forbidden' $contract.forbidden $forbidden
if($loaded.ContainsKey('priorV4Contract')){$v4=$loaded.priorV4Contract;Eq 'v4 state' $v4.state 'OFFLINE_PRELAUNCH_MANAGER65_INTEGRATED_READY_FALSE';Eq 'v4 blockers' @($v4.blockers).Count 12;$derived=@($v4.blockers|Where-Object{$_-ne'WARP_STAGE_OWNER_POINTER_UNBOUND'});$at=[Array]::IndexOf($derived,'FRESH_DESTINATION_PROJECTION_SNAPSHOT_MISSING');if($at-lt0){$errors.Add('v4 insertion point missing')}else{$derived=@($derived[0..($at-1)])+$introduced+@($derived[$at..($derived.Count-1)])};Seq 'v4 delta' $contract.blockers $derived}
if($loaded.ContainsKey('priorV4Verification')){$v=$loaded.priorV4Verification;Eq 'v4 receipt' $v.result 'PASS';Eq 'v4 cases' $v.tests.cases 19;Eq 'v4 assertions' $v.tests.assertions 32;Eq 'v4 ledger' $v.artifactLedgerSha256 $hashes.priorV4ArtifactLedger;Eq 'v4 inputs' $v.gameInputs 0;Eq 'v4 permit' $v.permitIssued $false}
if($loaded.ContainsKey('priorV4ArtifactLedger')){$l=$loaded.priorV4ArtifactLedger;Eq 'v4 artifact count' @($l.artifacts).Count 5;foreach($a in $l.artifacts){$p=Join-Path $repo ('work/20260828-original-client-first-play-prelaunch-manager65-integration-v4/'+[string]$a.path);if(-not(Test-Path $p)){$errors.Add("v4 artifact missing $($a.path)");continue};Eq "v4 artifact $($a.path)" (Get-FileHash $p -Algorithm SHA256).Hash $a.sha256}}
if($loaded.ContainsKey('warpOwnerStaticLedger')){$l=$loaded.warpOwnerStaticLedger;Eq 'target hash' $l.target.sha256 'BD19263C10DECC3D58373165A82D42A9267868400D407DA87D5F4F4109AB6E16';Eq 'static status' $l.status.staticWarpStageManagerOwner 'PASS';Eq 'live snapshot' $l.status.liveSnapshot 'UNSEEN';Eq 'independent binding' $l.status.independentLiveBinding 'UNBOUND';Eq 'static manager' $l.facts.textDialogManager 'moduleBase+0x8A292C';Eq 'child index' $l.facts.textDialogChildIndex 2;foreach($prop in $l.sources.PSObject.Properties){$p=Join-Path $repo ([string]$prop.Value.path);if(-not(Test-Path $p)){$errors.Add("source missing $($prop.Name)");continue};Eq "source $($prop.Name)" (Get-FileHash $p -Algorithm SHA256).Hash ([string]$prop.Value.sha256).ToUpperInvariant()}}
if($errors.Count-eq0){try{$t=& (Join-Path $repo 'work/20260828-original-client-warp-stage-owner-pointer/tests/test-warp-stage-owner-snapshot.ps1')|ConvertFrom-Json;Eq 'collector tests result' $t.result 'PASS';Eq 'collector cases' $t.cases 22;Eq 'collector assertions' $t.assertions 37}catch{$errors.Add("collector tests failed: $($_.Exception.Message)")}}
if($errors.Count-eq0){try{$v4=& (Join-Path $repo 'work/20260828-original-client-first-play-prelaunch-manager65-integration-v4/verify.ps1')|ConvertFrom-Json;Eq 'fresh v4 result' $v4.result 'PASS';Eq 'fresh v4 ledger' $v4.artifactLedgerSha256 $hashes.priorV4ArtifactLedger;Eq 'fresh v4 live' $v4.liveOperations 0;Eq 'fresh v4 inputs' $v4.gameInputs 0}catch{$errors.Add("fresh v4 failed: $($_.Exception.Message)")}}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors)}|ConvertTo-Json -Depth 10;return}
[ordered]@{result='PASS';state=$contract.state;blockerCount=$contract.blockers.Count;firstMissingBoundary=$contract.firstMissingBoundary;firstTechnicalBoundary=$contract.firstTechnicalBoundary;warpOwnerStaticGapsResolved=1;warpOwnerFreshRuntimeBoundary=$introduced[0];priorPermitState=$contract.priorPermit.state;liveOperations=0;gameInputs=0;permitIssued=$false}|ConvertTo-Json
