$ErrorActionPreference='Stop';$root=$PSScriptRoot
$collectorTests=& (Join-Path $root 'tests/test-warp-stage-owner-snapshot.ps1')|ConvertFrom-Json
$v5Tests=& (Join-Path $root 'tests/test-prelaunch-v5-warp-owner.ps1')|ConvertFrom-Json
$contract=& (Join-Path $root 'src/verify-prelaunch-v5-warp-owner.ps1') -ContractPath (Join-Path $root 'evidence/prelaunch-v5-warp-owner.json')|ConvertFrom-Json
if($collectorTests.result-ne'PASS'-or$collectorTests.cases-ne22-or$collectorTests.assertions-ne37){throw 'collector test contract mismatch'}
if($v5Tests.result-ne'PASS'-or$v5Tests.cases-ne13-or$v5Tests.assertions-ne23){throw 'v5 test contract mismatch'}
if($contract.result-ne'PASS'){throw 'v5 semantic contract failed'}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('logh7-warp-owner-verify-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null
try{$replay=Join-Path $temp 'fixture-snapshot.json';& (Join-Path $root 'src/collect-warp-stage-owner-snapshot.ps1') -FixtureMemoryPath (Join-Path $root 'tests/fixture-memory.json') -FixtureIdentityPath (Join-Path $root 'tests/fixture-identity.json') -OutputPath $replay|Out-Null;if((Get-FileHash $replay -Algorithm SHA256).Hash-ne(Get-FileHash (Join-Path $root 'evidence/fixture-snapshot.json') -Algorithm SHA256).Hash){throw 'fixture replay drift'}}finally{if(Test-Path $temp){$resolved=(Resolve-Path $temp).Path;$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if(-not$resolved.StartsWith($base,[StringComparison]::OrdinalIgnoreCase)){throw 'unsafe cleanup'};Remove-Item $resolved -Recurse -Force}}
$collector=Get-Content (Join-Path $root 'src/collect-warp-stage-owner-snapshot.ps1') -Raw -Encoding UTF8;$semantic=Get-Content (Join-Path $root 'src/verify-prelaunch-v5-warp-owner.ps1') -Raw -Encoding UTF8
$forbidden=@('WriteProcessMemory','SendInput','SetCursorPos','PostMessage','mouse_event','keybd_event','VirtualAllocEx','CreateRemoteThread','Invoke-VMScript','vmrun','x32dbg');$hits=@($forbidden|Where-Object{$collector.Contains($_)});if($hits.Count){throw "forbidden capability $($hits-join', ')"};if(-not$collector.Contains('OpenProcess(0x0410')){throw 'read-only access mask missing'}
$ledgerPath=Join-Path $root 'evidence/artifact-ledger.json';$ledger=Get-Content $ledgerPath -Raw -Encoding UTF8|ConvertFrom-Json;$map=[ordered]@{};foreach($a in $ledger.artifacts){$p=Join-Path $root ([string]$a.path);$h=(Get-FileHash $p -Algorithm SHA256).Hash;if($h-ne$a.sha256){throw "artifact drift $($a.path)"};$map[$a.path]=$h}
[ordered]@{result='PASS';collectorTests=$collectorTests;prelaunchV5Tests=$v5Tests;contract=$contract;fixtureReplay='PASS';artifactHashesVerified=$ledger.artifacts.Count;artifactLedgerSha256=(Get-FileHash $ledgerPath -Algorithm SHA256).Hash;artifactHashMap=$map;nativeCapability='READ_ONLY_PROCESS_MEMORY';forbiddenCapabilityHits=0;temporaryWrites=@('collector and mutation outputs under system temp');persistentWorkspaceWrites=0;liveOperations=0;processMemoryReads=0;gameInputs=0;permitIssued=$false;status='STATIC_WARP_STAGE_MANAGER_OWNER_PASS_LIVE_SNAPSHOT_UNSEEN'}|ConvertTo-Json -Depth 12
