[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ContractPath)
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$contract=Get-Content -LiteralPath $ContractPath -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Eq($name,$actual,$expected){if($actual-ne$expected){$errors.Add("$name expected=$expected actual=$actual")}}
function Seq($name,$actual,$expected){if((@($actual)|ConvertTo-Json -Compress -Depth 20)-ne(@($expected)|ConvertTo-Json -Compress -Depth 20)){$errors.Add("$name sequence mismatch")}}
function Load($path){Get-Content -LiteralPath $path -Raw -Encoding UTF8|ConvertFrom-Json}
$hashes=[ordered]@{
 movementStaticLedger='9BC141E9C2F9AA7A0EF6BADF9B63CED2822F3E5D7AF820382F38803523ED3B99'
 movementSchema='1DBADE5E0EFAC91ED648307C8026B26A4F80BC9A4E3A4F2E80AAED749BFC24F4'
 movementTemplate='122B8555BF25E752AE82958F14188669FCCE6B7FFB9BF4A9307CF1EA0DE9AD5A'
 movementVerifier='299648AED08C07A75B31A0E52D2A59A6AAE35C0B24E7E46CAD0D7452B9B1BCFF'
 movementFixture='6B6E0509C37259D29CE2E2317AF5363626B7458C7B81B028B9CC5602CD2786DE'
 movementTests='0DF45DA9CAD41288E578889019F5FE7DCE84A7737AFE075082B6B9CB5C2516F6'
 priorV5Contract='C699A8718EB659FB3346092DFCC4AA93F20F917FC6FBCCBF91BC36504E9D311C'
 priorV5Verification='D9F67AAC1B549AE1A96BBF59F017817C1372A97DA599E89FAEAC3EF4259F0F30'
 priorV5ArtifactLedger='327661670F7E0B0B9DAE67679CA59736913FF5C96BAD5FB00FFD6149E9F11F05'
}
$loaded=@{}
foreach($name in $hashes.Keys){$entry=$contract.boundArtifacts.$name;if($null-eq$entry){$errors.Add("missing artifact $name");continue};Eq "$name declared" ([string]$entry.sha256).ToUpperInvariant() $hashes[$name];$path=Join-Path $repo ([string]$entry.path);if(-not(Test-Path -LiteralPath $path)){$errors.Add("missing file $name");continue};Eq "$name actual" (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash $hashes[$name];if([IO.Path]::GetExtension($path)-eq'.json'){$loaded[$name]=Load $path}}
Eq 'schema' $contract.schemaVersion 6
Eq 'contract' $contract.contract 'ORIGINAL_CLIENT_FIRST_SERVER_BACKED_PLAY_PRELAUNCH_V6_MOVEMENT_RECEIPT_SCHEMA_INTEGRATED'
Eq 'state' $contract.state 'OFFLINE_PRELAUNCH_MOVEMENT_RECEIPT_SCHEMA_INTEGRATED_READY_FALSE'
Eq 'run id' $contract.oracleRunId $null;Eq 'launch' $contract.launchEligible $false;Eq 'permit eligible' $contract.permitEligible $false;Eq 'permit issued' $contract.permitIssued $false
Eq 'authority source' $contract.currentAuthority.source 'USER_APPROVED_CURRENT_THREAD';Eq 'authority scope' $contract.currentAuthority.scope 'ONE_LIVE_ORACLE_ONE_PHYSICAL_ACTIVATION_READ_ONLY_CAPTURE';Eq 'activation budget' $contract.currentAuthority.activationBudget 1;Eq 'gate bypass' $contract.currentAuthority.doesNotBypassPrelaunchGates $true
Eq 'prior permit id' $contract.priorPermit.id 'permit-live-v3-20260827-d89449bc2c3c4b70a9854833b2214012-once';Eq 'prior permit state' $contract.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'prior reusable' $contract.priorPermit.reusable $false
$resolved=@('MOVEMENT_SPECIFIC_BREAKPOINT_RECEIPT_SCHEMA_MISSING');$introduced=@('MOVEMENT_HARDWARE_BREAKPOINT_REARM_PLAN_MISSING');Seq 'resolved' $contract.integrationDelta.resolvedStaticBlockers $resolved;Seq 'introduced' $contract.integrationDelta.introducedStaticBlockers $introduced;Eq 'prior count' $contract.integrationDelta.priorBlockerCount 12;Eq 'current count' $contract.integrationDelta.currentBlockerCount 12
$expected=@('ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH','MOVEMENT_HARDWARE_BREAKPOINT_REARM_PLAN_MISSING','FRESH_RUN_IDENTITY_MISSING','FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING','MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_MANAGER65_SNAPSHOT_MISSING','MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_WARP_STAGE_OWNER_SNAPSHOT_MISSING','FRESH_DESTINATION_PROJECTION_SNAPSHOT_MISSING','FRESH_TEXTDIALOG_SNAPSHOT_MISSING','FOREGROUND_PROBE_NOT_RUN','INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING');Seq 'blockers' $contract.blockers $expected;Eq 'first missing' $contract.firstMissingBoundary $expected[0];Eq 'first technical' $contract.firstTechnicalBoundary $expected[1]
$m=$contract.staticPreparation.movementReceipt;Eq 'movement status' $m.status 'OFFLINE_MOVEMENT_RECEIPT_SCHEMA_PASS_LIVE_INSTALLATION_MISSING';Eq 'primary anchors' $m.primaryAnchorCount 7;Eq 'completion anchors' $m.completionAnchorCount 2;Eq 'total anchors' $m.totalAnchorCount 9;Eq 'mechanism' $m.breakpointMechanism 'HARDWARE_EXECUTION_REARM_REQUIRED_UNPROVEN';Eq 'hardware max' $m.maximumConcurrentHardwareBreakpoints 4;Eq 'int3' $m.softwareInt3Allowed $false;Eq 'writes allowed' $m.processMemoryWritesAllowed $false;Eq 'queue completion' $m.queueCompletion 'UNSEEN';Eq 'codec' $m.fullPayloadCodec 'CODEC_UNPROVEN';Eq 'runtime' $m.runtimeObserved 'UNSEEN';Eq 'visible' $m.playerVisible 'UNSEEN';Eq 'authority' $m.authorityProven 'UNSEEN'
$composition=@('fresh G7MTClient PID/startTime/hash/moduleBase/HWND/owner/client surface','fresh listener and heartbeat','fresh x32dbg PID/startTime/HWND/owner and exact foreground','fresh manager65-bound manager67 authority-card/action-0x2B/page-selected widget/gates/rect snapshot','independently bound manager67 authority-card hit region','fresh hardened manager65 action-0x2B snapshot','independently bound manager65 action-0x2B hit region','fresh WARP stage-owner snapshot binding active flow child[2] to the scoped TextDialog manager','fresh destination projection snapshot and independently resolved hit region','fresh TextDialog snapshot and independently resolved confirm region','independently reviewed non-writing hardware breakpoint rearm plan and fresh installation receipt','one authorized physical activation followed by separately adjudicated stage progression and movement outbound/inbound/queue-completion/pixel receipts');Seq 'composition' $contract.requiredSameRunComposition $composition
$forbidden=@('reuse prior permit/run/PID/HWND/pointer/coordinate','software INT3 or any process-memory-write breakpoint mechanism','automatic click or retry','input before all same-run gates and independent review pass','binary/resource patch','VM lifecycle or server/protocol/database change','fixture or self-claimed live evidence promotion');Seq 'forbidden' $contract.forbidden $forbidden
$counterNames=@('guestOperations','debuggerAttach','breakpointsInstalled','processMemoryReads','physicalInputs','captures','memoryWrites');Seq 'counters' @($contract.operationCounters.PSObject.Properties.Name) $counterNames;foreach($name in $counterNames){Eq "counter $name" $contract.operationCounters.$name 0}
if($loaded.ContainsKey('priorV5Contract')){$v5=$loaded.priorV5Contract;Eq 'v5 state' $v5.state 'OFFLINE_PRELAUNCH_WARP_OWNER_INTEGRATED_READY_FALSE';Eq 'v5 blockers' @($v5.blockers).Count 12;$derived=@($v5.blockers|Where-Object{$_-ne'MOVEMENT_SPECIFIC_BREAKPOINT_RECEIPT_SCHEMA_MISSING'});$derived=@($derived[0])+$introduced+@($derived[1..($derived.Count-1)]);Seq 'v5 delta' $contract.blockers $derived}
if($loaded.ContainsKey('priorV5Verification')){$v=$loaded.priorV5Verification;Eq 'v5 result' $v.result 'PASS';Eq 'v5 collector cases' $v.collectorTests.cases 22;Eq 'v5 movement cases' $v.prelaunchV5Tests.cases 13;Eq 'v5 live' $v.liveOperations 0;Eq 'v5 inputs' $v.gameInputs 0;Eq 'v5 permit' $v.permitIssued $false}
if($loaded.ContainsKey('priorV5ArtifactLedger')){$l=$loaded.priorV5ArtifactLedger;Eq 'v5 artifact count' @($l.artifacts).Count 12}
if($loaded.ContainsKey('movementStaticLedger')){$l=$loaded.movementStaticLedger;Eq 'static target' $l.target.sha256 'BD19263C10DECC3D58373165A82D42A9267868400D407DA87D5F4F4109AB6E16';Eq 'static count' @($l.anchors).Count 9;Eq 'primary count' $l.status.primaryAnchorCount 7;Eq 'completion count' $l.status.completionAnchorCount 2;Eq 'live receipt' $l.status.liveReceipt 'MISSING';Eq 'rearm plan' $l.status.hardwareBreakpointRearmPlan 'UNPROVEN'}
if($loaded.ContainsKey('movementSchema')){$s=$loaded.movementSchema;Eq 'schema dialect' $s.'$schema' 'https://json-schema.org/draft/2020-12/schema';Eq 'schema closed' $s.additionalProperties $false;Eq 'schema breakpoint min' $s.properties.breakpoints.minItems 9;Eq 'schema breakpoint max' $s.properties.breakpoints.maxItems 9}
if($loaded.ContainsKey('movementTemplate')){$t=$loaded.movementTemplate;Eq 'template state' $t.state 'EMPTY_TEMPLATE_NOT_LIVE';Eq 'template anchors' @($t.breakpoints).Count 9;Eq 'template hits' @($t.hits).Count 0;Eq 'template mechanism' $t.instrumentationPlan.mechanism 'NOT_RUN';Eq 'template rearm' $t.instrumentationPlan.rearmPlanStatus 'UNPROVEN';Eq 'template live eligible' $t.evaluation.liveReceiptEligible $false;Eq 'template permit' $t.permitIssued $false;foreach($p in $t.operations.PSObject.Properties){Eq "template op $($p.Name)" $p.Value 0}}
if($errors.Count-eq0){try{$r=& (Join-Path $repo 'work/20260828-original-client-movement-breakpoint-receipt-schema/tests/test-movement-breakpoint-receipt.ps1')|ConvertFrom-Json;Eq 'movement test result' $r.result 'PASS';Eq 'movement cases' $r.cases 39;Eq 'movement assertions' $r.assertions 53;Eq 'movement mutations' $r.mutations 37}catch{$errors.Add("movement tests failed: $($_.Exception.Message)")}}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors)}|ConvertTo-Json -Depth 12;return}
[ordered]@{result='PASS';state=$contract.state;blockerCount=$contract.blockers.Count;firstMissingBoundary=$contract.firstMissingBoundary;firstTechnicalBoundary=$contract.firstTechnicalBoundary;movementSchemaStaticGapsResolved=1;primaryAnchorCount=$m.primaryAnchorCount;completionAnchorCount=$m.completionAnchorCount;runtimeStatus=$m.runtimeObserved;priorPermitState=$contract.priorPermit.state;liveOperations=0;gameInputs=0;permitIssued=$false}|ConvertTo-Json
