$ErrorActionPreference='Stop'
$root=$PSScriptRoot;$repo=(Resolve-Path (Join-Path $root '..\..')).Path
$tests=& (Join-Path $root 'tests/test-manager65-live-collector-hardening.ps1')|ConvertFrom-Json
if($tests.result-ne'PASS'-or$tests.cases-ne44-or$tests.assertions-ne91){throw 'test contract mismatch'}
$ledger=Get-Content (Join-Path $root 'evidence/static-owner-ledger.json') -Raw -Encoding UTF8|ConvertFrom-Json
foreach($source in $ledger.sources){$path=Join-Path $repo ([string]$source.path);if(-not(Test-Path $path)){throw "missing source $($source.path)"};if((Get-FileHash $path -Algorithm SHA256).Hash-ne$source.sha256){throw "source hash mismatch $($source.path)"}}
$exe=(Resolve-Path (Join-Path $repo 'evidence/installshield-extract/*/*/exe/g7mtclient.exe')).Path;if((Get-FileHash $exe -Algorithm SHA256).Hash-ne$ledger.target.sha256){throw 'canonical executable hash mismatch'}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('manager65-hardening-verify-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null
try{$capture=Join-Path $temp 'fixture-capture.json';$resolution=Join-Path $temp 'fixture-resolution.json';& (Join-Path $root 'src/collect-manager65-action2b-hardened.ps1') -FixtureMemoryPath (Join-Path $root 'tests/fixture-memory.json') -FixtureIdentityPath (Join-Path $root 'tests/fixture-identity.json') -OutputPath $capture;& (Join-Path $root 'src/resolve-manager65-action2b-hardened.ps1') -CapturePath $capture -OutputPath $resolution;foreach($pair in @(@($capture,(Join-Path $root 'evidence/fixture-capture.json')),@($resolution,(Join-Path $root 'evidence/fixture-resolution.json')))){if((Get-FileHash $pair[0] -Algorithm SHA256).Hash-ne(Get-FileHash $pair[1] -Algorithm SHA256).Hash){throw "published fixture drift $($pair[1])"}}}finally{if(Test-Path $temp){$resolved=(Resolve-Path $temp).Path;$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if(-not$resolved.StartsWith($base,[StringComparison]::OrdinalIgnoreCase)){throw 'unsafe cleanup'};Remove-Item $resolved -Recurse -Force}}
$collectorPath=Join-Path $root 'src/collect-manager65-action2b-hardened.ps1';$resolverPath=Join-Path $root 'src/resolve-manager65-action2b-hardened.ps1';$collector=Get-Content $collectorPath -Raw -Encoding UTF8;$resolver=Get-Content $resolverPath -Raw -Encoding UTF8
$imports=[regex]::Matches($collector,'DllImport\("(?<dll>[^\"]+)"[^\]]*\)\]\s*public static extern (?<sig>[^;]+);');$native=@($imports|ForEach-Object{if($_.Groups['sig'].Value-match'\s(?<name>[A-Za-z0-9_]+)\('){$Matches.name}}|Sort-Object -Unique);$expected=@('CloseHandle','GetClientRect','GetWindowThreadProcessId','IsWindow','OpenProcess','ReadProcessMemory');if(($native|ConvertTo-Json -Compress)-ne($expected|ConvertTo-Json -Compress)){throw "native surface mismatch $($native-join', ')"}
$forbidden=@('WriteProcessMemory','SendInput','SetCursorPos','PostMessage','mouse_event','keybd_event','VirtualAllocEx','CreateRemoteThread','Invoke-VMScript','vmrun','x32dbg');$hits=@($forbidden|Where-Object{$collector.Contains($_)-or$resolver.Contains($_)});if($hits.Count){throw "forbidden capability $($hits-join', ')"};if(-not$collector.Contains('OpenProcess(0x0410')){throw 'read-only access mask missing'}
$captureJson=Get-Content (Join-Path $root 'evidence/fixture-capture.json') -Raw|ConvertFrom-Json;$resolutionJson=Get-Content (Join-Path $root 'evidence/fixture-resolution.json') -Raw|ConvertFrom-Json;if(-not$captureJson.stateEligible-or$captureJson.operations.memoryReadCount-ne142-or$resolutionJson.status-ne'OFFLINE_RESOLVED'-or$resolutionJson.automaticActivationPoint-ne$null){throw 'published semantic fixture mismatch'}
$artifactLedgerPath=Join-Path $root 'evidence/artifact-ledger.json';$artifactLedger=Get-Content $artifactLedgerPath -Raw -Encoding UTF8|ConvertFrom-Json;$map=[ordered]@{};foreach($artifact in $artifactLedger.artifacts){$path=Join-Path $root ([string]$artifact.path);$hash=(Get-FileHash $path -Algorithm SHA256).Hash;if($hash-ne$artifact.sha256){throw "artifact hash mismatch $($artifact.path)"};$map[$artifact.path]=$hash}
[ordered]@{result='PASS';tests=$tests;sourceHashesVerified=$ledger.sources.Count;canonicalExecutableVerified=$true;publishedFixtureArtifactsReproduced=2;artifactHashesVerified=$artifactLedger.artifacts.Count;artifactLedgerSha256=(Get-FileHash $artifactLedgerPath -Algorithm SHA256).Hash;artifactHashMap=$map;nativeReadOnlyApis=$native;forbiddenCapabilityHits=0;liveOperations=0;processMemoryReads=0;gameInputs=0;permitIssued=$false;status='OFFLINE_MANAGER65_HARDENED_COLLECTOR_RESOLVER_PASS_LIVE_UNSEEN'}|ConvertTo-Json -Depth 10
