[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ContractPath)
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$contract=Get-Content -LiteralPath $ContractPath -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Eq($name,$actual,$expected){if($actual-ne$expected){$errors.Add("$name expected=$expected actual=$actual")}}
function Seq($name,$actual,$expected){if((@($actual)|ConvertTo-Json -Compress -Depth 30)-ne(@($expected)|ConvertTo-Json -Compress -Depth 30)){$errors.Add("$name sequence mismatch")}}
function Load($path){Get-Content -LiteralPath $path -Raw -Encoding UTF8|ConvertFrom-Json}
$hashes=[ordered]@{
 hardwareRearmPlan='54192253616B5CE26F81A87276BD861B15069677E8F3EEDD6C3FA903D8DE665D'
 hardwareDryRun='F9CEA3F0AF236BBB20A7742DA06B6C3C16FEFD83BAD01FA12A611D31DA997F06'
 officialSources='AFC36F62445424A84D46C9C68DE25C3A33ADF97D2F636CA3490A5DD53555C2F7'
 hardwareVerifier='166BA3EB1D01558CCAC87C2E8AE3D15BF00324DAFFB49F380DD4DEEECB6B7E51'
 hardwareTests='792F8FE4710C2678E73336A1EA20D411E1703750FF4A0D83D69B67AF1E84228F'
 priorV6Contract='7371B9157C329FA4B538792C1C999B46671CE7E66B30C3F2AECC4B59A7C10C1F'
 priorV6Verifier='207883D457B9F8F43845825BA577919BF7F2A10774B2449EF80613AFB9387288'
 priorV6Tests='1D5579E172FF47E817421065570AEF04882165FCF70A19501B707E6897A93D32'
 priorV6FinalVerification='CAFFEF999A83FA5E862A63743BF843840E3FDC5C3CE306EB5DDA6B1226C555CC'
 priorV6ArtifactLedger='7A6E5594B7D2DA7DB331A92BEA350759EF36EB857AF75E379C12DE7DF8209DE3'
}
$loaded=@{}
foreach($name in $hashes.Keys){$entry=$contract.boundArtifacts.$name;if($null-eq$entry){$errors.Add("missing artifact $name");continue};Eq "$name declared" ([string]$entry.sha256).ToUpperInvariant() $hashes[$name];$path=Join-Path $repo ([string]$entry.path);if(-not(Test-Path -LiteralPath $path)){$errors.Add("missing file $name");continue};Eq "$name actual" (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash $hashes[$name];if([IO.Path]::GetExtension($path)-eq'.json'){$loaded[$name]=Load $path}}
Eq 'schema' $contract.schemaVersion 7;Eq 'contract' $contract.contract 'ORIGINAL_CLIENT_FIRST_SERVER_BACKED_PLAY_PRELAUNCH_V7_HARDWARE_REARM_PLAN_INTEGRATED';Eq 'state' $contract.state 'OFFLINE_PRELAUNCH_HARDWARE_REARM_PLAN_INTEGRATED_RECEIPT_V2_MISSING_READY_FALSE';Eq 'run' $contract.oracleRunId $null;Eq 'launch' $contract.launchEligible $false;Eq 'permit eligible' $contract.permitEligible $false;Eq 'permit issued' $contract.permitIssued $false
Eq 'authority source' $contract.currentAuthority.source 'USER_APPROVED_CURRENT_THREAD';Eq 'authority scope' $contract.currentAuthority.scope 'ONE_LIVE_ORACLE_ONE_PHYSICAL_ACTIVATION_READ_ONLY_CAPTURE';Eq 'activation budget' $contract.currentAuthority.activationBudget 1;Eq 'bypass' $contract.currentAuthority.doesNotBypassPrelaunchGates $true;Eq 'prior id' $contract.priorPermit.id 'permit-live-v3-20260827-d89449bc2c3c4b70a9854833b2214012-once';Eq 'prior state' $contract.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'prior reusable' $contract.priorPermit.reusable $false
$resolved=@('MOVEMENT_HARDWARE_BREAKPOINT_REARM_PLAN_MISSING');$introduced=@('MOVEMENT_RECEIPT_TEMPORAL_THREAD_CORRELATION_SCHEMA_MISSING');Seq 'resolved' $contract.integrationDelta.resolvedStaticBlockers $resolved;Seq 'introduced' $contract.integrationDelta.introducedStaticBlockers $introduced;Eq 'prior count' $contract.integrationDelta.priorBlockerCount 12;Eq 'current count' $contract.integrationDelta.currentBlockerCount 12
$expected=@('ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH','MOVEMENT_RECEIPT_TEMPORAL_THREAD_CORRELATION_SCHEMA_MISSING','FRESH_RUN_IDENTITY_MISSING','FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING','MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_MANAGER65_SNAPSHOT_MISSING','MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_WARP_STAGE_OWNER_SNAPSHOT_MISSING','FRESH_DESTINATION_PROJECTION_SNAPSHOT_MISSING','FRESH_TEXTDIALOG_SNAPSHOT_MISSING','FOREGROUND_PROBE_NOT_RUN','INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING');Seq 'blockers' $contract.blockers $expected;Eq 'first missing' $contract.firstMissingBoundary $expected[0];Eq 'first technical' $contract.firstTechnicalBoundary $expected[1]
$h=$contract.staticPreparation.hardwareRearm;Eq 'rearm status' $h.status 'OFFLINE_HARDWARE_REARM_PLAN_PASS_RECEIPT_SCHEMA_GAP';Eq 'anchors' $h.anchorCount 9;Eq 'phases' $h.phaseCount 10;Eq 'slot max' $h.maximumConcurrentSlots 4;Eq 'peak' $h.peakActiveSlots 4;Eq 'mechanism' $h.mechanism 'X86_DEBUG_REGISTERS_EXECUTE_SIZE_1';Eq 'installed commit' $h.installedX32dbgCommit '9c8ca1cae0b6d56cc44f31fddcb10e3b02ffbb87';Eq 'installed exe' $h.installedX32dbgExeSha256 '822028F0755DBA773E445EAF57FDB3DBA84C9550AC7BDAD2AFA449912B5FBA41';Eq 'installed commit file' $h.installedCommitHashFileSha256 '80A7077840C2DD987861A857DB19C06279408E0344B0AD13538217075A0E2C67';Eq 'thread coverage' $h.threadCoverage 'STATIC_SOURCE_INDICATES_ALL_THREAD_PROGRAMMING_RUNTIME_UNSEEN';Eq 'thread receipt' $h.livePerThreadDrReceipt 'MISSING';Eq 'runtime no miss' $h.runtimeNoMissProof 'MISSING';Eq 'runtime' $h.runtimeObserved 'UNSEEN'
$missing=@('HIT_THREAD_ID_AND_DEBUG_EVENT_ORDINAL','TEMPORAL_REARM_PHASE_LEDGER','PER_THREAD_DR_STATE_RECEIPT','REJECTED_HIT_LOG','UNIQUE_PENDING_0X0B07_QUEUE_CENSUS','REARM_PLAN_VERSION_AND_ARTIFACT_SHA256','INSTALLED_X32DBG_EXE_DLL_GUI_AND_COMMITHASH_BINDING','PER_PHASE_BPHWC_BPHWS_COMMAND_RESULT_PRE_POST_ACTIVE_SET_AND_BEFORE_RESUME_VERIFICATION');Eq 'v2 status' $contract.staticPreparation.receiptV2.status 'MISSING';Seq 'v2 fields' $contract.staticPreparation.receiptV2.missingFields $missing
$forbidden=@('reuse prior permit/run/PID/HWND/pointer/coordinate','software INT3, empty-address bphwc, DR-slot-number dependency, or any process-memory write','automatic click, retry, or breakpoint rearm command','input before all same-run gates, receipt-v2 schema, and independent review pass','binary/resource patch','VM lifecycle or server/protocol/database change','fixture, static source, bplist, or self-claimed live evidence promotion');Seq 'forbidden' $contract.forbidden $forbidden
$counterNames=@('guestOperations','debuggerAttach','debuggerCommands','breakpointsInstalled','processMemoryReads','physicalInputs','captures','memoryWrites');Seq 'counters' @($contract.operationCounters.PSObject.Properties.Name) $counterNames;foreach($name in $counterNames){Eq "counter $name" $contract.operationCounters.$name 0}
if($loaded.ContainsKey('priorV6Contract')){$v6=$loaded.priorV6Contract;Eq 'v6 state' $v6.state 'OFFLINE_PRELAUNCH_MOVEMENT_RECEIPT_SCHEMA_INTEGRATED_READY_FALSE';Eq 'v6 count' @($v6.blockers).Count 12;$derived=@($v6.blockers|Where-Object{$_-ne'MOVEMENT_HARDWARE_BREAKPOINT_REARM_PLAN_MISSING'});$derived=@($derived[0])+$introduced+@($derived[1..($derived.Count-1)]);Seq 'v6 delta' $contract.blockers $derived}
if($loaded.ContainsKey('priorV6FinalVerification')){$v=$loaded.priorV6FinalVerification;Eq 'v6 final result' $v.result 'PASS';Eq 'v6 final status' $v.status 'OFFLINE_MOVEMENT_RECEIPT_SCHEMA_PASS_REARM_PLAN_MISSING_RUNTIME_UNSEEN';Eq 'v6 final live' $v.liveOperations 0;Eq 'v6 final inputs' $v.gameInputs 0;Eq 'v6 final permit' $v.permitIssued $false}
if($loaded.ContainsKey('priorV6ArtifactLedger')){$l=$loaded.priorV6ArtifactLedger;Eq 'v6 ledger count' @($l.artifacts).Count 11}
if($loaded.ContainsKey('hardwareRearmPlan')){$p=$loaded.hardwareRearmPlan;Eq 'plan state' $p.state $h.status;Eq 'plan slots' $p.hardware.maximumConcurrentSlots 4;Eq 'plan phases' (1+@($p.transitions).Count) 10;Eq 'plan receipt gap' $p.receiptGapAudit.status 'MISSING';Seq 'plan missing fields' $p.receiptGapAudit.missingFields $missing;Eq 'plan boundary' $p.receiptGapAudit.nextBoundary $expected[1];Eq 'plan live eligible' $p.dryRun.liveInstallEligible $false;foreach($op in $p.operations.PSObject.Properties){Eq "plan op $($op.Name)" $op.Value 0}}
if($loaded.ContainsKey('hardwareDryRun')){$d=$loaded.hardwareDryRun;Eq 'dry result' $d.result 'PASS';Eq 'dry runtime' $d.runtimeStatus 'SYNTHETIC_DRY_RUN_ONLY';Eq 'dry phases' $d.phaseCount 10;Eq 'dry peak' $d.peakActiveSlots 4;Eq 'dry live' $d.liveOperations 0;Eq 'dry permit' $d.permitIssued $false}
if($loaded.ContainsKey('officialSources')){$s=$loaded.officialSources;Eq 'source boundary' $s.claimBoundary 'STATIC_SOURCE_PROVEN_LIVE_BEHAVIOR_UNSEEN';Eq 'source commit' $s.officialSource.x64dbg.commit '9c8ca1cae0b6d56cc44f31fddcb10e3b02ffbb87'}
$freshTraceCompared=$false
if($errors.Count-eq0){try{$fresh=& (Join-Path $repo 'work/20260828-original-client-movement-hardware-rearm-plan/src/verify-hardware-rearm-plan.ps1') -PlanPath (Join-Path $repo 'work/20260828-original-client-movement-hardware-rearm-plan/evidence/hardware-rearm-plan.json')|ConvertFrom-Json;Eq 'fresh plan result' $fresh.result 'PASS';$d=$loaded.hardwareDryRun;Eq 'fresh trace hash' $fresh.traceSha256 $d.traceSha256;Eq 'fresh phase count' $fresh.phaseCount $d.phaseCount;Eq 'fresh transition count' $fresh.transitionCount $d.transitionCount;Eq 'fresh peak' $fresh.peakActiveSlots $d.peakActiveSlots;$freshTraceCompared=($fresh.result-eq'PASS'-and$fresh.traceSha256-eq$d.traceSha256-and$fresh.phaseCount-eq$d.phaseCount-and$fresh.transitionCount-eq$d.transitionCount-and$fresh.peakActiveSlots-eq$d.peakActiveSlots)}catch{$errors.Add("fresh trace comparison failed: $($_.Exception.Message)")}}
if($errors.Count-eq0){try{$r=& (Join-Path $repo 'work/20260828-original-client-movement-hardware-rearm-plan/tests/test-hardware-rearm-plan.ps1')|ConvertFrom-Json;Eq 'hardware tests' $r.result 'PASS';Eq 'hardware cases' $r.cases 39;Eq 'hardware assertions' $r.assertions 59;Eq 'hardware mutations' $r.mutations 38}catch{$errors.Add("hardware tests failed: $($_.Exception.Message)")}}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors)}|ConvertTo-Json -Depth 20;return}
[ordered]@{result='PASS';state=$contract.state;blockerCount=@($contract.blockers).Count;firstMissingBoundary=$contract.firstMissingBoundary;firstTechnicalBoundary=$contract.firstTechnicalBoundary;hardwareRearmPlanResolved=1;receiptV2Status=$contract.staticPreparation.receiptV2.status;receiptV2MissingFieldCount=@($missing).Count;freshTraceCompared=$freshTraceCompared;priorV6SealBound=($loaded.ContainsKey('priorV6FinalVerification')-and$loaded.ContainsKey('priorV6ArtifactLedger'));liveOperations=0;gameInputs=0;permitIssued=$false}|ConvertTo-Json
