[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$PlanPath)
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$plan=Get-Content -LiteralPath $PlanPath -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Eq($name,$actual,$expected){if($actual-ne$expected){$errors.Add("$name expected=$expected actual=$actual")}}
function Seq($name,$actual,$expected){if((@($actual)|ConvertTo-Json -Compress)-ne(@($expected)|ConvertTo-Json -Compress)){$errors.Add("$name sequence mismatch")}}
function Apply-Transition($active,$remove,$add){$next=[Collections.Generic.List[string]]::new();foreach($id in @($active)){if(@($remove)-notcontains$id){$next.Add([string]$id)}};foreach($id in @($add)){if($next.Contains([string]$id)){$errors.Add("duplicate active anchor $id")}else{$next.Add([string]$id)}};return @($expectedOrder|Where-Object{$next.Contains($_)})}
$expectedOrder=@('MVB01','MVB02','MVB03','MVB04','MVB05','MVB06','MVB07','MVB08','MVB09')
$expectedInitial=@('MVB01','MVB06','MVB08','MVB09')
$expectedBefore=@($expectedInitial,@('MVB02','MVB06','MVB08','MVB09'),@('MVB03','MVB06','MVB08','MVB09'),@('MVB04','MVB06','MVB08','MVB09'),@('MVB05','MVB06','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'))
$expectedAfter=@(@('MVB02','MVB06','MVB08','MVB09'),@('MVB03','MVB06','MVB08','MVB09'),@('MVB04','MVB06','MVB08','MVB09'),@('MVB05','MVB06','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@('MVB06','MVB07','MVB08','MVB09'),@())
$expectedRemove=@(@('MVB01'),@('MVB02'),@('MVB03'),@('MVB04'),@('MVB05'),@(),@(),@(),@('MVB06','MVB07','MVB08','MVB09'))
$expectedAdd=@(@('MVB02'),@('MVB03'),@('MVB04'),@('MVB05'),@('MVB07'),@(),@(),@(),@())
$expectedNext=@('MVB02','MVB03','MVB04','MVB05','MVB06','MVB07','MVB08','MVB09',$null)
Eq 'schema' $plan.schemaVersion 1;Eq 'plan' $plan.plan 'ORIGINAL_CLIENT_MOVEMENT_HARDWARE_REARM_PLAN';Eq 'state' $plan.state 'OFFLINE_HARDWARE_REARM_PLAN_PASS_RECEIPT_SCHEMA_GAP';Eq 'target' $plan.target.sha256 'BD19263C10DECC3D58373165A82D42A9267868400D407DA87D5F4F4109AB6E16';Eq 'address rule' $plan.target.runtimeAddressRule 'freshModuleBase+anchorRva';Eq 'stale address' $plan.target.staleAbsoluteAddressReusable $false;Seq 'anchor order' $plan.anchorOrder $expectedOrder
Eq 'mechanism' $plan.hardware.mechanism 'X86_DEBUG_REGISTERS_EXECUTE_SIZE_1';Eq 'slot limit' $plan.hardware.maximumConcurrentSlots 4;Eq 'int3' $plan.hardware.softwareInt3Allowed $false;Eq 'writes' $plan.hardware.processMemoryWritesAllowed $false;Eq 'singleshoot' $plan.hardware.singleshoot $false;Eq 'automation' $plan.hardware.onHitCommandAutomation $false;Eq 'empty delete' $plan.hardware.emptyDeleteAddressAllowed $false;Eq 'slot dependency' $plan.hardware.slotNumberDependencyAllowed $false;Eq 'operator mode' $plan.hardware.operatorMode 'SINGLE_WRITER_PAUSED_TRANSACTION';Eq 'set command' $plan.hardware.setCommandTemplate 'bphws {runtimeAddress}, x, 1';Eq 'delete command' $plan.hardware.deleteCommandTemplate 'bphwc {runtimeAddress}'
Eq 'installed path' $plan.installedX32dbg.path 'C:/Users/user/Tools/x64dbg-2026.05.27/release/x32/x32dbg.exe';Eq 'installed commit' $plan.installedX32dbg.commit '9c8ca1cae0b6d56cc44f31fddcb10e3b02ffbb87';Eq 'commit file path' $plan.installedX32dbg.commitHashFilePath 'C:/Users/user/Tools/x64dbg-2026.05.27/commithash.txt';Eq 'commit file hash' $plan.installedX32dbg.commitHashFileSha256 '80A7077840C2DD987861A857DB19C06279408E0344B0AD13538217075A0E2C67';Eq 'installed exe hash' $plan.installedX32dbg.x32dbgExeSha256 '822028F0755DBA773E445EAF57FDB3DBA84C9550AC7BDAD2AFA449912B5FBA41';Eq 'installed dll hash' $plan.installedX32dbg.x32dbgDllSha256 '1C2A4A10E0D1C33FE230277E3A4C64AE5E18C165C9D6AED58B1F37E2CE9812FC';Eq 'installed gui hash' $plan.installedX32dbg.x32guiDllSha256 '74090ABE1FF077AB0C56F3B96D18314E7706B867345ABDD05891652F69A96853'
$installedExe=$plan.installedX32dbg.path -replace '/','\';$installedDir=Split-Path -Parent $installedExe;$installedDll=Join-Path $installedDir 'x32dbg.dll';$installedGui=Join-Path $installedDir 'x32gui.dll';foreach($pair in @(@('installed exe actual',$installedExe,$plan.installedX32dbg.x32dbgExeSha256),@('installed dll actual',$installedDll,$plan.installedX32dbg.x32dbgDllSha256),@('installed gui actual',$installedGui,$plan.installedX32dbg.x32guiDllSha256))){if(-not(Test-Path -LiteralPath $pair[1])){$errors.Add("$($pair[0]) missing")}else{Eq $pair[0] (Get-FileHash -LiteralPath $pair[1] -Algorithm SHA256).Hash $pair[2]}}
$commitFile=$plan.installedX32dbg.commitHashFilePath -replace '/','\';if(-not(Test-Path -LiteralPath $commitFile)){$errors.Add('installed commit file missing')}else{Eq 'commit file actual hash' (Get-FileHash -LiteralPath $commitFile -Algorithm SHA256).Hash $plan.installedX32dbg.commitHashFileSha256;Eq 'commit file content' ((Get-Content -LiteralPath $commitFile -Raw).Trim()) $plan.installedX32dbg.commit}
Eq 'thread status' $plan.threadCoverage.status 'STATIC_SOURCE_INDICATES_ALL_THREAD_PROGRAMMING_RUNTIME_UNSEEN';Eq 'all threads source' $plan.threadCoverage.sourceImplementationIteratesAllExistingThreads $true;Eq 'new threads source' $plan.threadCoverage.newThreadHandlerAppliesDefinitionsBeforeContinuation $true;Eq 'selected thread' $plan.threadCoverage.selectedThreadOnlyAllowed $false;Eq 'source todo' $plan.threadCoverage.installedSourceMultiThreadTodoPresent $true;Eq 'runtime validation' $plan.threadCoverage.multiThreadRuntimeValidation 'MISSING';Eq 'live thread receipt' $plan.threadCoverage.livePerThreadDrReceipt 'MISSING'
Eq 'schedule property' $plan.debuggerSemantics.scheduleProperty 'NEXT_ANCHOR_MEMBERSHIP_REQUIRED_BEFORE_RESUME';Eq 'debug event suspension' $plan.debuggerSemantics.debugEventAllThreadsStoppedEvidence 'MISSING_OR_UNBOUND';Eq 'execute preinstruction' $plan.debuggerSemantics.executeHardwareBreakpointPreInstructionEvidence 'MISSING_OR_UNBOUND';Eq 'runtime no miss' $plan.debuggerSemantics.runtimeNoMissProof 'MISSING'
Seq 'initial active' $plan.initial.active $expectedInitial;Eq 'initial stopped required' $plan.initial.targetStoppedRequired $true;Eq 'initial verification required' $plan.initial.allThreadStateVerificationRequiredBeforeResume $true;Eq 'initial resume' $plan.initial.resumeAllowed $false
$active=@($plan.initial.active);$peak=$active.Count;$trace=[Collections.Generic.List[object]]::new();$trace.Add([ordered]@{phase='INITIAL';active=@($active)})
Eq 'transition count' @($plan.transitions).Count 9
for($i=0;$i-lt[Math]::Min(9,@($plan.transitions).Count);$i++){$t=$plan.transitions[$i];Eq "transition[$i] hit" $t.hit $expectedOrder[$i];Seq "transition[$i] before" $t.activeBefore $expectedBefore[$i];Seq "transition[$i] remove" $t.remove $expectedRemove[$i];Seq "transition[$i] add" $t.add $expectedAdd[$i];if($i-lt8){Seq "transition[$i] after" $t.activeAfter $expectedAfter[$i]}else{Eq 'final declared active count' @($t.activeAfter).Count 0};Eq "transition[$i] next" $t.nextRequired $expectedNext[$i];if(@($active)-notcontains$t.hit){$errors.Add("hit not armed $($t.hit)")};Eq "transition[$i] stopped required" $t.targetStoppedForEntireMutationRequired $true;Eq "transition[$i] verification required" $t.activeSetVerificationRequiredBeforeResume $true;$computed=@(Apply-Transition $active $t.remove $t.add);Seq "transition[$i] computed" $computed $t.activeAfter;if(@($computed).Count-gt$plan.hardware.maximumConcurrentSlots){$errors.Add("slot overflow at $i")};$peak=[Math]::Max($peak,@($computed).Count);if($i-lt8){Eq "transition[$i] resume" $t.resumeAllowed $true;Eq "transition[$i] next armed required" $t.nextRequiredArmedBeforeResumeRequired $true;if(@($computed)-notcontains$t.nextRequired){$errors.Add("next anchor not armed $($t.nextRequired)")}}else{Eq 'final resume' $t.resumeAllowed $false;Eq 'final next required' $t.nextRequiredArmedBeforeResumeRequired $false};$active=@($computed);$trace.Add([ordered]@{phase=$t.hit;active=@($active)})}
Eq 'final active count' @($active).Count 0;Eq 'peak slots' $peak 4
Eq 'rotate accepted only' $plan.hitAcceptance.rotateOnlyOnAcceptedCandidateHit $true;Eq 'reject no mutation' $plan.hitAcceptance.rejectedHitDoesNotMutateSlots $true;Eq 'predecessor' $plan.hitAcceptance.laterAnchorWithoutAcceptedPredecessor 'FAIL_CLOSED';Eq 'MVB08 mismatch' $plan.hitAcceptance.mismatchAtMVB08 'FAIL_CLOSED_NO_MVB09_SUCCESS_WAIT';Eq 'second MVB01' $plan.hitAcceptance.noSecondMVB01BetweenMVB05AndMVB06 $true
Eq 'movement source' $plan.sources.movementLedger.sha256 '9BC141E9C2F9AA7A0EF6BADF9B63CED2822F3E5D7AF820382F38803523ED3B99';$movementPath=Join-Path $repo $plan.sources.movementLedger.path;if(-not(Test-Path -LiteralPath $movementPath)){$errors.Add('movement ledger missing')}else{Eq 'movement actual' (Get-FileHash -LiteralPath $movementPath -Algorithm SHA256).Hash $plan.sources.movementLedger.sha256}
Eq 'x64dbg commit' $plan.sources.x64dbg.commit '9c8ca1cae0b6d56cc44f31fddcb10e3b02ffbb87';Eq 'x64dbg source' $plan.sources.x64dbg.commandSourceSha256 'E33D8A19C6B2110EB3786FF6532C51F581C7E0EC3B2AA39735C017C96516114D';Eq 'titan commit' $plan.sources.titanEngine.commit 'ccac889f27622255dfb199b2f534d69e2e1e9050';Eq 'titan breakpoint' $plan.sources.titanEngine.breakpointSourceSha256 '9886D1E28D60A8099F37765414D0FBDAE73587D55ECBAACF88DFA54BB71E0B6E';Eq 'titan loop' $plan.sources.titanEngine.debugLoopSourceSha256 '3EA92B19A27DF1071162FF6DDA24D18A0CA0EF7081A1A3E0A3F3BD570086B1FA';Eq 'doc hash' $plan.sources.setHardwareDoc.contentSha256 '33FD09975D8AA3FDCD98E689CE36FD5E51688DCC12B243A6A66D0AE17FD9C26A'
$missing=@('HIT_THREAD_ID_AND_DEBUG_EVENT_ORDINAL','TEMPORAL_REARM_PHASE_LEDGER','PER_THREAD_DR_STATE_RECEIPT','REJECTED_HIT_LOG','UNIQUE_PENDING_0X0B07_QUEUE_CENSUS','REARM_PLAN_VERSION_AND_ARTIFACT_SHA256','INSTALLED_X32DBG_EXE_DLL_GUI_AND_COMMITHASH_BINDING','PER_PHASE_BPHWC_BPHWS_COMMAND_RESULT_PRE_POST_ACTIVE_SET_AND_BEFORE_RESUME_VERIFICATION');Eq 'gap status' $plan.receiptGapAudit.status 'MISSING';Seq 'missing fields' $plan.receiptGapAudit.missingFields $missing;Eq 'next boundary' $plan.receiptGapAudit.nextBoundary 'MOVEMENT_RECEIPT_TEMPORAL_THREAD_CORRELATION_SCHEMA_MISSING';Eq 'dry runtime' $plan.dryRun.runtimeStatus 'SYNTHETIC_DRY_RUN_ONLY';Eq 'dry live' $plan.dryRun.liveInstallEligible $false;Eq 'dry permit' $plan.dryRun.permitIssued $false
foreach($p in $plan.operations.PSObject.Properties){Eq "operation $($p.Name)" $p.Value 0}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors);liveOperations=0;permitIssued=$false}|ConvertTo-Json -Depth 12;return}
$traceJson=$trace|ConvertTo-Json -Compress -Depth 10;$traceSha=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($traceJson)))
[ordered]@{result='PASS';state=$plan.state;anchorCount=9;maximumConcurrentSlots=4;phaseCount=$trace.Count;transitionCount=9;peakActiveSlots=$peak;threadCoverage=$plan.threadCoverage.status;installedX32dbgCommit=$plan.installedX32dbg.commit;runtimeNoMissProof=$plan.debuggerSemantics.runtimeNoMissProof;receiptV2MissingFieldCount=@($missing).Count;nextBoundary=$plan.receiptGapAudit.nextBoundary;traceSha256=$traceSha;trace=@($trace);liveInstallEligible=$false;liveOperations=0;permitIssued=$false}|ConvertTo-Json -Depth 12
