[CmdletBinding()]
param([int]$TargetProcessId,[string]$ExpectedStartTimeUtc,[string]$ExpectedExecutableSha256,[string]$ExpectedWindowHandle,[string]$FixtureMemoryPath,[string]$FixtureIdentityPath,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop'; $canonical='BD19263C10DECC3D58373165A82D42A9267868400D407DA87D5F4F4109AB6E16'; $script:reads=0
function Hex([uint32]$v){'0x{0:X8}'-f $v}; function Add([uint32]$b,[uint32]$o){$v=[uint64]$b+$o;if($v-gt[uint32]::MaxValue){throw 'address overflow'};[uint32]$v}
$fixtureMode=![string]::IsNullOrWhiteSpace($FixtureMemoryPath);if($fixtureMode-ne(![string]::IsNullOrWhiteSpace($FixtureIdentityPath))){throw 'Both fixture paths are required.'}
$handle=[IntPtr]::Zero
if($fixtureMode){$fixture=Get-Content $FixtureMemoryPath -Raw -Encoding UTF8|ConvertFrom-Json;$identity=Get-Content $FixtureIdentityPath -Raw -Encoding UTF8|ConvertFrom-Json -DateKind String}
else{
 if($ExpectedExecutableSha256.ToUpperInvariant()-ne$canonical){throw 'Expected executable SHA-256 is not the canonical G7MTClient target.'}
 if($TargetProcessId-le 0-or[string]::IsNullOrWhiteSpace($ExpectedStartTimeUtc)-or[string]::IsNullOrWhiteSpace($ExpectedWindowHandle)){throw 'Live identity is incomplete.'}
 if(-not('TextDialogReadOnlyNative'-as[type])){Add-Type -TypeDefinition @'
using System; using System.Runtime.InteropServices;
public static class TextDialogReadOnlyNative {
 [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left,Top,Right,Bottom; }
 [DllImport("kernel32.dll",SetLastError=true)] public static extern IntPtr OpenProcess(uint a,bool i,int p);
 [DllImport("kernel32.dll",SetLastError=true)] public static extern bool ReadProcessMemory(IntPtr p,IntPtr a,byte[] b,UIntPtr n,out UIntPtr r);
 [DllImport("kernel32.dll")] public static extern bool CloseHandle(IntPtr h);
 [DllImport("user32.dll")] public static extern bool IsWindow(IntPtr h);
 [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);
 [DllImport("user32.dll")] public static extern bool GetClientRect(IntPtr h,out RECT r);
}
'@}
 $p=Get-Process -Id $TargetProcessId;$p.Refresh();if($p.ProcessName-ne'G7MTClient'){throw 'Target is not G7MTClient.'}
 $start=$p.StartTime.ToUniversalTime().ToString('o');if($start-ne([DateTime]::Parse($ExpectedStartTimeUtc).ToUniversalTime().ToString('o'))){throw 'Start time mismatch.'}
 $hash=(Get-FileHash $p.Path -Algorithm SHA256).Hash;if($hash-ne$canonical){throw 'Executable hash mismatch.'};$moduleBase=('0x{0:X8}'-f$p.MainModule.BaseAddress.ToInt64());if($moduleBase-ne'0x00400000'){throw "Module base mismatch: $moduleBase"}
 $hwnd=[IntPtr][Convert]::ToInt64(($ExpectedWindowHandle-replace'^0x',''),16);if(-not[TextDialogReadOnlyNative]::IsWindow($hwnd)){throw 'Invalid HWND.'};[uint32]$owner=0;[void][TextDialogReadOnlyNative]::GetWindowThreadProcessId($hwnd,[ref]$owner);if($owner-ne$TargetProcessId-or$p.MainWindowHandle-ne$hwnd){throw 'HWND ownership mismatch.'}
 $rc=New-Object TextDialogReadOnlyNative+RECT;if(-not[TextDialogReadOnlyNative]::GetClientRect($hwnd,[ref]$rc)){throw 'GetClientRect failed.'}
 $identity=[pscustomobject]@{pid=$p.Id;startTimeUtc=$start;sha256=$hash;moduleBase=$moduleBase;hwnd=('0x{0:X8}'-f$hwnd.ToInt64());hwndOwnerPid=$owner;clientWidth=$rc.Right-$rc.Left;clientHeight=$rc.Bottom-$rc.Top;secondHwndOwnerPid=$owner;secondClientWidth=$rc.Right-$rc.Left;secondClientHeight=$rc.Bottom-$rc.Top}
 $handle=[TextDialogReadOnlyNative]::OpenProcess(0x410,$false,$TargetProcessId);if($handle-eq[IntPtr]::Zero){throw 'OpenProcess read-only failed.'}
}
function Bytes([uint32]$a,[int]$n){$b=[byte[]]::new($n);$got=[UIntPtr]::Zero;if(-not[TextDialogReadOnlyNative]::ReadProcessMemory($handle,[IntPtr][int64]$a,$b,[UIntPtr][uint64]$n,[ref]$got)-or$got.ToUInt64()-ne$n){throw "ReadProcessMemory failed at $(Hex $a)"};$script:reads++;,$b}
function FV($section,$kind,[uint32]$a){$k=Hex $a;$v=$section.$kind.PSObject.Properties[$k];if($null-eq$v){throw "Missing fixture $kind $k"};$script:reads++;$v.Value}
function U32($s,[uint32]$a){if($fixtureMode){[uint32](FV $s u32 $a)}else{[BitConverter]::ToUInt32((Bytes $a 4),0)}}
function I32($s,[uint32]$a){if($fixtureMode){[int32](FV $s i32 $a)}else{[BitConverter]::ToInt32((Bytes $a 4),0)}}
function U8($s,[uint32]$a){if($fixtureMode){[byte](FV $s u8 $a)}else{(Bytes $a 1)[0]}}
function F32($s,[uint32]$a){if($fixtureMode){[single](FV $s f32 $a)}else{[BitConverter]::ToSingle((Bytes $a 4),0)}}
function Widget($s,[uint32]$p,[int]$ox,[int]$oy){if($p-eq0){return [ordered]@{widgetPointer='0x00000000';status='NULL'}};$init=U8 $s (Add $p 8);$sel=U8 $s (Add $p 0xA);$lx=I32 $s (Add $p 0xC);$ly=I32 $s (Add $p 0x10);$gate=U8 $s (Add $p 0x14);$hit=U8 $s (Add $p 0x15);$visible=U8 $s (Add $p 0x18);$x=I32 $s (Add $p 0x20);$y=I32 $s (Add $p 0x24);$w=I32 $s (Add $p 0x2C);$h=I32 $s (Add $p 0x30);if($sel-ne0){$x+=$lx;$y+=$ly};$x+=$ox;$y+=$oy;[ordered]@{widgetPointer=Hex $p;status='READ';initialized=[int]$init;localSelector=[int]$sel;localGate=[int]$gate;hitTestEnabled=[int]$hit;activeVisible=[int]$visible;width=$w;height=$h;logicalRect=[ordered]@{left=$x;top=$y;right=$x+$w;bottom=$y+$h}}}
function Context($s,[uint32]$root){$nodes=@();$seen=@{};$p=$root;$x=0;$y=0;for($depth=0;$depth-lt16;$depth++){if($p-eq0){throw 'NULL_CONTEXT'};$key=Hex $p;if($seen.ContainsKey($key)){throw 'CONTEXT_CYCLE'};$seen[$key]=$true;$id=U32 $s $p;$active=U8 $s (Add $p 4);$parent=I32 $s (Add $p 8);$lx=I32 $s (Add $p 0xC);$ly=I32 $s (Add $p 0x10);$registry=U32 $s (Add $p 0x30);$nodes+=,[ordered]@{pointer=$key;id=[int]$id;active=[int]$active;parentId=$parent;localX=$lx;localY=$ly;registry=Hex $registry};$x+=$lx;$y+=$ly;if($parent-eq-1){return [ordered]@{nodes=$nodes;resolvedX=$x;resolvedY=$y;rootLocalX=$nodes[0].localX;rootLocalY=$nodes[0].localY}};if($parent-lt0-or$parent-gt0x72-or$parent-eq$id-or$registry-eq0){throw 'INVALID_PARENT_CHAIN'};$p=U32 $s (Add $registry ([uint32](4+4*$parent)))};throw 'CONTEXT_DEPTH_EXCEEDED'}
function Capture($s){[uint32]$m=0x00CA292C;$ui=U32 $s (Add $m 8);$cp=U32 $s (Add $m 0x24);$xp=U32 $s (Add $m 0x28);$layout=I32 $s (Add $m 0x37C);$terminal=I32 $s (Add $m 0xDE0);$cx=I32 $s (Add $m 0xDBC);$cy=I32 $s (Add $m 0xDC0);$sx=F32 $s 0x00772E2C;$sy=F32 $s 0x00772E30;$engine=U32 $s 0x007C1B4C;$er=[ordered]@{left=I32 $s (Add $engine 0x2A5FC);top=I32 $s (Add $engine 0x2A600);right=I32 $s (Add $engine 0x2A604);bottom=I32 $s (Add $engine 0x2A608)};$ctx=Context $s $ui;$confirm=Widget $s $cp $ctx.resolvedX $ctx.resolvedY;$cancel=Widget $s $xp $ctx.resolvedX $ctx.resolvedY;[ordered]@{manager=[ordered]@{base=Hex $m;uiContextPointer=Hex $ui;confirmPointer=Hex $cp;cancelPointer=Hex $xp;layout=$layout;terminalState=$terminal;cachedOrigin=[ordered]@{x=$cx;y=$cy};cachedOriginMatches=($cx-eq$ctx.rootLocalX-and$cy-eq$ctx.rootLocalY)};scaleX=$sx;scaleY=$sy;engineClientRect=$er;context=$ctx;confirm=$confirm;cancel=$cancel}}
try{$aSection=if($fixtureMode){$fixture.first}else{$null};$bSection=if($fixtureMode-and$fixture.second-is[string]){$fixture.first}elseif($fixtureMode){$fixture.second}else{$null};$a=Capture $aSection;$b=Capture $bSection;if(-not$fixtureMode){$p.Refresh();if(-not[TextDialogReadOnlyNative]::IsWindow($hwnd)-or$p.MainWindowHandle-ne$hwnd){throw 'Post-capture HWND invalid.'};[uint32]$owner2=0;[void][TextDialogReadOnlyNative]::GetWindowThreadProcessId($hwnd,[ref]$owner2);$rc2=New-Object TextDialogReadOnlyNative+RECT;if(-not[TextDialogReadOnlyNative]::GetClientRect($hwnd,[ref]$rc2)){throw 'Post-capture GetClientRect failed.'};$identity.secondHwndOwnerPid=$owner2;$identity.secondClientWidth=$rc2.Right-$rc2.Left;$identity.secondClientHeight=$rc2.Bottom-$rc2.Top};$stable=(($a|ConvertTo-Json -Depth 12 -Compress)-eq($b|ConvertTo-Json -Depth 12 -Compress));$surfaceStable=([int]$identity.hwndOwnerPid-eq[int]$identity.secondHwndOwnerPid-and[int]$identity.clientWidth-eq[int]$identity.secondClientWidth-and[int]$identity.clientHeight-eq[int]$identity.secondClientHeight);$block=@();if(([string]$identity.moduleBase)-ne'0x00400000'){$block+='MODULE_BASE_NOT_0X00400000'};if(-not$stable){$block+='TORN_SNAPSHOT'};if(-not$surfaceStable){$block+='OWNED_HWND_SURFACE_TORN'};if($a.engineClientRect.left-ne0-or$a.engineClientRect.top-ne0-or$a.engineClientRect.right-ne[int]$identity.clientWidth-or$a.engineClientRect.bottom-ne[int]$identity.clientHeight){$block+='ENGINE_RECT_HWND_MISMATCH'};if($a.manager.uiContextPointer-eq'0x00000000'){$block+='TEXT_DIALOG_UI_CONTEXT_NULL'};if($a.manager.layout-ne4){$block+='TEXT_DIALOG_LAYOUT_NOT_4'};if($a.manager.terminalState-notin@(1,2)){$block+='TERMINAL_STATE_NOT_WAITING_1_OR_2'};if(-not$a.manager.cachedOriginMatches){$block+='MANAGER_CACHED_ORIGIN_MISMATCH'};if($a.context.nodes[0].active-eq0){$block+='UI_CONTEXT_INACTIVE'};foreach($name in @('confirm','cancel')){$w=$a.$name;$up=$name.ToUpper();if($w.status-eq'NULL'){$block+="${up}_WIDGET_POINTER_NULL";continue};if($w.width-le0-or$w.height-le0){$block+="${up}_INVALID_SIZE"};if($w.localSelector-ne0-and$w.localGate-eq0){$block+="${up}_LOCAL_TRANSFORM_GATE_INVALID"};if($w.initialized-eq0-or$w.hitTestEnabled-eq0-or$w.activeVisible-eq0){$block+="${up}_WIDGET_NOT_INPUT_ELIGIBLE"}};if(-not[float]::IsFinite([single]$a.scaleX)-or-not[float]::IsFinite([single]$a.scaleY)-or$a.scaleX-le0-or$a.scaleY-le0){$block+='INVALID_SCALE'}
 $out=[ordered]@{schemaVersion=2;provenance=if($fixtureMode){'SYNTHETIC_FIXTURE'}else{'LIVE_READONLY'};process=$identity;manager=$a.manager;coordinateFrame=[ordered]@{status='STATICALLY_BOUND';logicalOrigin=[ordered]@{x=$a.context.resolvedX;y=$a.context.resolvedY};contextChain=$a.context.nodes;scaleX=$a.scaleX;scaleY=$a.scaleY;engineClientRect=$a.engineClientRect};confirm=$a.confirm;cancel=$a.cancel;snapshotStable=$stable;windowSurfaceStable=$surfaceStable;stateEligible=(@($block).Count-eq0);blockers=@($block);permitIssued=$false;operations=[ordered]@{memoryReads='READ_ONLY';memoryReadCount=$script:reads;writes=0;gameInputs=0;breakpointsInstalled=0}};$dir=Split-Path $OutputPath;if($dir-and-not(Test-Path $dir)){New-Item -ItemType Directory $dir|Out-Null};$out|ConvertTo-Json -Depth 15|Set-Content $OutputPath -Encoding UTF8
}finally{if($handle-ne[IntPtr]::Zero){[void][TextDialogReadOnlyNative]::CloseHandle($handle)}}
