[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$CapturePath,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop';$c=Get-Content $CapturePath -Raw -Encoding UTF8|ConvertFrom-Json;$block=@();$reason=$null
if($c.provenance-eq'LIVE_READONLY'){$reason='LIVE_SNAPSHOT_INDEPENDENT_BINDING_REQUIRED'}
if(-not$c.stateEligible){$block+='CAPTURE_NOT_ELIGIBLE'}
$sx=[single]$c.coordinateFrame.scaleX;$sy=[single]$c.coordinateFrame.scaleY;if(-not[float]::IsFinite($sx)-or-not[float]::IsFinite($sy)-or$sx-le0-or$sy-le0){$block+='INVALID_SCALE'}
function Trunc([double]$v){[int][Math]::Truncate($v)}
function Axis($lo,$hi,$scale,$limit){$inside=@();for($p=0;$p-lt$limit;$p++){ $v=Trunc($p*$scale);if($v-ge$lo-and$v-lt$hi){$inside+=$p}};if($inside.Count-eq0){return $null};[ordered]@{first=$inside[0];lastExclusive=$inside[-1]+1}}
function ResolveWidget($name,$w){$x=Axis $w.logicalRect.left $w.logicalRect.right $sx $c.process.clientWidth;$y=Axis $w.logicalRect.top $w.logicalRect.bottom $sy $c.process.clientHeight;if($null-eq$x-or$null-eq$y){$script:block+="${name}_NO_CLIENT_PIXELS";return $null};if(($x.lastExclusive-$x.first)-lt3-or($y.lastExclusive-$y.first)-lt3){$script:block+="${name}_NO_3X3_SAFE_MARGIN";return [ordered]@{clientRect=[ordered]@{left=$x.first;top=$y.first;right=$x.lastExclusive;bottom=$y.lastExclusive}}};$px=[int][Math]::Floor(($x.first+$x.lastExclusive-1)/2);$py=[int][Math]::Floor(($y.first+$y.lastExclusive-1)/2);for($xx=$px-1;$xx-le$px+1;$xx++){for($yy=$py-1;$yy-le$py+1;$yy++){$lx=Trunc($xx*$sx);$ly=Trunc($yy*$sy);if($lx-lt$w.logicalRect.left-or$lx-ge$w.logicalRect.right-or$ly-lt$w.logicalRect.top-or$ly-ge$w.logicalRect.bottom){$script:block+="${name}_SAFE_MARGIN_REPLAY_FAILED"}}};[ordered]@{logicalRect=$w.logicalRect;clientRect=[ordered]@{left=$x.first;top=$y.first;right=$x.lastExclusive;bottom=$y.lastExclusive};safePoint=[ordered]@{x=$px;y=$py;forwardLogical=[ordered]@{x=Trunc($px*$sx);y=Trunc($py*$sy)}}}}
$confirm=if($block.Count-eq0){ResolveWidget 'CONFIRM' $c.confirm}else{$null};$cancel=if($block.Count-eq0){ResolveWidget 'CANCEL' $c.cancel}else{$null};$status=if($reason-or$block.Count){'UNBOUND'}else{'OFFLINE_RESOLVED'};$out=[ordered]@{schemaVersion=1;status=$status;reason=$reason;sourceProvenance=$c.provenance;originalRuntimeObserved=$false;confirm=$confirm;cancel=$cancel;blockers=@($block);operations=[ordered]@{writes=0;gameInputs=0}};$dir=Split-Path $OutputPath;if($dir-and-not(Test-Path $dir)){New-Item -ItemType Directory $dir|Out-Null};$out|ConvertTo-Json -Depth 12|Set-Content $OutputPath -Encoding UTF8
