$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot;$collector=Join-Path $root 'src/collect-manager67-current-card.ps1';$fixture=Join-Path $PSScriptRoot 'fixture-ready.json';$identity=Join-Path $PSScriptRoot 'fixture-identity.json'
$temp=Join-Path ([IO.Path]::GetTempPath()) ('manager67-collector-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null;$script:n=0
function Eq($name,$actual,$expected){$script:n++;if($actual-ne$expected){throw "$name expected=$expected actual=$actual"}}
function Variant($name,[scriptblock]$change){$f=Get-Content $fixture -Raw|ConvertFrom-Json;$f.second=$f.first|ConvertTo-Json -Depth 12|ConvertFrom-Json;&$change $f;$p=Join-Path $temp "$name.json";$f|ConvertTo-Json -Depth 15|Set-Content $p;$p}
function Run($memory,$name){$p=Join-Path $temp "$name-out.json";$null=&$collector -FixtureMemoryPath $memory -FixtureIdentityPath $identity -OutputPath $p;Get-Content $p -Raw|ConvertFrom-Json}
function RunIdentityVariant($name,[scriptblock]$change){$i=Get-Content $identity -Raw|ConvertFrom-Json;&$change $i;$ip=Join-Path $temp "$name-identity.json";$i|ConvertTo-Json|Set-Content $ip;$p=Join-Path $temp "$name-out.json";$null=&$collector -FixtureMemoryPath $fixture -FixtureIdentityPath $ip -OutputPath $p;Get-Content $p -Raw|ConvertFrom-Json}
try{
 $r=Run $fixture ready
 Eq 'eligible' $r.stateEligible $true;Eq 'root' $r.strategyRoot.pointer '0x00C9E638';Eq 'controller' $r.manager67.controllerPointer '0x00C9EAC4';Eq 'manager id' $r.manager67.managerId 103;Eq 'count' $r.manager67.cardCount 3;Eq 'pending reset' $r.manager67.pendingHitIndex -1;Eq 'bound id' $r.manager65.boundAuthorityCardId 200;Eq 'reconciled index' $r.selectedAuthorityCard.index 1;Eq 'reconciled card' $r.selectedAuthorityCard.cardId 200;Eq 'semantic caveat' $r.selectedAuthorityCard.semantic 'AUTHORITY_CARD_WITH_WARP_ACTION_NOT_PROVEN_CAPTAIN_PORTRAIT';Eq 'active surface' $r.selectedAuthorityCard.activeSurface.surface 'C';Eq 'surface count' @($r.selectedAuthorityCard.surfaces).Count 2;Eq 'surface C left' $r.selectedAuthorityCard.activeSurface.logicalRect.left 310;Eq 'surface C top' $r.selectedAuthorityCard.activeSurface.logicalRect.top 225;Eq 'reads' $r.operations.memoryReadCount 238;Eq 'stable' $r.snapshotStable $true;Eq 'registry match' $r.manager67.registrySlotMatches $true;Eq 'data count match' $r.manager67.dataOwnerCountMatches $true;Eq 'current record match' $r.manager67.currentRecordSourceMatches $true;Eq 'writes' $r.operations.writes 0;Eq 'inputs' $r.operations.gameInputs 0
 $p=Variant duplicate {param($f)foreach($s in @($f.first,$f.second)){$s.u16.'0x03000284'=200}};$r=Run $p duplicate;Eq 'duplicate blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NOT_UNIQUE_IN_CURRENT_MANAGER67_LIST') $true
 $p=Variant inactive {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x02002018'=0;$s.u8.'0x02002118'=0}};$r=Run $p inactive;Eq 'inactive blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant uninitialized {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x02002008'=0}};$r=Run $p uninitialized;Eq 'initialized gate blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant localgate {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x02002014'=0}};$r=Run $p localgate;Eq 'conditional local gate blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant hitgate {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x02002015'=0}};$r=Run $p hitgate;Eq 'hit gate blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant width {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x0200202C'=0}};$r=Run $p width;Eq 'nonpositive width blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant height {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x02002030'=-1}};$r=Run $p height;Eq 'nonpositive height blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant managergate {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x02000005'=0}};$r=Run $p managergate;Eq 'manager input gate blocked' (@($r.blockers)-contains'MANAGER67_CONTEXT_INACTIVE') $true
 $p=Variant opposite {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x02002115'=1;$s.u8.'0x02002118'=1;$s.u8.'0x0200211B'=1}};$r=Run $p opposite;Eq 'opposite page surface blocked' (@($r.blockers)-contains'MANAGER67_PAGE_SURFACE_GATE_MISMATCH') $true
 $p=Variant nullsurface {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x00C9EB50'=0}};$r=Run $p nullsurface;Eq 'null selected surface blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant invalidpage {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9F0E0'=4}};$r=Run $p invalidpage;Eq 'invalid page blocked' (@($r.blockers)-contains'MANAGER67_PAGE_NOT_2_OR_3') $true
 $p=Variant torn {param($f)$f.second.u16.'0x0300027C'=201};$r=Run $p torn;Eq 'torn blocked' (@($r.blockers)-contains'TORN_SNAPSHOT') $true
 $p=Variant managerid {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x02000000'=102}};$r=Run $p managerid;Eq 'manager id blocked' (@($r.blockers)-contains'MANAGER67_ID_MISMATCH') $true
 $p=Variant count {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9F0E4'=0}};$r=Run $p count;Eq 'count blocked' (@($r.blockers)-contains'MANAGER67_CARD_COUNT_OUT_OF_RANGE') $true
 $p=Variant datacount {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x03000270'=2}};$r=Run $p datacount;Eq 'data count blocked' (@($r.blockers)-contains'MANAGER67_DATA_OWNER_COUNT_MISMATCH') $true
 $p=Variant registry {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x060001A0'=33558528}};$r=Run $p registry;Eq 'registry blocked' (@($r.blockers)-contains'MANAGER67_REGISTRY_SLOT_MISMATCH') $true
 $p=Variant recordsource {param($f)foreach($s in @($f.first,$f.second)){$s.u32.'0x07000008'=50331904}};$r=Run $p recordsource;Eq 'record source blocked' (@($r.blockers)-contains'MANAGER67_CURRENT_RECORD_SOURCE_MISMATCH') $true
 $p=Variant rendergate {param($f)foreach($s in @($f.first,$f.second)){$s.u8.'0x0200201B'=0;$s.u8.'0x0200211B'=0}};$r=Run $p rendergate;Eq 'render gate blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NO_ELIGIBLE_SURFACE') $true
 $p=Variant page3 {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9F0E0'=3;$s.u8.'0x02002015'=0;$s.u8.'0x02002018'=0;$s.u8.'0x0200201B'=0;$s.u8.'0x02002115'=1;$s.u8.'0x02002118'=1;$s.u8.'0x0200211B'=1}};$r=Run $p page3;Eq 'page3 eligible' $r.stateEligible $true;Eq 'page3 active D' $r.selectedAuthorityCard.activeSurface.surface 'D'
 $p=Variant noWarp {param($f)foreach($s in @($f.first,$f.second)){$s.u16.'0x07344DA8'=16}};$r=Run $p noWarp;Eq 'no warp blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_MISSING_WARP_ACTION_0X2B') $true
 $p=Variant missingBound {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9EAC0'=201}};$r=Run $p missingBound;Eq 'bound id missing blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_NOT_IN_CURRENT_MANAGER67_LIST') $true
 $p=Variant parent {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x02000008'=2;$s.u32|Add-Member -NotePropertyName '0x0500000C' -NotePropertyValue 33570816;$s.u32|Add-Member -NotePropertyName '0x02004000' -NotePropertyValue 2;$s.u8|Add-Member -NotePropertyName '0x02004004' -NotePropertyValue 1;$s.i32|Add-Member -NotePropertyName '0x02004008' -NotePropertyValue -1;$s.i32|Add-Member -NotePropertyName '0x0200400C' -NotePropertyValue 50;$s.i32|Add-Member -NotePropertyName '0x02004010' -NotePropertyValue 60;$s.u32|Add-Member -NotePropertyName '0x02004030' -NotePropertyValue 83886080}};$r=Run $p parent;Eq 'parent origin x' $r.coordinateFrame.logicalOrigin.x 150;Eq 'parent origin y' $r.coordinateFrame.logicalOrigin.y 180;Eq 'parent reads' $r.operations.memoryReadCount 252
 $p=Variant cycle {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x02000008'=103}};$threw=$false;try{$null=Run $p cycle}catch{$threw=$_.Exception.Message-like'*INVALID_PARENT_CHAIN*'};Eq 'context self cycle rejected' $threw $true
 $r=RunIdentityVariant module {param($i)$i.moduleBase='0x00500000'};Eq 'module blocker' (@($r.blockers)-contains'MODULE_BASE_NOT_0X00400000') $true
 $r=RunIdentityVariant hash {param($i)$i.sha256=('0'*64)};Eq 'actual identity hash blocker' (@($r.blockers)-contains'EXECUTABLE_HASH_MISMATCH') $true
 $r=RunIdentityVariant owner {param($i)$i.hwndOwnerPid=4243};Eq 'initial HWND owner blocker' (@($r.blockers)-contains'OWNED_HWND_PID_MISMATCH') $true
 $r=RunIdentityVariant owner2 {param($i)$i.secondHwndOwnerPid=4243};Eq 'second HWND owner blocker' (@($r.blockers)-contains'OWNED_HWND_PID_MISMATCH') $true
 $r=RunIdentityVariant surface {param($i)$i.secondClientWidth=801};Eq 'surface blocker' (@($r.blockers)-contains'OWNED_HWND_SURFACE_TORN') $true
 $r=RunIdentityVariant zerosurface {param($i)$i.clientWidth=0};Eq 'nonpositive surface blocker' (@($r.blockers)-contains'NONPOSITIVE_CLIENT_SURFACE') $true
 $p=Variant engine {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x0402A604'=801}};$r=Run $p engine;Eq 'engine blocker' (@($r.blockers)-contains'ENGINE_RECT_HWND_MISMATCH') $true
 $p=Variant pending {param($f)foreach($s in @($f.first,$f.second)){$s.i32.'0x00C9F0E8'=1}};$r=Run $p pending;Eq 'pending blocker' (@($r.blockers)-contains'MANAGER67_PENDING_HIT_NOT_RESET') $true
 $p=Variant scale {param($f)foreach($s in @($f.first,$f.second)){$s.f32.'0x00772E2C'=1.0}};$r=Run $p scale;Eq 'scale blocker' (@($r.blockers)-contains'SCALE_LOGICAL_SURFACE_MISMATCH') $true
 $p=Variant zeroscale {param($f)foreach($s in @($f.first,$f.second)){$s.f32.'0x00772E2C'=0}};$r=Run $p zeroscale;Eq 'zero scale blocker' (@($r.blockers)-contains'INVALID_SCALE') $true
 $p=Variant nanscale {param($f)foreach($s in @($f.first,$f.second)){$s.f32.'0x00772E2C'='NaN'}};$r=Run $p nanscale;Eq 'NaN scale blocker' (@($r.blockers)-contains'INVALID_SCALE') $true
 $rejected=$false;try{&$collector -TargetProcessId 2147483647 -ExpectedStartTimeUtc '2000-01-01Z' -ExpectedExecutableSha256 ('0'*64) -ExpectedWindowHandle 0x1 -OutputPath (Join-Path $temp bad.json)}catch{$rejected=$_.Exception.Message-like'*canonical*'};Eq 'noncanonical rejected before lookup' $rejected $true
 [ordered]@{result='PASS';cases=36;assertions=$script:n}|ConvertTo-Json
}finally{if(Test-Path $temp){$resolved=(Resolve-Path $temp).Path;$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if(-not$resolved.StartsWith($base,[StringComparison]::OrdinalIgnoreCase)){throw'unsafe cleanup'};Remove-Item $resolved -Recurse -Force}}
