$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot;$collector=Join-Path $root 'src/collect-manager67-current-card.ps1';$resolver=Join-Path $root 'src/resolve-manager67-current-card.ps1';$fixture=Join-Path $PSScriptRoot 'fixture-ready.json';$identity=Join-Path $PSScriptRoot 'fixture-identity.json'
$temp=Join-Path ([IO.Path]::GetTempPath()) ('manager67-resolver-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null;$script:n=0
function Eq($name,$actual,$expected){$script:n++;if($actual-ne$expected){throw "$name expected=$expected actual=$actual"}}
function Resolve($capture,$name){$p=Join-Path $temp "$name.json";$null=&$resolver -CapturePath $capture -OutputPath $p;Get-Content $p -Raw|ConvertFrom-Json}
try{
 $capture=Join-Path $temp capture.json;$null=&$collector -FixtureMemoryPath $fixture -FixtureIdentityPath $identity -OutputPath $capture;$r=Resolve $capture ready
 Eq 'status' $r.status 'OFFLINE_RESOLVED';Eq 'region count' @($r.selectedAuthorityCard.regions).Count 1;Eq 'C left' $r.selectedAuthorityCard.regions[0].clientRect.left 248;Eq 'C right' $r.selectedAuthorityCard.regions[0].clientRect.right 344;Eq 'C top' $r.selectedAuthorityCard.regions[0].clientRect.top 150;Eq 'C bottom' $r.selectedAuthorityCard.regions[0].clientRect.bottom 190;Eq 'C safe x' $r.selectedAuthorityCard.regions[0].safePoint.x 295;Eq 'C safe y' $r.selectedAuthorityCard.regions[0].safePoint.y 169;Eq 'C forward x' $r.selectedAuthorityCard.regions[0].safePoint.forwardLogical.x 368;Eq 'semantic caveat' $r.selectedAuthorityCard.semantic 'AUTHORITY_CARD_WITH_WARP_ACTION_NOT_PROVEN_CAPTAIN_PORTRAIT';Eq 'no auto point' $r.automaticActivationPoint $null;Eq 'runtime unseen' $r.originalRuntimeObserved $false
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.provenance='LIVE_READONLY';$p=Join-Path $temp live.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$r=Resolve $p live;Eq 'live self claim unbound' $r.status 'UNBOUND';Eq 'live reason' $r.reason 'LIVE_SNAPSHOT_INDEPENDENT_BINDING_REQUIRED';Eq 'live self claim emits no region' @($r.selectedAuthorityCard.regions).Count 0
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.stateEligible=$false;$j.blockers=@('TEST');$p=Join-Path $temp ineligible.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$r=Resolve $p ineligible;Eq 'ineligible unbound' $r.status 'UNBOUND'
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.coordinateFrame.scaleX=0;$p=Join-Path $temp zero.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$r=Resolve $p zero;Eq 'zero scale blocked' (@($r.blockers)-contains'INVALID_SCALE') $true
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.selectedAuthorityCard.activeSurface.logicalRect.left=10000;$j.selectedAuthorityCard.activeSurface.logicalRect.right=10001;$p=Join-Path $temp nopixels.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$r=Resolve $p nopixels;Eq 'no client pixels blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_SURFACE_NO_CLIENT_PIXELS') $true
 $j=Get-Content $capture -Raw|ConvertFrom-Json;$j.selectedAuthorityCard.activeSurface.logicalRect.left=1;$j.selectedAuthorityCard.activeSurface.logicalRect.right=2;$j.selectedAuthorityCard.activeSurface.logicalRect.top=1;$j.selectedAuthorityCard.activeSurface.logicalRect.bottom=2;$p=Join-Path $temp tiny.json;$j|ConvertTo-Json -Depth 15|Set-Content $p;$r=Resolve $p tiny;Eq 'tiny region blocked' (@($r.blockers)-contains'BOUND_AUTHORITY_CARD_SURFACE_NO_3X3_SAFE_MARGIN') $true
 [ordered]@{result='PASS';cases=6;assertions=$script:n}|ConvertTo-Json
}finally{if(Test-Path $temp){$resolved=(Resolve-Path $temp).Path;$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());if(-not$resolved.StartsWith($base,[StringComparison]::OrdinalIgnoreCase)){throw'unsafe cleanup'};Remove-Item $resolved -Recurse -Force}}
