param(
 [Parameter(Mandatory=$true)][string]$ReceiptPath,
 [Parameter(Mandatory=$true)][string]$OutputPath,
 [Parameter(Mandatory=$true)][string]$RunId,
 [Parameter(Mandatory=$true)][string]$InteractiveCollectorPath,
 [datetime]$EvaluationTimeUtc=[datetime]::UtcNow,
 [string]$BindingPath
)
$ErrorActionPreference='Stop'

function Write-CanonicalJson([object]$Value,[string]$Path){$json=($Value|ConvertTo-Json -Depth 16)-replace"`r`n","`n";[IO.File]::WriteAllText($Path,$json+"`n",[Text.UTF8Encoding]::new($false))}
function Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Hex64($Value){[string]$Value-match'^[0-9A-Fa-f]{64}$'}
function NonZeroAddress($Value){$text=[string]$Value;return($text-match'^0x[0-9A-Fa-f]{8,16}$'-and$text-notmatch'^0x0+$')}
function ExactKeys($Value,[string[]]$Expected){if($null-eq$Value){return$false};$a=@($Value.PSObject.Properties.Name|Sort-Object);$e=@($Expected|Sort-Object);return($a.Count-eq$e.Count-and(Compare-Object $e $a).Count-eq0)}
$blockers=[Collections.Generic.List[string]]::new();function Block([string]$Code){if(-not$blockers.Contains($Code)){$blockers.Add($Code)}}

try{$r=Get-Content -LiteralPath $ReceiptPath -Raw -Encoding UTF8|ConvertFrom-Json}catch{$r=$null;Block 'RECEIPT_JSON_INVALID'}
$client=$null;$debugger=$null;$agent=$null
if($null-ne$r){
 $root=@('schemaVersion','runId','provenance','observedAtUtc','helper','activeConsoleSessionId','absoluteProgram','processes','operations')
 if(-not(ExactKeys $r $root)){Block 'SCHEMA_ROOT_KEYS_MISMATCH'}
 if([int]$r.schemaVersion-ne1){Block 'SCHEMA_VERSION_UNSUPPORTED'}
 if([string]$r.runId-cne$RunId){Block 'RECEIPT_RUN_ID_MISMATCH'}
 if($r.provenance-notin@('SYNTHETIC_FIXTURE','LIVE_READONLY_CORRECTED_ROUTE_PREFLIGHT')){Block 'PROVENANCE_INVALID'}
 try{$observed=[datetime]$r.observedAtUtc}catch{$observed=[datetime]::MinValue;Block 'OBSERVED_TIME_INVALID'}
 if(-not(ExactKeys $r.helper @('pid','sessionId','userName','userSid'))){Block 'SCHEMA_HELPER_KEYS_MISMATCH'}
 if(-not(ExactKeys $r.absoluteProgram @('path','exists','sha256','length','observedAtUtc'))){Block 'SCHEMA_PROGRAM_KEYS_MISMATCH'}
 if([string]::IsNullOrWhiteSpace([string]$r.helper.userName)-or[string]$r.helper.userSid-notmatch'^S-\d-\d+(-\d+)+$'){Block 'OWNER_IDENTITY_INVALID'}
 if([int]$r.helper.sessionId-ne0){Block 'PREFLIGHT_HELPER_SESSION_NOT_0'}
 if([int]$r.activeConsoleSessionId-ne1){Block 'ACTIVE_CONSOLE_INVALID'}
 $expectedProgram='C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
 if([string]$r.absoluteProgram.path-cne$expectedProgram){Block 'ABSOLUTE_PROGRAM_PATH_MISMATCH'}
 if($r.absoluteProgram.exists-ne$true){Block 'ABSOLUTE_PROGRAM_MISSING'}
 if(-not(Hex64 $r.absoluteProgram.sha256)-or[int64]$r.absoluteProgram.length-le0){Block 'ABSOLUTE_PROGRAM_IDENTITY_INVALID'}
 try{$programObserved=[datetime]$r.absoluteProgram.observedAtUtc}catch{$programObserved=[datetime]::MinValue;Block 'ABSOLUTE_PROGRAM_IDENTITY_INVALID'}
 if($observed-ne[datetime]::MinValue-and(($EvaluationTimeUtc.ToUniversalTime()-$observed.ToUniversalTime()).TotalSeconds-gt120-or$observed.ToUniversalTime()-gt$EvaluationTimeUtc.ToUniversalTime())){Block 'PREFLIGHT_STALE'}
 if($programObserved-ne[datetime]::MinValue-and(($EvaluationTimeUtc.ToUniversalTime()-$programObserved.ToUniversalTime()).TotalSeconds-gt120-or$programObserved.ToUniversalTime()-gt$EvaluationTimeUtc.ToUniversalTime())){Block 'PREFLIGHT_STALE'}
 $processKeys=@('role','name','pid','sessionId','startTimeUtc','path','sha256','owner','ownerSid','ownerLookupStatus','moduleBase','moduleSize')
 $p=@($r.processes);foreach($process in $p){if(-not(ExactKeys $process $processKeys)){Block 'SCHEMA_PROCESS_KEYS_MISMATCH'}};$cs=@($p|Where-Object{$_.role-eq'CLIENT'});$ds=@($p|Where-Object{$_.role-eq'DEBUGGER'});$as=@($p|Where-Object{$_.role-eq'INTERACTIVE_AGENT'})
 if($cs.Count-ne1){Block 'CLIENT_COUNT_NOT_1'}else{$client=$cs[0]}
 if($ds.Count-ne1){Block 'DEBUGGER_COUNT_NOT_1'}else{$debugger=$ds[0]}
 if($as.Count-ne1){Block 'INTERACTIVE_AGENT_COUNT_NOT_1'}else{$agent=$as[0]}
 $positivePids=@($p|Where-Object{[int]$_.pid-gt0}|ForEach-Object{[int]$_.pid});if(($positivePids|Sort-Object -Unique).Count-ne$positivePids.Count){Block 'PROCESS_PID_COLLISION'}
 $active=[int]$r.activeConsoleSessionId;$ownerName=[string]$r.helper.userName;$ownerSid=[string]$r.helper.userSid
 if($client){if([int]$client.pid-le0){Block 'CLIENT_IDENTITY_INVALID'};if([string]$client.name-cne'G7MTClient'){Block 'CLIENT_NAME_MISMATCH'};if([string]$client.path-cne'C:\LOGH7_ORACLE\exe\G7MTClient.exe'){Block 'CLIENT_PATH_MISMATCH'};if([string]$client.sha256-cne'BD19263C10DECC3D58373165A82D42A9267868400D407DA87D5F4F4109AB6E16'){Block 'CLIENT_HASH_MISMATCH'};if([int]$client.sessionId-ne$active){Block 'CLIENT_SESSION_MISMATCH'};if([string]$client.ownerLookupStatus-cne'SUCCESS'){Block 'CLIENT_OWNER_LOOKUP_FAILED'};if([string]$client.owner-cne$ownerName){Block 'CLIENT_OWNER_MISMATCH'};if([string]$client.ownerSid-cne$ownerSid){Block 'CLIENT_OWNER_SID_MISMATCH'};if([int64]$client.moduleSize-le0-or-not(NonZeroAddress $client.moduleBase)){Block 'CLIENT_MODULE_IDENTITY_INVALID'};try{$clientStart=[datetime]$client.startTimeUtc;if($clientStart.ToUniversalTime()-gt$observed.ToUniversalTime()){throw'future'}}catch{Block 'CLIENT_START_TIME_INVALID'}}
 if($debugger){if([int]$debugger.pid-le0){Block 'DEBUGGER_IDENTITY_INVALID'};if([string]$debugger.name-cne'x32dbg'){Block 'DEBUGGER_NAME_MISMATCH'};if([string]$debugger.path-cne'C:\LOGH7_TOOLS\x64dbg-xp-2020-12-14\release\x32\x32dbg.exe'){Block 'DEBUGGER_PATH_MISMATCH'};if([string]$debugger.sha256-cne'42CF419B3549332AF44A8500E99085A0C590547CAE6950623FE592EA885711C6'){Block 'DEBUGGER_HASH_MISMATCH'};if([int]$debugger.sessionId-ne$active){Block 'DEBUGGER_SESSION_MISMATCH'};if([string]$debugger.ownerLookupStatus-cne'SUCCESS'){Block 'DEBUGGER_OWNER_LOOKUP_FAILED'};if([string]$debugger.owner-cne$ownerName){Block 'DEBUGGER_OWNER_MISMATCH'};if([string]$debugger.ownerSid-cne$ownerSid){Block 'DEBUGGER_OWNER_SID_MISMATCH'};if([int64]$debugger.moduleSize-le0-or-not(NonZeroAddress $debugger.moduleBase)){Block 'DEBUGGER_MODULE_IDENTITY_INVALID'};try{$debuggerStart=[datetime]$debugger.startTimeUtc;if($debuggerStart.ToUniversalTime()-gt$observed.ToUniversalTime()){throw'future'}}catch{Block 'DEBUGGER_START_TIME_INVALID'}}
 if($agent){if([int]$agent.pid-le0){Block 'INTERACTIVE_AGENT_IDENTITY_INVALID'};if([string]$agent.name-cne'vmtoolsd'){Block 'INTERACTIVE_AGENT_NAME_MISMATCH'};if([string]$agent.path-cne'C:\Program Files\VMware\VMware Tools\vmtoolsd.exe'){Block 'INTERACTIVE_AGENT_PATH_MISMATCH'};if([int]$agent.sessionId-ne$active){Block 'INTERACTIVE_AGENT_SESSION_MISMATCH'};if([string]$agent.ownerLookupStatus-cne'SUCCESS'){Block 'INTERACTIVE_AGENT_OWNER_LOOKUP_FAILED'};if([string]$agent.owner-cne$ownerName){Block 'INTERACTIVE_AGENT_OWNER_MISMATCH'};if([string]$agent.ownerSid-cne$ownerSid){Block 'INTERACTIVE_AGENT_OWNER_SID_MISMATCH'};if(-not(Hex64 $agent.sha256)){Block 'INTERACTIVE_AGENT_HASH_INVALID'};if([int64]$agent.moduleSize-le0-or-not(NonZeroAddress $agent.moduleBase)){Block 'INTERACTIVE_AGENT_MODULE_IDENTITY_INVALID'};try{$agentStart=[datetime]$agent.startTimeUtc;if($agentStart.ToUniversalTime()-gt$observed.ToUniversalTime()){throw'future'}}catch{Block 'INTERACTIVE_AGENT_START_TIME_INVALID'}}
 $allowed=@{helperProcessesCreated=1;guestSourceCopies=1;guestFileWrites=1};foreach($k in $allowed.Keys){if([int]$r.operations.$k-ne$allowed[$k]){Block 'PREFLIGHT_OPERATION_ACCOUNTING_INVALID'}}
 $operationKeys=@('helperProcessesCreated','guestSourceCopies','guestFileWrites','processMemoryReads','processMemoryWrites','foregroundChanges','debuggerAttach','debuggerCommands','breakpointsInstalled','captures','gameInputs','automaticInputs','permitIssued','vmLifecycleChanges','serverChanges','protocolChanges','databaseChanges');if(-not(ExactKeys $r.operations $operationKeys)){Block 'SCHEMA_OPERATION_KEYS_MISMATCH'}
 foreach($k in @('processMemoryReads','processMemoryWrites','foregroundChanges','debuggerAttach','debuggerCommands','breakpointsInstalled','captures','gameInputs','automaticInputs','vmLifecycleChanges','serverChanges','protocolChanges','databaseChanges')){if([int]$r.operations.$k-ne0){Block 'FORBIDDEN_OPERATION_RECORDED'}}
 if($r.operations.permitIssued-ne$false){Block 'FORBIDDEN_OPERATION_RECORDED'}
}
if($RunId-notmatch'^[A-Za-z0-9][A-Za-z0-9._-]{7,63}$'){Block 'RUN_ID_INVALID'}
if(-not(Test-Path -LiteralPath $InteractiveCollectorPath)){Block 'INTERACTIVE_COLLECTOR_MISSING'}
$guestScript="C:\LOGH7_ORACLE\interactive-canary-$RunId.ps1";$guestStarted="C:\LOGH7_ORACLE\interactive-canary-$RunId-started.json";$guestRaw="C:\LOGH7_ORACLE\interactive-canary-$RunId-receipt.json";$guestDiag="C:\LOGH7_ORACLE\interactive-canary-$RunId-diagnostic.json"
$hostDir=Split-Path -Parent ([IO.Path]::GetFullPath($OutputPath));$hostStarted=Join-Path $hostDir "interactive-canary-$RunId-started.json";$hostRaw=Join-Path $hostDir "interactive-canary-$RunId-receipt.json";$hostDiag=Join-Path $hostDir "interactive-canary-$RunId-diagnostic.json"
$guestPaths=@($guestScript,$guestStarted,$guestRaw,$guestDiag);$hostPaths=@($hostStarted,$hostRaw,$hostDiag)

$bound=$false
if($null-ne$r-and$r.provenance-eq'LIVE_READONLY_CORRECTED_ROUTE_PREFLIGHT'){
 if([string]::IsNullOrWhiteSpace($BindingPath)-or-not(Test-Path -LiteralPath $BindingPath)){Block 'LIVE_BINDING_MISSING'}else{
  try{
   $b=Get-Content -LiteralPath $BindingPath -Raw|ConvertFrom-Json
   $keys=@('schemaVersion','runId','provenance','createdAtUtc','rawReceiptPath','rawReceiptSha256','preflightCollectorPath','preflightCollectorSha256','vmxPath','vmxSha256','programCopyReceiptPath','programCopyReceiptSha256','interactiveCollectorSourcePath','interactiveCollectorSourceSha256','interactiveCollectorSealedPath','interactiveCollectorSealedSha256','interactiveCollectorRoundTripPath','interactiveCollectorRoundTripSha256','preflightGuestScriptPath','programExecutable','argumentVector','interactivePaths','interactiveArgumentVector','historyLedgerPath','historyLedgerSha256','pathAbsenceReceiptPath','pathAbsenceReceiptSha256','guestSourceCopies','helperLaunchCalls','copyBackCalls','vmrunHostExitCode')
   if(-not(ExactKeys $b $keys)-or[int]$b.schemaVersion-ne1-or$b.provenance-cne'HOST_BOUND_CORRECTED_ROUTE_PREFLIGHT'){Block 'BINDING_SCHEMA_INVALID'}
   if([string]$b.runId-cne$RunId){Block 'BINDING_RUN_ID_MISMATCH'}
   if([IO.Path]::GetFullPath([string]$b.rawReceiptPath)-cne[IO.Path]::GetFullPath($ReceiptPath)-or$b.rawReceiptSha256-cne(Sha $ReceiptPath)){Block 'BINDING_RAW_HASH_MISMATCH'}
   if(-not(Test-Path $b.preflightCollectorPath)-or$b.preflightCollectorSha256-cne(Sha $b.preflightCollectorPath)){Block 'BINDING_COLLECTOR_HASH_MISMATCH'}
   if(-not(Test-Path $b.vmxPath)-or$b.vmxSha256-cne(Sha $b.vmxPath)){Block 'BINDING_VMX_HASH_MISMATCH'}
   try{$created=[datetime]$b.createdAtUtc}catch{$created=[datetime]::MinValue;Block 'BINDING_TIME_INVALID'}
   if($created-ne[datetime]::MinValue-and($created.ToUniversalTime()-lt$observed.ToUniversalTime()-or$created.ToUniversalTime()-gt$EvaluationTimeUtc.ToUniversalTime())){Block 'BINDING_TIME_INVALID'}
   if(-not(Test-Path $b.programCopyReceiptPath)-or$b.programCopyReceiptSha256-cne(Sha $b.programCopyReceiptPath)){Block 'BINDING_PROGRAM_COPY_RECEIPT_INVALID'}else{$programCopy=Get-Content $b.programCopyReceiptPath -Raw|ConvertFrom-Json;try{$copyTime=[datetime]$programCopy.copiedAtUtc}catch{$copyTime=[datetime]::MinValue};if(-not(ExactKeys $programCopy @('schemaVersion','provenance','runId','guestProgramPath','hostCopyPath','hostCopySha256','hostCopyLength','copyExitCode','copiedAtUtc'))-or[int]$programCopy.schemaVersion-ne1-or$programCopy.provenance-cne'HOST_GUEST_PROGRAM_COPY_RECEIPT'-or$programCopy.runId-cne$RunId-or$programCopy.guestProgramPath-cne'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'-or[int]$programCopy.copyExitCode-ne0-or-not(Test-Path $programCopy.hostCopyPath)-or$programCopy.hostCopySha256-cne(Sha $programCopy.hostCopyPath)-or[int64]$programCopy.hostCopyLength-ne(Get-Item $programCopy.hostCopyPath).Length-or$programCopy.hostCopySha256-cne[string]$r.absoluteProgram.sha256-or[int64]$programCopy.hostCopyLength-ne[int64]$r.absoluteProgram.length-or$copyTime.ToUniversalTime()-lt$observed.ToUniversalTime()-or$copyTime.ToUniversalTime()-gt$created.ToUniversalTime()){Block 'BINDING_PROGRAM_COPY_RECEIPT_INVALID'}}
   $sourceHash=if(Test-Path $b.interactiveCollectorSourcePath){Sha $b.interactiveCollectorSourcePath}else{$null};$sealedHash=if(Test-Path $b.interactiveCollectorSealedPath){Sha $b.interactiveCollectorSealedPath}else{$null};$roundHash=if(Test-Path $b.interactiveCollectorRoundTripPath){Sha $b.interactiveCollectorRoundTripPath}else{$null}
   if([IO.Path]::GetFullPath([string]$b.interactiveCollectorSourcePath)-cne[IO.Path]::GetFullPath($InteractiveCollectorPath)-or$b.interactiveCollectorSourceSha256-cne$sourceHash-or$b.interactiveCollectorSealedSha256-cne$sealedHash-or$b.interactiveCollectorRoundTripSha256-cne$roundHash-or$sourceHash-cne$sealedHash-or$sourceHash-cne$roundHash){Block 'BINDING_INTERACTIVE_COLLECTOR_DRIFT'}
   $preArgs=@('-NoProfile','-ExecutionPolicy','Bypass','-File',[string]$b.preflightGuestScriptPath,'-RunId',$RunId,'-OutputPath','C:\LOGH7_ORACLE\corrected-route-preflight.json')
   $actual=@($b.argumentVector);$argBad=$actual.Count-ne$preArgs.Count-or(Compare-Object $preArgs $actual -SyncWindow 0).Count-ne0
   if($b.programExecutable-cne'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'-or$argBad-or[int]$b.guestSourceCopies-ne1-or[int]$b.helperLaunchCalls-ne1-or[int]$b.copyBackCalls-ne1-or[int]$b.vmrunHostExitCode-ne0){Block 'BINDING_ROUTE_INVALID'}
   $pathKeys=@('guestCollector','guestStarted','guestRaw','guestDiagnostic','hostStarted','hostRaw','hostDiagnostic')
   if(-not(ExactKeys $b.interactivePaths $pathKeys)-or$b.interactivePaths.guestCollector-cne$guestScript-or$b.interactivePaths.guestStarted-cne$guestStarted-or$b.interactivePaths.guestRaw-cne$guestRaw-or$b.interactivePaths.guestDiagnostic-cne$guestDiag-or[IO.Path]::GetFullPath([string]$b.interactivePaths.hostStarted)-cne[IO.Path]::GetFullPath($hostStarted)-or[IO.Path]::GetFullPath([string]$b.interactivePaths.hostRaw)-cne[IO.Path]::GetFullPath($hostRaw)-or[IO.Path]::GetFullPath([string]$b.interactivePaths.hostDiagnostic)-cne[IO.Path]::GetFullPath($hostDiag)){Block 'BINDING_INTERACTIVE_PATHS_INVALID'}
   $expectedInteractiveArgs=@('-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$guestScript,'-RunId',$RunId,'-OutputPath',$guestRaw,'-StartedPath',$guestStarted,'-DiagnosticPath',$guestDiag);$actualInteractiveArgs=@($b.interactiveArgumentVector)
   if($actualInteractiveArgs.Count-ne$expectedInteractiveArgs.Count-or(Compare-Object $expectedInteractiveArgs $actualInteractiveArgs -SyncWindow 0).Count-ne0){Block 'BINDING_INTERACTIVE_ROUTE_INVALID'}
   if(-not(Test-Path $b.historyLedgerPath)-or$b.historyLedgerSha256-cne(Sha $b.historyLedgerPath)){Block 'BINDING_HISTORY_INVALID'}else{$history=Get-Content $b.historyLedgerPath -Raw|ConvertFrom-Json;$historical=@($history.historicalRuns);$knownV1Paths=@('C:\LOGH7_ORACLE\interactive-canary-20260829T183100Z-v1.ps1','C:\LOGH7_ORACLE\interactive-canary-20260829T183100Z-v1-started.json','C:\LOGH7_ORACLE\interactive-canary-20260829T183100Z-v1-receipt.json','C:\LOGH7_ORACLE\interactive-canary-20260829T183100Z-v1-diagnostic.json');if(-not(ExactKeys $history @('schemaVersion','provenance','historicalRuns'))-or[int]$history.schemaVersion-ne1-or$history.provenance-cne'IMMUTABLE_ATTEMPT_HISTORY'-or$historical.Count-ne1){Block 'BINDING_HISTORY_INVALID'}else{$past=$historical[0];$pastPaths=@($past.guestPaths);if(-not(ExactKeys $past @('runId','guestPaths'))-or[string]$past.runId-cne'20260829T183100Z-v1'-or$pastPaths.Count-ne$knownV1Paths.Count-or(Compare-Object $knownV1Paths $pastPaths -SyncWindow 0).Count-ne0){Block 'BINDING_HISTORY_INVALID'};if([string]$past.runId-ceq$RunId-or@($pastPaths|Where-Object{$guestPaths-contains$_}).Count-ne0){Block 'RUN_OR_PATH_REUSED'}}}
   if(-not(Test-Path $b.pathAbsenceReceiptPath)-or$b.pathAbsenceReceiptSha256-cne(Sha $b.pathAbsenceReceiptPath)){Block 'BINDING_PATH_ABSENCE_INVALID'}else{$absence=Get-Content $b.pathAbsenceReceiptPath -Raw|ConvertFrom-Json;try{$absenceTime=[datetime]$absence.observedAtUtc}catch{$absenceTime=[datetime]::MinValue};$absenceGuest=@($absence.guestPaths);$absenceHost=@($absence.hostPaths);if(-not(ExactKeys $absence @('schemaVersion','provenance','runId','observedAtUtc','guestPaths','hostPaths','allAbsent'))-or[int]$absence.schemaVersion-ne1-or$absence.provenance-cne'HOST_PATH_ABSENCE_RECEIPT'-or$absence.runId-cne$RunId-or$absence.allAbsent-ne$true-or(Compare-Object $guestPaths $absenceGuest -SyncWindow 0).Count-ne0-or(Compare-Object $hostPaths $absenceHost -SyncWindow 0).Count-ne0-or$absenceTime.ToUniversalTime()-lt$observed.ToUniversalTime()-or$absenceTime.ToUniversalTime()-gt$created.ToUniversalTime()){Block 'BINDING_PATH_ABSENCE_INVALID'}}
   $bound=@($blockers|Where-Object{$_-match'^BINDING_|^LIVE_BINDING_'}).Count-eq0
  }catch{Block 'BINDING_INVALID'}
 }
}

$guestPaths=@($guestScript,$guestStarted,$guestRaw,$guestDiag);if(($guestPaths|Sort-Object -Unique).Count-ne4-or@($guestPaths|Where-Object{$_-match'\.\.'}).Count-ne0){Block 'ROUTE_PATHS_INVALID'}
$route=[ordered]@{runId=$RunId;programExecutable='C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe';programSha256=if($r){[string]$r.absoluteProgram.sha256}else{$null};programLength=if($r){[int64]$r.absoluteProgram.length}else{0};interactiveCollectorPath=[IO.Path]::GetFullPath($InteractiveCollectorPath);interactiveCollectorSha256=if(Test-Path $InteractiveCollectorPath){Sha $InteractiveCollectorPath}else{$null};guestCollectorPath=$guestScript;guestStartedPath=$guestStarted;guestRawReceiptPath=$guestRaw;guestDiagnosticPath=$guestDiag;hostStartedPath=$hostStarted;hostRawReceiptPath=$hostRaw;hostDiagnosticPath=$hostDiag;argumentVector=@('-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$guestScript,'-RunId',$RunId,'-OutputPath',$guestRaw,'-StartedPath',$guestStarted,'-DiagnosticPath',$guestDiag);vmrunInteractive=$true;vmrunActiveWindow=$false;maxGuestSourceCopies=1;maxHelperLaunchCalls=1;maxCopyBackCalls=3;retryAllowed=$false}
$structural=@($blockers|Where-Object{$_-ne'EXECUTION_AUTHORITY_NOT_BOUND'}).Count-eq0;$prepared=$null-ne$r-and$r.provenance-eq'LIVE_READONLY_CORRECTED_ROUTE_PREFLIGHT'-and$bound-and$structural
if($prepared){Block 'EXECUTION_AUTHORITY_NOT_BOUND'}
$status=if($null-ne$r-and$r.provenance-eq'LIVE_READONLY_CORRECTED_ROUTE_PREFLIGHT'-and$blockers.Contains('LIVE_BINDING_MISSING')){'CLAIMED_LIVE_PREFLIGHT_UNBOUND'}elseif($prepared){'CORRECTED_ROUTE_LIVE_PREFLIGHT_STRUCTURALLY_READY_AUTHORITY_MISSING'}elseif($null-ne$r-and$r.provenance-eq'SYNTHETIC_FIXTURE'-and$blockers.Count-eq0){'STRUCTURALLY_READY_SYNTHETIC_PREFLIGHT_NOT_LIVE'}else{'CORRECTED_ROUTE_PREFLIGHT_REJECTED'}
$out=[ordered]@{schemaVersion=1;status=$status;routePreparedCandidateEligible=$prepared;routeLaunchCandidateEligible=$false;executionAuthorized=$false;prelaunchEligible=$false;independentReviewRequired=$true;route=$route;client=$client;debugger=$debugger;interactiveAgent=$agent;blockers=@($blockers)}
Write-CanonicalJson $out $OutputPath;$out|ConvertTo-Json -Depth 16
