<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetLockFilePath>$(MSBuildThisFileDirectory)..\..\..\packages.lock.json</NuGetLockFilePath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Logh7.Server\Logh7.Server.csproj" />
    <Content Include="..\..\..\tools\native-setup\select-test-return-base.sql" Link="select-test-return-base.sql" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
