[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ContractPath)
$ErrorActionPreference='Stop'
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$c=Get-Content -LiteralPath $ContractPath -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Eq($n,$a,$e){if($a-ne$e){$errors.Add("$n expected=$e actual=$a")}}
function Seq($n,$a,$e){$aa=if($null-eq$a){@()}else{@($a)};$ee=if($null-eq$e){@()}else{@($e)};if(($aa|ConvertTo-Json -Compress -Depth 30)-ne($ee|ConvertTo-Json -Compress -Depth 30)){$errors.Add("$n sequence mismatch")}}
function Load($p){Get-Content -LiteralPath $p -Raw -Encoding UTF8|ConvertFrom-Json}
$hashes=[ordered]@{
 receiptV2Schema='5CCFA54F81DE0100826137ED75EAD10E47180257AEA564FEB665D58AAD0E6ADE';receiptV2Template='63B2935A7B4B8B6FA2CD1874ECC4E6DE9294398C3759C36712F3793C42A3FE82';receiptV2Specimen='9A1D507EB6D6B9FDDE8429C70BD35D5549C033F355E1EC0520F9793DA7745AA1';receiptV2Verifier='A70EF5535A70686A9C979601FB4032B1B094BF1FA3DEE1DE9BD6A5F171ABC135';receiptV2Tests='8F9E0A8069EE4CD08BBB78E30141A8F02C6107BB66450234DFCD0E50ACA634AD';migrationMatrix='D8AE0F8BA1B2F915456D08C1313C3F30001000D6E9D114D06EFEBD5AEB73C603';debuggerSemantics='6DC0AAA072E06749A286C38F3232DD682945FAEEDC2CF7DD97D17FA798C935C8';jsonSchemaValidator='666D694E0A26BC5A2D3B80A6CFB41CCB91837FE4DB997A850CB5A944228983C3';priorV7Contract='5DEEDD1232E0C21AB4836FEA6A9AF3B190BE4BFE0B7E21A26E4C928A4C69E4AF';priorV7Verifier='29A4662C832A0BDAA04207FAE5ED1EE715AFCD9A5C77A8CE0584FAF7EE2198A4';priorV7Tests='9210593A23315CD3E8AD35D2BDD467B7FD1636C6FCC23D115E8E8A14798D94A0';priorV7FinalVerification='E6554004C96BC1F232D80773FA084C04BB583B906E57E20822E1B6B5255E6B8E';priorV7ArtifactLedger='1CBE49CF3ED2131387716B0645FFCEFA18018878C207EE0618861CF605C469CD'
}
$loaded=@{};$paths=@{}
foreach($name in $hashes.Keys){$e=$c.boundArtifacts.$name;if($null-eq$e){$errors.Add("missing artifact $name");continue};Eq "$name declared" ([string]$e.sha256).ToUpperInvariant() $hashes[$name];$p=Join-Path $repo ([string]$e.path);$paths[$name]=$p;if(-not(Test-Path -LiteralPath $p)){$errors.Add("missing file $name");continue};Eq "$name actual" (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash $hashes[$name];if([IO.Path]::GetExtension($p)-eq'.json'){$loaded[$name]=Load $p}}
Eq 'schema' $c.schemaVersion 8;Eq 'contract' $c.contract 'ORIGINAL_CLIENT_FIRST_SERVER_BACKED_PLAY_PRELAUNCH_V8_MOVEMENT_RECEIPT_V2_INTEGRATED';Eq 'state' $c.state 'OFFLINE_PRELAUNCH_MOVEMENT_RECEIPT_V2_INTEGRATED_RUNTIME_INSTALL_MISSING_READY_FALSE';Eq 'run' $c.oracleRunId $null;Eq 'launch' $c.launchEligible $false;Eq 'permit eligible' $c.permitEligible $false;Eq 'permit' $c.permitIssued $false
Eq 'authority source' $c.currentAuthority.source 'USER_APPROVED_CURRENT_THREAD';Eq 'authority scope' $c.currentAuthority.scope 'ONE_LIVE_ORACLE_ONE_PHYSICAL_ACTIVATION_READ_ONLY_CAPTURE';Eq 'activation budget' $c.currentAuthority.activationBudget 1;Eq 'bypass' $c.currentAuthority.doesNotBypassPrelaunchGates $true;Eq 'prior id' $c.priorPermit.id 'permit-live-v3-20260827-d89449bc2c3c4b70a9854833b2214012-once';Eq 'prior state' $c.priorPermit.state 'CONSUMED_NO_RETRY';Eq 'prior reuse' $c.priorPermit.reusable $false
$resolved=@('MOVEMENT_RECEIPT_TEMPORAL_THREAD_CORRELATION_SCHEMA_MISSING');$introduced=@('FRESH_MOVEMENT_BREAKPOINT_INSTALL_AND_PER_THREAD_TEMPORAL_RECEIPT_MISSING');Seq 'resolved' $c.integrationDelta.resolvedStaticBlockers $resolved;Seq 'introduced' $c.integrationDelta.introducedRuntimeBlockers $introduced;Eq 'prior count' $c.integrationDelta.priorBlockerCount 12;Eq 'current count' $c.integrationDelta.currentBlockerCount 12
$expected=@('ACTIVATION_BUDGET_STAGE_CONTRACT_MISMATCH','FRESH_RUN_IDENTITY_MISSING','FRESH_MOVEMENT_BREAKPOINT_INSTALL_AND_PER_THREAD_TEMPORAL_RECEIPT_MISSING','FRESH_MANAGER67_AUTHORITY_CARD_SNAPSHOT_MISSING','MANAGER67_AUTHORITY_CARD_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_MANAGER65_SNAPSHOT_MISSING','MANAGER65_ACTION_0X2B_HIT_REGION_INDEPENDENT_BINDING_MISSING','FRESH_WARP_STAGE_OWNER_SNAPSHOT_MISSING','FRESH_DESTINATION_PROJECTION_SNAPSHOT_MISSING','FRESH_TEXTDIALOG_SNAPSHOT_MISSING','FOREGROUND_PROBE_NOT_RUN','INDEPENDENT_LIVE_PRELAUNCH_REVIEW_MISSING');Seq 'blockers' $c.blockers $expected;Eq 'first missing' $c.firstMissingBoundary $expected[0];Eq 'first technical' $c.firstTechnicalBoundary $expected[1]
$v=$c.staticPreparation.movementReceiptV2;Eq 'v2 status' $v.status 'OFFLINE_MOVEMENT_RECEIPT_V2_SCHEMA_PASS_RUNTIME_UNSEEN';Eq 'schema status' $v.schemaStatus 'PASS';Eq 'dialect' $v.schemaDialect '2020-12';Eq 'groups' $v.fieldGroupCount 8;Eq 'template' $v.templateState 'EMPTY_TEMPLATE_NOT_LIVE';Eq 'synthetic' $v.syntheticState 'SYNTHETIC_SEMANTIC_SPECIMEN';Eq 'phases' $v.phaseCount 10;Eq 'commands' $v.commandCount 18;Eq 'hits' $v.acceptedHitCount 9;Eq 'thread phases' $v.threadPhaseCount 10;Eq 'no miss' $v.runtimeNoMissProof 'MISSING';Eq 'runtime receipt' $v.runtimeReceiptStatus 'MISSING';Eq 'live install' $v.liveInstallationStatus 'MISSING';Eq 'live eligible' $v.liveReceiptEligible $false
$forbidden=@('reuse prior permit/run/PID/HWND/module base/pointer/coordinate','live attach, breakpoint installation, process-memory access, capture, or input in this schema unit','software INT3, empty-address bphwc, DR-slot-number dependency, singleshoot, automatic breakpoint command, or process-memory write','DBG_REPLY_LATER','binary/resource patch','VM lifecycle or server/protocol/database change','v1, fixture, schema validity, static semantics, or synthetic receipt promotion to live evidence');Seq 'forbidden' $c.forbidden $forbidden
$counterNames=@('guestOperations','debuggerAttach','debuggerCommands','breakpointsInstalled','processMemoryReads','processMemoryWrites','captures','physicalInputs');Seq 'counters' @($c.operationCounters.PSObject.Properties.Name) $counterNames;foreach($n in $counterNames){Eq "counter $n" $c.operationCounters.$n 0}
if($loaded.ContainsKey('priorV7Contract')){$p=$loaded.priorV7Contract;Eq 'v7 state' $p.state 'OFFLINE_PRELAUNCH_HARDWARE_REARM_PLAN_INTEGRATED_RECEIPT_V2_MISSING_READY_FALSE';Eq 'v7 count' @($p.blockers).Count 12;$derived=@($p.blockers|Where-Object{$_-ne'MOVEMENT_RECEIPT_TEMPORAL_THREAD_CORRELATION_SCHEMA_MISSING'});$derived=@($derived[0..1])+$introduced+@($derived[2..($derived.Count-1)]);Seq 'v7 delta' $c.blockers $derived}
if($loaded.ContainsKey('priorV7FinalVerification')){$f=$loaded.priorV7FinalVerification;Eq 'v7 final' $f.result 'PASS';Eq 'v7 review' $f.independentReview 'APPROVE';Eq 'v7 live' $f.liveOperations 0;Eq 'v7 permit' $f.permitIssued $false}
if($loaded.ContainsKey('priorV7ArtifactLedger')){Eq 'v7 ledger count' @($loaded.priorV7ArtifactLedger.artifacts).Count 10}
if($loaded.ContainsKey('receiptV2Schema')){Eq 'v2 dialect actual' $loaded.receiptV2Schema.'$schema' 'https://json-schema.org/draft/2020-12/schema';Eq 'v2 closed' $loaded.receiptV2Schema.additionalProperties $false}
if($loaded.ContainsKey('receiptV2Template')){Eq 'template actual' $loaded.receiptV2Template.state 'EMPTY_TEMPLATE_NOT_LIVE';Eq 'template live actual' $loaded.receiptV2Template.evaluation.liveReceiptEligible $false;Eq 'template no miss actual' $loaded.receiptV2Template.evaluation.runtimeNoMissProof 'MISSING'}
if($loaded.ContainsKey('receiptV2Specimen')){Eq 'specimen actual' $loaded.receiptV2Specimen.state 'SYNTHETIC_SEMANTIC_SPECIMEN';Eq 'specimen phases actual' @($loaded.receiptV2Specimen.phaseExecutionLedger.phases).Count 10;Eq 'specimen commands actual' $loaded.receiptV2Specimen.phaseExecutionLedger.commandCount 18;Eq 'specimen live actual' $loaded.receiptV2Specimen.evaluation.liveReceiptEligible $false}
if($loaded.ContainsKey('migrationMatrix')){Eq 'migration promotion' $loaded.migrationMatrix.automaticMigrationAllowed $false;Eq 'migration fields' @($loaded.migrationMatrix.fieldGroups).Count 8}
if($loaded.ContainsKey('debuggerSemantics')){Eq 'semantic event' $loaded.debuggerSemantics.claims.debugEventSuspendsAffectedProcessThreadsUntilContinueDebugEvent 'AUTHORITATIVE_STATIC_PASS';Eq 'semantic instruction' $loaded.debuggerSemantics.claims.instructionBreakpointFaultsBeforeInstructionExecution 'AUTHORITATIVE_STATIC_PASS';Eq 'semantic runtime' $loaded.debuggerSemantics.claims.actualG7MTClientRearmContinuity 'RUNTIME_UNSEEN'}
if($errors.Count-eq0){try{$t=&$paths.receiptV2Tests|ConvertFrom-Json;Eq 'v2 test result' $t.result 'PASS';Eq 'v2 cases' $t.cases 78;Eq 'v2 assertions' $t.assertions 101;Eq 'v2 mutations' $t.mutations 74}catch{$errors.Add("v2 tests failed: $($_.Exception.Message)")}}
if($errors.Count-eq0){try{$schemaResult=&python $paths.jsonSchemaValidator $paths.receiptV2Schema $paths.receiptV2Template $paths.receiptV2Specimen|ConvertFrom-Json;Eq 'schema validation' $schemaResult.result 'PASS';Eq 'schema documents' $schemaResult.documents 2}catch{$errors.Add("schema validation failed: $($_.Exception.Message)")}}
if($errors.Count-eq0){try{$tr=&$paths.receiptV2Verifier -ReceiptPath $paths.receiptV2Template|ConvertFrom-Json;$sr=&$paths.receiptV2Verifier -ReceiptPath $paths.receiptV2Specimen|ConvertFrom-Json;Eq 'template semantic' $tr.result 'PASS';Eq 'template semantic state' $tr.state 'EMPTY_TEMPLATE_NOT_LIVE';Eq 'specimen semantic' $sr.result 'PASS';Eq 'specimen semantic state' $sr.state 'SYNTHETIC_SEMANTIC_SPECIMEN';Eq 'specimen semantic groups' $sr.fieldGroupCount 8;Eq 'specimen semantic live' $sr.liveReceiptEligible $false}catch{$errors.Add("v2 semantic verification failed: $($_.Exception.Message)")}}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors)}|ConvertTo-Json -Depth 20;return}
[ordered]@{result='PASS';state=$c.state;blockerCount=@($c.blockers).Count;firstMissingBoundary=$c.firstMissingBoundary;firstTechnicalBoundary=$c.firstTechnicalBoundary;receiptV2SchemaBlockerResolved=1;receiptV2FieldGroupCount=$v.fieldGroupCount;runtimeReceiptStatus=$v.runtimeReceiptStatus;liveOperations=0;gameInputs=0;permitIssued=$false}|ConvertTo-Json
