[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ReceiptPath)
$ErrorActionPreference='Stop'
$unitRoot=Split-Path -Parent $PSScriptRoot
$repoRoot=(Resolve-Path (Join-Path $unitRoot '..\..')).Path
$receipt=Get-Content -LiteralPath $ReceiptPath -Raw -Encoding UTF8|ConvertFrom-Json
$schema=Get-Content -LiteralPath (Join-Path $unitRoot 'evidence/movement-breakpoint-receipt-v2.schema.json') -Raw -Encoding UTF8|ConvertFrom-Json
$migration=Get-Content -LiteralPath (Join-Path $unitRoot 'evidence/v1-v2-migration-matrix.json') -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[Collections.Generic.List[string]]::new()
function Add-Error($m){$errors.Add([string]$m)}
function Eq($n,$a,$e){if($a-ne$e){Add-Error "$n expected=$e actual=$a"}}
function Seq($n,$a,$e){$aa=if($null-eq$a){@()}else{@($a)};$ee=if($null-eq$e){@()}else{@($e)};if(($aa|ConvertTo-Json -Compress -Depth 20)-ne($ee|ConvertTo-Json -Compress -Depth 20)){Add-Error "$n sequence mismatch"}}
function Is-Sha($v){$null-ne$v-and[string]$v-match'^[0-9A-F]{64}$'}
function Is-Hex($v){$null-ne$v-and[string]$v-match'^0x[0-9A-F]+$'}
function Hex-U64($v){[Convert]::ToUInt64(([string]$v).Substring(2),16)}
function Runtime-Address($base,$rva){'0x{0:X8}'-f((Hex-U64 $base)+(Hex-U64 $rva))}
function Repo-Path($p){Join-Path $repoRoot ([string]$p)}
function Bound-File($name,$path,$sha){$p=Repo-Path $path;if(-not(Test-Path -LiteralPath $p)){Add-Error "$name missing";return $null};Eq "$name hash" (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash ([string]$sha).ToUpperInvariant();return $p}
function Canonical($ids,$order){@($order|Where-Object{@($ids)-contains$_})}
function Expected-LocalDr7([int]$slotCount){$mask=[uint64]0;for($slot=0;$slot-lt$slotCount;$slot++){$mask=$mask-bor([uint64]1-shl(2*$slot))};$mask}

$short=@('MVB01','MVB02','MVB03','MVB04','MVB05','MVB06','MVB07','MVB08','MVB09')
$full=@('MVB01_HANDLER_CALLBACK','MVB02_PAYLOAD_READY','MVB03_EXPECTED_SET','MVB04_COMMAND_SET','MVB05_TRANSPORT_SEND','MVB06_NOTIFY_DISPATCH','MVB07_NOTIFY_APPLIED','MVB08_EXPECTED_OPCODE_COMPARE','MVB09_QUEUE_DECREMENTED')
$rvas=@('0x001737D0','0x000B490E','0x000B7EDE','0x000B7EE3','0x000B85B6','0x000BCF4F','0x000BCF7E','0x000BDD91','0x000BDDE2')
$fieldIds=@('HIT_THREAD_ID_AND_DEBUG_EVENT_ORDINAL','TEMPORAL_REARM_PHASE_LEDGER','PER_THREAD_DR_STATE_RECEIPT','REJECTED_HIT_LOG','UNIQUE_PENDING_0X0B07_QUEUE_CENSUS','REARM_PLAN_VERSION_AND_ARTIFACT_SHA256','INSTALLED_X32DBG_EXE_DLL_GUI_AND_COMMITHASH_BINDING','PER_PHASE_BPHWC_BPHWS_COMMAND_RESULT_PRE_POST_ACTIVE_SET_AND_BEFORE_RESUME_VERIFICATION')
$pointers=@('/acceptedHits','/phaseExecutionLedger/phases','/perThreadDrState','/rejectedHitLog','/queueCensus','/rearmPlanBinding','/debuggerBuildBinding','/phaseExecutionLedger/phases/*')
$schedule=@'
[
 {"before":[],"after":["MVB01","MVB06","MVB08","MVB09"],"next":"MVB01"},
 {"before":["MVB01","MVB06","MVB08","MVB09"],"after":["MVB02","MVB06","MVB08","MVB09"],"next":"MVB02"},
 {"before":["MVB02","MVB06","MVB08","MVB09"],"after":["MVB03","MVB06","MVB08","MVB09"],"next":"MVB03"},
 {"before":["MVB03","MVB06","MVB08","MVB09"],"after":["MVB04","MVB06","MVB08","MVB09"],"next":"MVB04"},
 {"before":["MVB04","MVB06","MVB08","MVB09"],"after":["MVB05","MVB06","MVB08","MVB09"],"next":"MVB05"},
 {"before":["MVB05","MVB06","MVB08","MVB09"],"after":["MVB06","MVB07","MVB08","MVB09"],"next":"MVB06"},
 {"before":["MVB06","MVB07","MVB08","MVB09"],"after":["MVB06","MVB07","MVB08","MVB09"],"next":"MVB07"},
 {"before":["MVB06","MVB07","MVB08","MVB09"],"after":["MVB06","MVB07","MVB08","MVB09"],"next":"MVB08"},
 {"before":["MVB06","MVB07","MVB08","MVB09"],"after":["MVB06","MVB07","MVB08","MVB09"],"next":"MVB09"},
 {"before":["MVB06","MVB07","MVB08","MVB09"],"after":[],"next":null}
]
'@|ConvertFrom-Json

$schemaPath=Join-Path $unitRoot 'evidence/movement-breakpoint-receipt-v2.schema.json'
$schemaValidator=Join-Path $unitRoot '..\20260828-original-client-movement-breakpoint-receipt-schema\tests\validate-json-schema.py'
try{
 $schemaOutput=(& python $schemaValidator $schemaPath $ReceiptPath $ReceiptPath 2>&1|Out-String).Trim();$schemaExit=$LASTEXITCODE
 if($schemaExit-ne0){Add-Error "receipt JSON Schema validation failed: $schemaOutput"}else{$schemaResult=$schemaOutput|ConvertFrom-Json;Eq 'receipt schema validation' $schemaResult.result 'PASS';Eq 'receipt schema dialect' $schemaResult.dialect '2020-12'}
}catch{Add-Error "receipt JSON Schema validator failed: $($_.Exception.Message)"}

try{
 Eq 'schema dialect' $schema.'$schema' 'https://json-schema.org/draft/2020-12/schema';Eq 'schema closed' $schema.additionalProperties $false
 Eq 'schema version' $receipt.schemaVersion 2;Eq 'receipt type' $receipt.receiptType 'ORIGINAL_CLIENT_MOVEMENT_BREAKPOINT_RECEIPT_V2';Eq 'permit' $receipt.permitIssued $false
 Eq 'migration policy' $migration.policy 'NO_AUTOMATIC_EVIDENCE_PROMOTION';Eq 'migration automatic' $migration.automaticMigrationAllowed $false;Eq 'migration synthetic' $migration.syntheticMayBecomeLive $false
 foreach($p in $migration.v1FrozenArtifacts.PSObject.Properties){$null=Bound-File "frozen $($p.Name)" $p.Value.path $p.Value.sha256}

 Eq 'coverage count' @($receipt.v2Coverage).Count 8
 for($i=0;$i-lt[Math]::Min(8,@($receipt.v2Coverage).Count);$i++){Eq "coverage[$i] id" $receipt.v2Coverage[$i].fieldId $fieldIds[$i];Eq "coverage[$i] pointer" $receipt.v2Coverage[$i].jsonPointer $pointers[$i]}
 Eq 'alias count' @($receipt.anchorAliases).Count 9
 for($i=0;$i-lt[Math]::Min(9,@($receipt.anchorAliases).Count);$i++){Eq "alias[$i] short" $receipt.anchorAliases[$i].shortId $short[$i];Eq "alias[$i] full" $receipt.anchorAliases[$i].fullId $full[$i];Eq "alias[$i] order" $receipt.anchorAliases[$i].order ($i+1);Eq "alias[$i] rva" $receipt.anchorAliases[$i].rva $rvas[$i]}

 $basePath=Bound-File 'base receipt' $receipt.baseReceiptBinding.path $receipt.baseReceiptBinding.sha256
 $baseVerifier=Bound-File 'base verifier' $receipt.baseReceiptBinding.verifierPath $receipt.baseReceiptBinding.verifierSha256
 $base=$null;$baseResult=$null
 if($basePath){$base=Get-Content -LiteralPath $basePath -Raw -Encoding UTF8|ConvertFrom-Json;Eq 'base expected state' $base.state $receipt.baseReceiptBinding.expectedState;Eq 'base expected runtime' $base.runtimeBindingStatus $receipt.baseReceiptBinding.expectedRuntimeBindingStatus}
 if($basePath-and$baseVerifier){try{$baseResult=&$baseVerifier -ReceiptPath $basePath|ConvertFrom-Json;Eq 'base verifier result' $baseResult.result 'PASS';Eq 'base verifier state' $baseResult.state $receipt.baseReceiptBinding.expectedState}catch{Add-Error "base verifier failed: $($_.Exception.Message)"}}

 $planPath=Bound-File 'rearm plan' $receipt.rearmPlanBinding.path $receipt.rearmPlanBinding.sha256
 $reviewPath=Bound-File 'rearm review' $receipt.rearmPlanBinding.reviewPath $receipt.rearmPlanBinding.reviewSha256
 $semanticsPath=Bound-File 'debugger semantics' $receipt.rearmPlanBinding.debuggerSemanticsPath $receipt.rearmPlanBinding.debuggerSemanticsSha256
 $plan=$null;if($planPath){$plan=Get-Content -LiteralPath $planPath -Raw -Encoding UTF8|ConvertFrom-Json;Eq 'plan id' $receipt.rearmPlanBinding.planId $plan.plan;Eq 'plan schema' $receipt.rearmPlanBinding.schemaVersion $plan.schemaVersion;Eq 'plan trace' $receipt.rearmPlanBinding.traceSha256 'FE3E9046EA15DE5E64F1E7CF1159E3D6F3B72CC94C14AB1200E87B2F7243D8CA';Eq 'plan target' $receipt.rearmPlanBinding.targetSha256 $plan.target.sha256;Eq 'plan ledger' $receipt.rearmPlanBinding.movementLedgerSha256 $plan.sources.movementLedger.sha256}
 Eq 'plan review' $receipt.rearmPlanBinding.reviewStatus 'APPROVE';Eq 'event suspension' $receipt.rearmPlanBinding.debugEventSuspensionEvidence 'AUTHORITATIVE_STATIC_PASS';Eq 'instruction timing' $receipt.rearmPlanBinding.executeBreakpointTimingEvidence 'AUTHORITATIVE_STATIC_PASS';Eq 'runtime no miss binding' $receipt.rearmPlanBinding.runtimeNoMissProof 'MISSING'
 if($semanticsPath){$sem=Get-Content -LiteralPath $semanticsPath -Raw -Encoding UTF8|ConvertFrom-Json;Eq 'sem event' $sem.claims.debugEventSuspendsAffectedProcessThreadsUntilContinueDebugEvent 'AUTHORITATIVE_STATIC_PASS';Eq 'sem timing' $sem.claims.instructionBreakpointFaultsBeforeInstructionExecution 'AUTHORITATIVE_STATIC_PASS';Eq 'sem runtime' $sem.claims.actualG7MTClientRearmContinuity 'RUNTIME_UNSEEN'}

 Eq 'debugger arch' $receipt.debuggerBuildBinding.architecture 'x86';Eq 'debugger commit' $receipt.debuggerBuildBinding.commit '9c8ca1cae0b6d56cc44f31fddcb10e3b02ffbb87';Eq 'commit normalized' $receipt.debuggerBuildBinding.commitHashFile.normalizedContent $receipt.debuggerBuildBinding.commit;Eq 'commit hash' $receipt.debuggerBuildBinding.commitHashFile.sha256 '80A7077840C2DD987861A857DB19C06279408E0344B0AD13538217075A0E2C67'
 $commitFile=([string]$receipt.debuggerBuildBinding.commitHashFile.path)-replace'/','\';if(-not(Test-Path -LiteralPath $commitFile)){Add-Error 'commit file missing'}else{Eq 'commit actual hash' (Get-FileHash -LiteralPath $commitFile -Algorithm SHA256).Hash $receipt.debuggerBuildBinding.commitHashFile.sha256;Eq 'commit actual content' ((Get-Content -LiteralPath $commitFile -Raw).Trim()) $receipt.debuggerBuildBinding.commit}
 $expectedRoles=@('x32dbg.exe','x32dbg.dll','x32gui.dll');$expectedHashes=@('822028F0755DBA773E445EAF57FDB3DBA84C9550AC7BDAD2AFA449912B5FBA41','1C2A4A10E0D1C33FE230277E3A4C64AE5E18C165C9D6AED58B1F37E2CE9812FC','74090ABE1FF077AB0C56F3B96D18314E7706B867345ABDD05891652F69A96853');Eq 'debugger file count' @($receipt.debuggerBuildBinding.files).Count 3
 for($i=0;$i-lt[Math]::Min(3,@($receipt.debuggerBuildBinding.files).Count);$i++){$f=$receipt.debuggerBuildBinding.files[$i];Eq "debugger[$i] role" $f.role $expectedRoles[$i];Eq "debugger[$i] hash" $f.sha256 $expectedHashes[$i];$p=([string]$f.path)-replace'/','\';if(-not(Test-Path -LiteralPath $p)){Add-Error "debugger[$i] missing"}else{Eq "debugger[$i] actual" (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash $f.sha256}}
 foreach($n in @('processMemoryWrites','softwareInt3Breakpoints','automaticInputs','binaryPatches','vmLifecycleChanges','serverProtocolDbChanges')){Eq "operation $n" $receipt.operations.$n 0}
 Eq 'evaluation no miss' $receipt.evaluation.runtimeNoMissProof 'MISSING';Eq 'evaluation live' $receipt.evaluation.liveReceiptEligible $false

 if($receipt.state-eq'EMPTY_TEMPLATE_NOT_LIVE'){
  Eq 'template source' $receipt.sourceMode 'NOT_RUN';Eq 'template runtime' $receipt.runtimeBindingStatus 'UNSEEN';foreach($c in $receipt.v2Coverage){Eq "template coverage $($c.fieldId)" $c.status 'MISSING'};Eq 'template phases' @($receipt.phaseExecutionLedger.phases).Count 0;Eq 'template hits' @($receipt.acceptedHits).Count 0;Eq 'template threads' @($receipt.perThreadDrState.snapshots).Count 0;Eq 'template lifecycle' @($receipt.perThreadDrState.lifecycleEvents).Count 0;Eq 'template rejected' @($receipt.rejectedHitLog.entries).Count 0;Eq 'template queue entries' @($receipt.queueCensus.entries).Count 0;Eq 'template queue unique' $receipt.queueCensus.uniquePendingExpected0B07 $false;foreach($p in $receipt.operations.PSObject.Properties){Eq "template op $($p.Name)" $p.Value 0};Eq 'template review' $receipt.review.status 'NOT_REVIEWED'
 }
 elseif($receipt.state-eq'SYNTHETIC_SEMANTIC_SPECIMEN'){
  Eq 'specimen source' $receipt.sourceMode 'SYNTHETIC_TEST_ONLY';Eq 'specimen runtime' $receipt.runtimeBindingStatus 'SYNTHETIC_SPECIMEN_ONLY';Eq 'specimen debugger binding' $receipt.debuggerBuildBinding.bindingMode 'SYNTHETIC_TEST_ONLY';foreach($c in $receipt.v2Coverage){Eq "specimen coverage $($c.fieldId)" $c.status 'SYNTHETIC_ONLY'}
  if($null-eq$base-or-not(Is-Hex $base.client.moduleBase)){Add-Error 'synthetic base module missing'}else{$moduleBase=$base.client.moduleBase}
  $runtime=@{};for($i=0;$i-lt9;$i++){$runtime[$short[$i]]=Runtime-Address $moduleBase $rvas[$i]}
  Eq 'continue policy' $receipt.phaseExecutionLedger.continuePolicy 'CONTINUE_DEBUG_EVENT_NO_DBG_REPLY_LATER';Eq 'phase count declared' $receipt.phaseExecutionLedger.phaseCount 10;Eq 'phase count' @($receipt.phaseExecutionLedger.phases).Count 10;Eq 'trace' $receipt.phaseExecutionLedger.traceSha256 $receipt.rearmPlanBinding.traceSha256;Eq 'peak' $receipt.phaseExecutionLedger.peakActiveSlots 4
  $commandOrdinal=0;$setCount=0;$deleteCount=0;$allCommands=[Collections.Generic.List[object]]::new()
  for($i=0;$i-lt[Math]::Min(10,@($receipt.phaseExecutionLedger.phases).Count);$i++){
   $p=$receipt.phaseExecutionLedger.phases[$i];$phaseSuffix=if($i-eq0){'INITIAL'}else{'AFTER_'+$short[$i-1]};Eq "phase[$i] ordinal" $p.phaseOrdinal $i;Eq "phase[$i] id" $p.phaseId ('P{0:D2}_{1}'-f$i,$phaseSuffix);Seq "phase[$i] before" $p.activeBefore $schedule[$i].before;Seq "phase[$i] after" $p.activeAfter $schedule[$i].after;Eq "phase[$i] next" $p.nextRequiredAnchorShortId $schedule[$i].next;Eq "phase[$i] stopped" $p.targetStoppedForEntireMutation $true;Eq "phase[$i] snapshot id" $p.perThreadSnapshotId ('S{0:D2}'-f$i)
   if(@($p.activeBefore).Count-gt4-or@($p.activeAfter).Count-gt4){Add-Error "phase[$i] slot overflow"};Seq "phase[$i] canonical before" $p.activeBefore (Canonical $p.activeBefore $short);Seq "phase[$i] canonical after" $p.activeAfter (Canonical $p.activeAfter $short)
   if($i-eq0){Eq 'phase0 trigger' $p.triggerAnchorShortId $null;Eq 'phase0 event' $p.triggerDebugEventOrdinal $null}else{Eq "phase[$i] trigger" $p.triggerAnchorShortId $short[$i-1]}
   $fold=[Collections.Generic.List[string]]::new();foreach($id in @($p.activeBefore)){$fold.Add([string]$id)}
   foreach($cmd in @($p.commands)){$commandOrdinal++;$allCommands.Add($cmd);Eq "command[$commandOrdinal] ordinal" $cmd.globalCommandOrdinal $commandOrdinal;Eq "command[$commandOrdinal] result" $cmd.result 'SUCCESS';Eq "command[$commandOrdinal] error" $cmd.errorCode 0;Eq "command[$commandOrdinal] automatic" $cmd.automatic $false;if(-not(Is-Sha $cmd.rawOutputSha256)){Add-Error "command[$commandOrdinal] output hash"};Eq "command[$commandOrdinal] address" $cmd.runtimeAddress $runtime[$cmd.anchorShortId];if($cmd.operation-eq'SET'){$setCount++;Eq "command[$commandOrdinal] text" $cmd.command ("bphws $($cmd.runtimeAddress), x, 1");if($fold.Contains($cmd.anchorShortId)){Add-Error "command[$commandOrdinal] duplicate set"}else{$fold.Add($cmd.anchorShortId)}}elseif($cmd.operation-eq'DELETE'){$deleteCount++;Eq "command[$commandOrdinal] text" $cmd.command ("bphwc $($cmd.runtimeAddress)");if(-not$fold.Contains($cmd.anchorShortId)){Add-Error "command[$commandOrdinal] delete absent"}else{$fold.Remove($cmd.anchorShortId)|Out-Null}}else{Add-Error "command[$commandOrdinal] operation"}}
   Seq "phase[$i] fold" (Canonical @($fold) $short) $p.activeAfter
   if($i-lt9){Eq "phase[$i] verify" $p.beforeResumeVerification 'PASS';Eq "phase[$i] resume" $p.resumeIssued $true;if(-not(Is-Sha $p.resumeAuthorizationSha256)){Add-Error "phase[$i] resume auth"};if(@($p.activeAfter)-notcontains$p.nextRequiredAnchorShortId){Add-Error "phase[$i] next not armed"}}else{Eq 'phase9 verify' $p.beforeResumeVerification 'SEALED_STOPPED';Eq 'phase9 resume' $p.resumeIssued $false;Eq 'phase9 auth' $p.resumeAuthorizationSha256 $null}
  }
  Eq 'command declared' $receipt.phaseExecutionLedger.commandCount $commandOrdinal;Eq 'command exact total' $commandOrdinal 18;Eq 'set declared' $receipt.phaseExecutionLedger.setCommandCount $setCount;Eq 'set exact' $setCount 9;Eq 'delete declared' $receipt.phaseExecutionLedger.deleteCommandCount $deleteCount;Eq 'delete exact' $deleteCount 9
   Eq 'accepted count' @($receipt.acceptedHits).Count 9;$acceptedOrdinals=[Collections.Generic.List[int]]::new()
   for($i=0;$i-lt[Math]::Min(9,@($receipt.acceptedHits).Count);$i++){
    $h=$receipt.acceptedHits[$i];$phaseIndex=$i+1;$predecessor=if($i-eq0){$null}else{$short[$i-1]}
    Eq "hit[$i] anchor" $h.anchorShortId $short[$i];Eq "hit[$i] sequence" $h.acceptedSequence $phaseIndex;Eq "hit[$i] phase" $h.phaseOrdinal $phaseIndex;Eq "hit[$i] accepted" $h.acceptedCandidate $true
    Eq "hit[$i] code" $h.exceptionCode '0x80000004';Eq "hit[$i] first" $h.firstChance $true;Eq "hit[$i] pre" $h.preInstruction $true;Eq "hit[$i] exception" $h.exceptionAddress $runtime[$short[$i]];Eq "hit[$i] ip" $h.instructionPointer $h.exceptionAddress;Eq "hit[$i] bpea" $h.breakpointExceptionAddress $h.exceptionAddress;Eq "hit[$i] predecessor" $h.predecessorAnchorShortId $predecessor
    if($h.threadId-le0){Add-Error "hit[$i] thread"};if((-not(Is-Sha $h.debugEventRecordSha256))-or(-not(Is-Sha $h.stackFingerprintSha256))-or(-not(Is-Sha $h.suppressionAuditSha256))-or(-not(Is-Sha $h.preCommandStateSha256))){Add-Error "hit[$i] evidence hash"}
    if($i-gt0-and$h.debugEventOrdinal-le$receipt.acceptedHits[$i-1].debugEventOrdinal){Add-Error "hit[$i] event order"};$acceptedOrdinals.Add([int]$h.debugEventOrdinal);Eq "hit[$i] phase event" $receipt.phaseExecutionLedger.phases[$phaseIndex].triggerDebugEventOrdinal $h.debugEventOrdinal
    $eflags=Hex-U64 $h.eflags;$rf=(($eflags-band[uint64]0x10000)-ne0);Eq "hit[$i] RF declaration" $h.resumeFlagSet $rf;Eq "hit[$i] RF clear" $rf $false;Eq "hit[$i] suppression" $h.predecessorSuppressionClass 'NONE'
    $preDr7=Hex-U64 $h.preCommandDr7;$expectedPreDr7=Expected-LocalDr7 @($schedule[$phaseIndex].before).Count;Eq "hit[$i] pre-command DR7 exact" $preDr7 $expectedPreDr7
    $derivedHit=[Collections.Generic.List[string]]::new();for($slot=0;$slot-lt4;$slot++){if((($preDr7-shr(2*$slot))-band1)-eq1){$addr=$h.("preCommandDr$slot");$match=@($short|Where-Object{$runtime[$_]-eq$addr});if($match.Count-ne1){Add-Error "hit[$i] pre-command slot $slot unresolved"}elseif($derivedHit.Contains($match[0])){Add-Error "hit[$i] pre-command duplicate anchor"}else{$derivedHit.Add($match[0])}}}
    $canonicalHit=Canonical @($derivedHit) $short;Seq "hit[$i] pre-command derived" $canonicalHit $schedule[$phaseIndex].before;Seq "hit[$i] pre-command declared" $h.preCommandActiveAnchorShortIds $canonicalHit
    $triggerSlot=[int]$h.triggerSlotIndex;$preDr6=Hex-U64 $h.preCommandDr6;Eq "hit[$i] trigger slot address" $h.("preCommandDr$triggerSlot") $h.exceptionAddress;Eq "hit[$i] DR6 trigger bits" ($preDr6-band[uint64]0xF) ([uint64]1-shl$triggerSlot);Eq "hit[$i] DR6 BD BS BT clear" ($preDr6-band[uint64]0xE000) ([uint64]0)
    $phaseSnapshot=@($receipt.perThreadDrState.snapshots|Where-Object{$_.phaseOrdinal-eq$phaseIndex})|Select-Object -First 1;if($null-eq$phaseSnapshot-or@($phaseSnapshot.enumeratedThreadIds)-notcontains[int]$h.threadId){Add-Error "hit[$i] thread absent from phase census"}
   }
  foreach($i in 1..4){Eq "outbound thread[$i]" $receipt.acceptedHits[$i].threadId $receipt.acceptedHits[0].threadId};foreach($i in 6..8){Eq "inbound thread[$i]" $receipt.acceptedHits[$i].threadId $receipt.acceptedHits[5].threadId}
  Eq 'thread snapshot count' @($receipt.perThreadDrState.snapshots).Count 10
   $previousThreadIds=@();$previousSnapshotEvent=0;for($i=0;$i-lt[Math]::Min(10,@($receipt.perThreadDrState.snapshots).Count);$i++){
    $snap=$receipt.perThreadDrState.snapshots[$i];Eq "snapshot[$i] id" $snap.snapshotId ('S{0:D2}'-f$i);Eq "snapshot[$i] phase" $snap.phaseOrdinal $i;Eq "snapshot[$i] coverage" $snap.allCurrentThreadsCovered $true
    if($snap.targetState-ne'SYNTHETIC_STOPPED'){Add-Error "snapshot[$i] target state"};if(-not(Is-Sha $snap.threadInventorySha256)){Add-Error "snapshot[$i] inventory hash"}
    if($i-eq0){Eq 'snapshot[0] observation start' $snap.debugEventOrdinal $receipt.rejectedHitLog.observationStartDebugEventOrdinal}else{Eq "snapshot[$i] trigger event" $snap.debugEventOrdinal $receipt.phaseExecutionLedger.phases[$i].triggerDebugEventOrdinal;if($snap.debugEventOrdinal-le$previousSnapshotEvent){Add-Error "snapshot[$i] event order"}}
    $threadIds=@($snap.threads|ForEach-Object{[int]$_.threadId}|Sort-Object);Seq "snapshot[$i] enumerated" @($snap.enumeratedThreadIds|Sort-Object) $threadIds;if(@($threadIds|Select-Object -Unique).Count-ne$threadIds.Count){Add-Error "snapshot[$i] duplicate thread"}
    foreach($th in $snap.threads){Eq "snapshot[$i] context $($th.threadId)" $th.contextReadSuccess $true;if(-not(Is-Sha $th.rawContextSha256)){Add-Error "snapshot[$i] context hash"};$dr7=Hex-U64 $th.dr7;$expectedDr7=Expected-LocalDr7 @($schedule[$i].after).Count;Eq "snapshot[$i] thread $($th.threadId) DR7 exact" $dr7 $expectedDr7;$derived=[Collections.Generic.List[string]]::new();for($slot=0;$slot-lt4;$slot++){$l=[int](($dr7-shr(2*$slot))-band1);if($l){$addr=$th.("dr$slot");$match=@($short|Where-Object{$runtime[$_]-eq$addr});if($match.Count-ne1){Add-Error "snapshot[$i] thread $($th.threadId) slot $slot unresolved"}elseif($derived.Contains($match[0])){Add-Error "snapshot[$i] thread $($th.threadId) duplicate anchor"}else{$derived.Add($match[0])}}};$canonical=Canonical @($derived) $short;Seq "snapshot[$i] thread $($th.threadId) derived" $canonical $schedule[$i].after;Seq "snapshot[$i] thread $($th.threadId) declared" $th.activeAnchorShortIds $canonical}
    if($i-gt0){$created=@($threadIds|Where-Object{$previousThreadIds-notcontains$_});$exited=@($previousThreadIds|Where-Object{$threadIds-notcontains$_});foreach($tid in $created){$events=@($receipt.perThreadDrState.lifecycleEvents|Where-Object{$_.eventType-eq'CREATE_THREAD'-and$_.threadId-eq$tid-and$_.appliedAtPhaseOrdinal-eq$i-and$_.snapshotId-eq$snap.snapshotId-and$_.beforeContinuationVerified-and$_.debugEventOrdinal-gt$previousSnapshotEvent-and$_.debugEventOrdinal-le$snap.debugEventOrdinal});if($events.Count-ne1){Add-Error "snapshot[$i] thread $tid create lifecycle missing"}};foreach($tid in $exited){$events=@($receipt.perThreadDrState.lifecycleEvents|Where-Object{$_.eventType-eq'EXIT_THREAD'-and$_.threadId-eq$tid-and$_.appliedAtPhaseOrdinal-eq$i-and$_.snapshotId-eq$snap.snapshotId-and$_.beforeContinuationVerified-and$_.debugEventOrdinal-gt$previousSnapshotEvent-and$_.debugEventOrdinal-le$snap.debugEventOrdinal});if($events.Count-ne1){Add-Error "snapshot[$i] thread $tid exit lifecycle missing"}}}
    $previousThreadIds=$threadIds;$previousSnapshotEvent=[int]$snap.debugEventOrdinal;Eq "phase[$i] snapshot link" $receipt.phaseExecutionLedger.phases[$i].perThreadSnapshotId $snap.snapshotId
   }
   $lifecycleOrdinal=0;foreach($life in $receipt.perThreadDrState.lifecycleEvents){if($life.debugEventOrdinal-le$lifecycleOrdinal){Add-Error 'lifecycle event order'};$lifecycleOrdinal=[int]$life.debugEventOrdinal;Eq "lifecycle $($life.threadId) before" $life.beforeContinuationVerified $true;$lifePhase=[int]$life.appliedAtPhaseOrdinal;if($lifePhase-le0-or$lifePhase-ge@($receipt.perThreadDrState.snapshots).Count){Add-Error "lifecycle $($life.threadId) invalid phase";continue};$snap=$receipt.perThreadDrState.snapshots[$lifePhase];$previous=$receipt.perThreadDrState.snapshots[$lifePhase-1];Eq "lifecycle $($life.threadId) snapshot" $life.snapshotId $snap.snapshotId;if($life.debugEventOrdinal-le$previous.debugEventOrdinal-or$life.debugEventOrdinal-gt$snap.debugEventOrdinal){Add-Error "lifecycle $($life.threadId) event interval"};if($life.eventType-eq'CREATE_THREAD'){if((@($previous.enumeratedThreadIds)-contains[int]$life.threadId)-or(@($snap.enumeratedThreadIds)-notcontains[int]$life.threadId)){Add-Error "lifecycle $($life.threadId) unmatched create"}}elseif($life.eventType-eq'EXIT_THREAD'){if((@($previous.enumeratedThreadIds)-notcontains[int]$life.threadId)-or(@($snap.enumeratedThreadIds)-contains[int]$life.threadId)){Add-Error "lifecycle $($life.threadId) unmatched exit"}}else{Add-Error "lifecycle $($life.threadId) type"}}
   $rejected=$receipt.rejectedHitLog;$start=[int]$rejected.observationStartDebugEventOrdinal;$end=[int]$rejected.observationEndDebugEventOrdinal;if($start-gt$end){Add-Error 'observation ordinal range'};Eq 'observation end snapshot' $end $receipt.perThreadDrState.snapshots[9].debugEventOrdinal;Eq 'rejected count' $rejected.count @($rejected.entries).Count;Eq 'rejected complete' $rejected.complete $true;if((-not(Is-Sha $rejected.logSha256))-or(-not(Is-Sha $rejected.rawTranscriptSha256))){Add-Error 'rejected transcript hash'}
   $allEvents=[Collections.Generic.List[int]]::new();foreach($x in $acceptedOrdinals){if($x-lt$start-or$x-gt$end){Add-Error 'accepted event outside observation'};$allEvents.Add($x)};foreach($life in $receipt.perThreadDrState.lifecycleEvents){if($life.debugEventOrdinal-lt$start-or$life.debugEventOrdinal-gt$end){Add-Error 'lifecycle event outside observation'};if($allEvents.Contains([int]$life.debugEventOrdinal)){Add-Error 'lifecycle event collision'}else{$allEvents.Add([int]$life.debugEventOrdinal)}}
   $rejectedOrdinal=0;$hardware=[Collections.Generic.List[int]]::new();foreach($x in $acceptedOrdinals){$hardware.Add($x)};foreach($rh in $rejected.entries){if($rh.debugEventOrdinal-le$rejectedOrdinal){Add-Error 'rejected event order'};$rejectedOrdinal=[int]$rh.debugEventOrdinal;if($rh.debugEventOrdinal-lt$start-or$rh.debugEventOrdinal-gt$end){Add-Error 'rejected event outside observation'};if($allEvents.Contains([int]$rh.debugEventOrdinal)){Add-Error 'rejected event collision'}else{$allEvents.Add([int]$rh.debugEventOrdinal)};$hardware.Add([int]$rh.debugEventOrdinal);Eq 'rejected phase advance' $rh.phaseAdvanced $false;Eq 'rejected mutation' $rh.slotMutationCount 0;Eq 'rejected commands' @($rh.commandOrdinals).Count 0;Eq 'rejected resume' $rh.resumeIssued $true;if(-not(Is-Sha $rh.entrySha256)){Add-Error 'rejected entry hash'};$phaseIndex=[int]$rh.phaseOrdinal;$phase=$receipt.phaseExecutionLedger.phases[$phaseIndex];if(@($phase.activeAfter)-notcontains$rh.candidateAnchorShortId){Add-Error 'rejected anchor not active'};Eq 'rejected address' $rh.exceptionAddress $runtime[$rh.candidateAnchorShortId];$phaseSnapshot=$receipt.perThreadDrState.snapshots[$phaseIndex];if(@($phaseSnapshot.enumeratedThreadIds)-notcontains[int]$rh.threadId){Add-Error 'rejected thread absent from phase census'}}
   $hardwareSorted=@($hardware|Sort-Object);Eq 'hardware event count' $rejected.hardwareBreakpointEventCount $hardwareSorted.Count;Seq 'hardware event transcript' $rejected.hardwareBreakpointEventOrdinals $hardwareSorted;for($i=1;$i-lt@($rejected.hardwareBreakpointEventOrdinals).Count;$i++){if($rejected.hardwareBreakpointEventOrdinals[$i]-le$rejected.hardwareBreakpointEventOrdinals[$i-1]){Add-Error 'hardware transcript order'}}
   $q=$receipt.queueCensus;Eq 'queue policy' $q.policy 'EXACTLY_ONE_EXPECTED_0X0B07_AMONG_PENDING';Eq 'queue phase' $q.phaseOrdinal 5;Eq 'queue event' $q.debugEventOrdinal $receipt.acceptedHits[4].debugEventOrdinal;Eq 'queue count' $q.pendingCount @($q.entries).Count;$slots=@($q.entries|ForEach-Object{[int]$_.slot});Seq 'queue slots' $slots @(0..($q.pendingCount-1));$matches=@($q.entries|Where-Object{$_.expectedOpcode-eq'0x0B07'});Eq 'queue match declared' $q.matchingExpectedOpcodeCount $matches.Count;Eq 'queue unique count' $matches.Count 1;Eq 'queue unique' $q.uniquePendingExpected0B07 $true;if($matches.Count-eq1){Eq 'queue selected' $q.selectedQueueSlot $matches[0].slot;Eq 'queue base slot' $q.selectedQueueSlot $base.correlation.queueSlot;Eq 'queue ordinal' $matches[0].movementCommandOrdinal $base.correlation.movementCommandOrdinal;Eq 'queue payload' $matches[0].payloadSha256 $base.correlation.payloadSha256};Eq 'queue post decrement' $q.postDecrementCount ($q.pendingCount-1);Eq 'queue post phase' $q.postDecrementPhaseOrdinal 9;Eq 'queue post event' $q.postDecrementDebugEventOrdinal $receipt.acceptedHits[8].debugEventOrdinal;if((-not(Is-Sha $q.censusSha256))-or(-not(Is-Sha $q.postDecrementEvidenceSha256))){Add-Error 'queue census hash'};foreach($entry in $q.entries){if((-not(Is-Sha $entry.payloadSha256))-or(-not(Is-Sha $entry.rawEntrySha256))){Add-Error 'queue entry hash'}}
  $pre=@($base.hits[7].memoryCaptures|Where-Object{$_.label-eq'queue-count-before'})|Select-Object -First 1;$post=@($base.hits[8].memoryCaptures|Where-Object{$_.label-eq'queue-count-after'})|Select-Object -First 1;if($pre){Eq 'queue base pre count' $q.pendingCount $pre.decodedU32};if($post){Eq 'queue base post count' $q.postDecrementCount $post.decodedU32}
  Eq 'operation commands' $receipt.operations.debuggerCommands $commandOrdinal;Eq 'operation sets' $receipt.operations.successfulSetCommands $setCount;Eq 'operation deletes' $receipt.operations.successfulDeleteCommands $deleteCount;Eq 'specimen review' $receipt.review.status 'NOT_REVIEWED'
 }
 else{Add-Error "offline verifier rejects state $($receipt.state)"}
}
catch{Add-Error "verification exception: $($_.Exception.Message)"}
if($errors.Count){[ordered]@{result='FAIL';errors=@($errors);liveOperations=0;permitIssued=$false}|ConvertTo-Json -Depth 20;return}
$template=$receipt.state-eq'EMPTY_TEMPLATE_NOT_LIVE'
[ordered]@{result='PASS';state=$receipt.state;baseReceiptState=$receipt.baseReceiptBinding.expectedState;fieldGroupCount=@($receipt.v2Coverage).Count;phaseCount=@($receipt.phaseExecutionLedger.phases).Count;acceptedHitCount=@($receipt.acceptedHits).Count;threadPhaseCount=@($receipt.perThreadDrState.snapshots).Count;rejectedHitCount=@($receipt.rejectedHitLog.entries).Count;uniquePendingExpected0B07=if($template){$false}else{$receipt.queueCensus.uniquePendingExpected0B07};runtimeNoMissProof=$receipt.evaluation.runtimeNoMissProof;liveReceiptEligible=$false;liveOperations=0;permitIssued=$false}|ConvertTo-Json -Depth 10
