[CmdletBinding()]
param(
 [int]$TargetProcessId,[string]$ExpectedStartTimeUtc,[string]$ExpectedExecutableSha256,[string]$ExpectedWindowHandle,
 [string]$FixtureMemoryPath,[string]$FixtureIdentityPath,[Parameter(Mandatory=$true)][string]$OutputPath
)
$ErrorActionPreference='Stop'
$canonical='BD19263C10DECC3D58373165A82D42A9267868400D407DA87D5F4F4109AB6E16'
$script:reads=0
function Hex([uint32]$v){'0x{0:X8}'-f$v}
function Add([uint32]$base,[uint64]$offset){$v=[uint64]$base+$offset;if($v-gt[uint32]::MaxValue){throw 'address overflow'};[uint32]$v}
$fixtureMode=![string]::IsNullOrWhiteSpace($FixtureMemoryPath)
if($fixtureMode-ne(![string]::IsNullOrWhiteSpace($FixtureIdentityPath))){throw 'Both fixture paths are required.'}
$handle=[IntPtr]::Zero
if($fixtureMode){$fixture=Get-Content $FixtureMemoryPath -Raw -Encoding UTF8|ConvertFrom-Json;$identity=Get-Content $FixtureIdentityPath -Raw -Encoding UTF8|ConvertFrom-Json -DateKind String}
else{
 if([string]::IsNullOrWhiteSpace($ExpectedExecutableSha256)-or$ExpectedExecutableSha256.ToUpperInvariant()-ne$canonical){throw 'Expected executable SHA-256 is not the canonical G7MTClient target.'}
 if($TargetProcessId-le0-or[string]::IsNullOrWhiteSpace($ExpectedStartTimeUtc)-or[string]::IsNullOrWhiteSpace($ExpectedWindowHandle)){throw 'Live identity is incomplete.'}
 if(-not('Manager65HardenedNative'-as[type])){Add-Type -TypeDefinition @'
using System; using System.Runtime.InteropServices;
public static class Manager65HardenedNative {
 [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left,Top,Right,Bottom; }
 [DllImport("kernel32.dll",SetLastError=true)] public static extern IntPtr OpenProcess(uint a,bool i,int p);
 [DllImport("kernel32.dll",SetLastError=true)] public static extern bool ReadProcessMemory(IntPtr p,IntPtr a,byte[] b,UIntPtr n,out UIntPtr r);
 [DllImport("kernel32.dll")] public static extern bool CloseHandle(IntPtr h);
 [DllImport("user32.dll")] public static extern bool IsWindow(IntPtr h);
 [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);
 [DllImport("user32.dll")] public static extern bool GetClientRect(IntPtr h,out RECT r);
}
'@}
 $process=Get-Process -Id $TargetProcessId;$process.Refresh();if($process.ProcessName-ne'G7MTClient'){throw 'Target is not G7MTClient.'}
 $start=$process.StartTime.ToUniversalTime().ToString('o');if($start-ne([DateTime]::Parse($ExpectedStartTimeUtc).ToUniversalTime().ToString('o'))){throw 'Start time mismatch.'}
 $hash=(Get-FileHash $process.Path -Algorithm SHA256).Hash;if($hash-ne$canonical){throw 'Executable hash mismatch.'}
 $module=('0x{0:X8}'-f$process.MainModule.BaseAddress.ToInt64());if($module-ne'0x00400000'){throw 'Module base mismatch.'}
 $hwnd=[IntPtr][Convert]::ToInt64(($ExpectedWindowHandle-replace'^0x',''),16);if(-not[Manager65HardenedNative]::IsWindow($hwnd)){throw 'Invalid HWND.'}
 [uint32]$owner=0;[void][Manager65HardenedNative]::GetWindowThreadProcessId($hwnd,[ref]$owner);if($owner-ne$TargetProcessId-or$process.MainWindowHandle-ne$hwnd){throw 'HWND ownership mismatch.'}
 $rect=New-Object Manager65HardenedNative+RECT;if(-not[Manager65HardenedNative]::GetClientRect($hwnd,[ref]$rect)){throw 'GetClientRect failed.'}
 $identity=[pscustomobject]@{pid=$process.Id;startTimeUtc=$start;sha256=$hash;moduleBase=$module;hwnd=('0x{0:X8}'-f$hwnd.ToInt64());hwndOwnerPid=$owner;clientWidth=$rect.Right-$rect.Left;clientHeight=$rect.Bottom-$rect.Top;secondHwndOwnerPid=$owner;secondClientWidth=$rect.Right-$rect.Left;secondClientHeight=$rect.Bottom-$rect.Top}
 $handle=[Manager65HardenedNative]::OpenProcess(0x0410,$false,$TargetProcessId);if($handle-eq[IntPtr]::Zero){throw 'OpenProcess read-only failed.'}
}
$moduleBase=if($fixtureMode){[uint32]0x00400000}else{[uint32][Convert]::ToUInt64(([string]$identity.moduleBase-replace'^0x',''),16)}
function VA([uint32]$rva){Add $moduleBase $rva}
function Read-Bytes([uint32]$address,[int]$length){$buffer=[byte[]]::new($length);$got=[UIntPtr]::Zero;if(-not[Manager65HardenedNative]::ReadProcessMemory($handle,[IntPtr][int64]$address,$buffer,[UIntPtr][uint64]$length,[ref]$got)-or$got.ToUInt64()-ne$length){throw "ReadProcessMemory failed at $(Hex $address)"};$script:reads++;,$buffer}
function FV($s,[string]$kind,[uint32]$address){$key=Hex $address;$p=$s.$kind.PSObject.Properties[$key];if($null-eq$p){throw "Missing fixture $kind $key"};$script:reads++;$p.Value}
function U32($s,[uint32]$a){if($fixtureMode){[uint32](FV $s u32 $a)}else{[BitConverter]::ToUInt32((Read-Bytes $a 4),0)}}
function I32($s,[uint32]$a){if($fixtureMode){[int32](FV $s i32 $a)}else{[BitConverter]::ToInt32((Read-Bytes $a 4),0)}}
function U16($s,[uint32]$a){if($fixtureMode){[uint16](FV $s u16 $a)}else{[BitConverter]::ToUInt16((Read-Bytes $a 2),0)}}
function U8($s,[uint32]$a){if($fixtureMode){[byte](FV $s u8 $a)}else{(Read-Bytes $a 1)[0]}}
function F32($s,[uint32]$a){if($fixtureMode){[single](FV $s f32 $a)}else{[BitConverter]::ToSingle((Read-Bytes $a 4),0)}}
function Read-Context($s,[uint32]$root){$nodes=@();$seen=@{};$p=$root;$x=0;$y=0;for($depth=0;$depth-lt16;$depth++){if($p-eq0){throw 'NULL_CONTEXT'};$key=Hex $p;if($seen.ContainsKey($key)){throw 'CONTEXT_CYCLE'};$seen[$key]=$true;$id=U32 $s $p;$active=U8 $s (Add $p 4);$parent=I32 $s (Add $p 8);$lx=I32 $s (Add $p 0xC);$ly=I32 $s (Add $p 0x10);$registry=U32 $s (Add $p 0x30);$nodes+=,[ordered]@{pointer=$key;id=[int]$id;active=[int]$active;parentId=$parent;localX=$lx;localY=$ly;registry=Hex $registry};$x+=$lx;$y+=$ly;if($parent-eq-1){return [ordered]@{nodes=$nodes;resolvedX=$x;resolvedY=$y}};if($parent-lt0-or$parent-gt0x72-or$parent-eq$id-or$registry-eq0){throw 'INVALID_PARENT_CHAIN'};$p=U32 $s (Add $registry ([uint32](4+4*$parent)))};throw 'CONTEXT_DEPTH_EXCEEDED'}
function Read-Widget($s,[uint32]$p,[int]$originX,[int]$originY){if($p-eq0){return [ordered]@{widgetPointer='0x00000000';status='NULL';eligible=$false}};$init=U8 $s (Add $p 8);$selector=U8 $s (Add $p 0xA);$lx=I32 $s (Add $p 0xC);$ly=I32 $s (Add $p 0x10);$localGate=U8 $s (Add $p 0x14);$hit=U8 $s (Add $p 0x15);$active=U8 $s (Add $p 0x18);$render=U8 $s (Add $p 0x1B);$x=I32 $s (Add $p 0x20);$y=I32 $s (Add $p 0x24);$w=I32 $s (Add $p 0x2C);$h=I32 $s (Add $p 0x30);if($selector-ne0){$x+=$lx;$y+=$ly};$x+=$originX;$y+=$originY;$eligible=$init-ne0-and$hit-ne0-and$active-ne0-and$render-ne0-and$w-gt0-and$h-gt0-and($selector-eq0-or$localGate-ne0);[ordered]@{widgetPointer=Hex $p;status='READ';initialized=[int]$init;localSelector=[int]$selector;localGate=[int]$localGate;hitTestEnabled=[int]$hit;activeVisible=[int]$active;renderVisible=[int]$render;width=$w;height=$h;eligible=$eligible;logicalRect=[ordered]@{left=$x;top=$y;right=$x+$w;bottom=$y+$h}}}
function Capture($s){
 $root=VA 0x89E638;$builder=I32 $s $root;$handler=I32 $s (Add $root 4);$strategyMode=I32 $s (Add $root 0xF4)
 $registryHost=U32 $s (VA 0x1E15E2C);$registry=[uint32]0;$registry65=[uint32]0;if($registryHost-ne0){$registry=U32 $s (Add $registryHost 0xC);if($registry-ne0){$registry65=U32 $s (Add $registry 0x198)}}
 $controller=Add $root 0x130;$manager=U32 $s $controller;$context=Read-Context $s $manager;$inputGate=U8 $s (Add $manager 5)
 $page=I32 $s (Add $controller 0x34C);$count=I32 $s (Add $controller 0x350);$selected=I32 $s (Add $controller 0x354);$cardId=I32 $s (Add $controller 0x358)
 $owner=U32 $s (VA 0x3CCFFC);$recordCount=-1;$actions=@();if($owner-ne0-and$cardId-ge0-and$cardId-le0xFFFF){$record=Add (Add $owner 0x3416D8) ([uint64]$cardId*0x46);$recordCount=U8 $s (Add $record 0x1E);if($count-ge1-and$count-le24){for($i=0;$i-lt$count;$i++){$widgetPointer=U32 $s (Add $controller ([uint32](0x30+4*$i)));$command=U16 $s (Add $record ([uint32](0x20+2*$i)));$widget=Read-Widget $s $widgetPointer $context.resolvedX $context.resolvedY;$actions+=,[ordered]@{index=$i;commandId=[int]$command;widgetPointer=$widget.widgetPointer;initialized=$widget.initialized;localSelector=$widget.localSelector;localGate=$widget.localGate;hitTestEnabled=$widget.hitTestEnabled;activeVisible=$widget.activeVisible;renderVisible=$widget.renderVisible;width=$widget.width;height=$widget.height;eligible=$widget.eligible;logicalRect=$widget.logicalRect}}}}
 $scaleX=F32 $s (VA 0x372E2C);$scaleY=F32 $s (VA 0x372E30);$engine=U32 $s (VA 0x3C1B4C);$logicalWidth=I32 $s (Add $engine 0x2A3D8);$logicalHeight=I32 $s (Add $engine 0x2A3DC);$engineRect=[ordered]@{left=I32 $s (Add $engine 0x2A5FC);top=I32 $s (Add $engine 0x2A600);right=I32 $s (Add $engine 0x2A604);bottom=I32 $s (Add $engine 0x2A608)}
 [ordered]@{root=Hex $root;builderMode=$builder;handlerState=$handler;strategyMode=$strategyMode;registryHost=Hex $registryHost;registry=Hex $registry;registry65=Hex $registry65;controller=Hex $controller;manager=Hex $manager;managerInputGate=[int]$inputGate;context=$context;page=$page;actionCount=$count;selectedIndex=$selected;cardId=$cardId;recordActionCount=[int]$recordCount;currentCharacterOwner=Hex $owner;actions=$actions;scaleX=$scaleX;scaleY=$scaleY;logicalWidth=$logicalWidth;logicalHeight=$logicalHeight;engineRect=$engineRect}
}
try{
 $firstSection=if($fixtureMode){$fixture.first}else{$null};$secondSection=if($fixtureMode-and$fixture.second-is[string]){$fixture.first}elseif($fixtureMode){$fixture.second}else{$null};$first=Capture $firstSection;$second=Capture $secondSection
 if(-not$fixtureMode){$process.Refresh();if($process.StartTime.ToUniversalTime().ToString('o')-ne$identity.startTimeUtc-or(Get-FileHash $process.Path -Algorithm SHA256).Hash-ne$canonical-or('0x{0:X8}'-f$process.MainModule.BaseAddress.ToInt64())-ne'0x00400000'-or-not[Manager65HardenedNative]::IsWindow($hwnd)-or$process.MainWindowHandle-ne$hwnd){throw 'Post-capture process/window identity changed.'};[uint32]$owner2=0;[void][Manager65HardenedNative]::GetWindowThreadProcessId($hwnd,[ref]$owner2);$rect2=New-Object Manager65HardenedNative+RECT;if(-not[Manager65HardenedNative]::GetClientRect($hwnd,[ref]$rect2)){throw 'Post-capture GetClientRect failed.'};$identity.secondHwndOwnerPid=$owner2;$identity.secondClientWidth=$rect2.Right-$rect2.Left;$identity.secondClientHeight=$rect2.Bottom-$rect2.Top}
 $stable=(($first|ConvertTo-Json -Depth 20 -Compress)-eq($second|ConvertTo-Json -Depth 20 -Compress));$surfaceStable=([int]$identity.hwndOwnerPid-eq[int]$identity.secondHwndOwnerPid-and[int]$identity.clientWidth-eq[int]$identity.secondClientWidth-and[int]$identity.clientHeight-eq[int]$identity.secondClientHeight);$blockers=@()
 if(([string]$identity.sha256).ToUpperInvariant()-ne$canonical){$blockers+='EXECUTABLE_HASH_MISMATCH'};if($identity.moduleBase-ne'0x00400000'){$blockers+='MODULE_BASE_NOT_0X00400000'};if([int]$identity.pid-le0-or[int]$identity.hwndOwnerPid-ne[int]$identity.pid-or[int]$identity.secondHwndOwnerPid-ne[int]$identity.pid){$blockers+='OWNED_HWND_PID_MISMATCH'};if([int]$identity.clientWidth-le0-or[int]$identity.clientHeight-le0-or[int]$identity.secondClientWidth-le0-or[int]$identity.secondClientHeight-le0){$blockers+='NONPOSITIVE_CLIENT_SURFACE'};if(-not$surfaceStable){$blockers+='OWNED_HWND_SURFACE_TORN'};if(-not$stable){$blockers+='TORN_SNAPSHOT'}
 if($first.engineRect.left-ne0-or$first.engineRect.top-ne0-or$first.engineRect.right-ne[int]$identity.clientWidth-or$first.engineRect.bottom-ne[int]$identity.clientHeight){$blockers+='ENGINE_RECT_HWND_MISMATCH'};if(-not[float]::IsFinite([single]$first.scaleX)-or-not[float]::IsFinite([single]$first.scaleY)-or$first.scaleX-le0-or$first.scaleY-le0){$blockers+='INVALID_SCALE'}elseif([int]$identity.clientWidth-gt0-and[int]$identity.clientHeight-gt0-and([Math]::Abs($first.scaleX-($first.logicalWidth/[double]$identity.clientWidth))-gt0.0001-or[Math]::Abs($first.scaleY-($first.logicalHeight/[double]$identity.clientHeight))-gt0.0001)){$blockers+='SCALE_LOGICAL_SURFACE_MISMATCH'}
 if($first.builderMode-ne2-or$first.handlerState-ne1-or$first.strategyMode-ne2){$blockers+='STRATEGY_ROOT_STATE_MISMATCH'};if($first.registryHost-eq'0x00000000'){$blockers+='MANAGER65_REGISTRY_HOST_NULL'};if($first.registry-eq'0x00000000'){$blockers+='MANAGER65_REGISTRY_NULL'};if($first.registry65-ne$first.manager){$blockers+='MANAGER65_REGISTRY_SLOT_MISMATCH'};if($first.context.nodes[0].id-ne0x65){$blockers+='MANAGER65_ID_MISMATCH'};if($first.context.nodes[0].active-eq0-or$first.managerInputGate-eq0){$blockers+='MANAGER65_CONTEXT_INACTIVE'};if($first.page-lt1-or$first.page-gt5){$blockers+='MANAGER65_PAGE_OUT_OF_RANGE_1_TO_5'};if($first.actionCount-lt1-or$first.actionCount-gt24){$blockers+='MANAGER65_ACTION_COUNT_OUT_OF_RANGE'};if($first.currentCharacterOwner-eq'0x00000000'){$blockers+='CURRENT_CHARACTER_OWNER_NULL'};if($first.recordActionCount-ne$first.actionCount){$blockers+='MANAGER65_RECORD_ACTION_COUNT_MISMATCH'};if($first.selectedIndex-ne-1){$blockers+='MANAGER65_SELECTED_INDEX_NOT_RESET'};if($first.cardId-lt0-or$first.cardId-gt0xFFFF){$blockers+='MANAGER65_BOUND_CARD_ID_INVALID'}
 $matches=@($first.actions|Where-Object{$_.commandId-eq0x2B});if($matches.Count-eq0){$blockers+='ACTION_0X2B_NOT_FOUND'}elseif($matches.Count-gt1){$blockers+='ACTION_0X2B_NOT_UNIQUE'};$warp=if($matches.Count-eq1){$matches[0]}else{$null};if($null-ne$warp){if(-not$warp.eligible){$blockers+='ACTION_0X2B_WIDGET_NOT_ELIGIBLE'};if($warp.logicalRect.left-lt0-or$warp.logicalRect.top-lt0-or$warp.logicalRect.right-gt$first.logicalWidth-or$warp.logicalRect.bottom-gt$first.logicalHeight){$blockers+='ACTION_0X2B_RECT_OUTSIDE_LOGICAL_SURFACE'}}
 $out=[ordered]@{schemaVersion=2;provenance=if($fixtureMode){'SYNTHETIC_FIXTURE'}else{'LIVE_READONLY'};process=$identity;root=[ordered]@{pointer=$first.root;builderMode=$first.builderMode;handlerState=$first.handlerState;strategyMode=$first.strategyMode};manager65=[ordered]@{controllerPointer=$first.controller;managerPointer=$first.manager;managerId=$first.context.nodes[0].id;managerInputGate=$first.managerInputGate;page=$first.page;cardId=$first.cardId;actionCount=$first.actionCount;recordActionCount=$first.recordActionCount;recordActionCountMatches=($first.recordActionCount-eq$first.actionCount);selectedIndex=$first.selectedIndex;registryHostPointer=$first.registryHost;registryPointer=$first.registry;registrySlotPointer=$first.registry65;registrySlotMatches=($first.registry65-eq$first.manager);currentCharacterOwnerPointer=$first.currentCharacterOwner;contextChain=$first.context.nodes;actions=$first.actions};coordinateFrame=[ordered]@{type='LOGICAL_TO_CLIENT_TRUNCATE_SCALE';logicalOrigin=[ordered]@{x=$first.context.resolvedX;y=$first.context.resolvedY};scaleX=$first.scaleX;scaleY=$first.scaleY;logicalWidth=$first.logicalWidth;logicalHeight=$first.logicalHeight;engineClientRect=$first.engineRect};action0x2B=[ordered]@{semantic='CURRENT_AUTHORITY_CARD_ACTION_WIDGET_FOR_COMMAND_0X2B_WARP_NAVIGATION';match=$warp};snapshotStable=$stable;windowSurfaceStable=$surfaceStable;stateEligible=(@($blockers).Count-eq0);blockers=@($blockers);originalRuntimeObserved=$false;permitIssued=$false;operations=[ordered]@{memoryReads='READ_ONLY';memoryReadCount=$script:reads;writes=0;gameInputs=0;breakpointsInstalled=0}}
 $dir=Split-Path $OutputPath;if($dir-and-not(Test-Path $dir)){New-Item -ItemType Directory $dir|Out-Null};$out|ConvertTo-Json -Depth 20|Set-Content $OutputPath -Encoding UTF8
}finally{if($handle-ne[IntPtr]::Zero){[void][Manager65HardenedNative]::CloseHandle($handle)}}
